### ISSUE TITLE
Improve style of donor delete screen

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#1197]
## Issue Overview
Donor delete page styling is not looking good. I think check box sholud be left align.

#### before
<img width="1134" alt="screen shot 2016-11-02 at 11 24 09 am" src="https://cloud.githubusercontent.com/assets/1784821/19918120/e8262db0-a0ee-11e6-8952-fb3d6de1340a.png">

#### suggestion
<img width="1143" alt="screen shot 2016-11-02 at 11 28 08 am" src="https://cloud.githubusercontent.com/assets/1784821/19918223/81ed3cfe-a0ef-11e6-98e1-37c6464c07b0.png">

**Comment by mathetos** [comment]
Personally, I've never liked that "Delete Donor" is it's own Tab. I'd rather it be a link floated right that opens a modal with those options.

**Comment by ravinderk** [comment]
@mathetos I agreed with you there is no need of delete donor tab. We can manage this with a popup and it can be implemented on donor edit and list screen. 

@DevinWalker Let me know what do you think?

**Comment by DevinWalker** [comment]
Totally, I think we should improve the donor UI entirely. I've been meaning to create an issue for that.

**Comment by ramiy** [comment]
From accessibility point of view, the button text should be "**Delete Donor**".

**Comment by ramiy** [comment]
We can also merge the "Notes" tab to the main Donor screen. Removing the tabs entirely. And we can use the same layout we have in the "Donation" screen. The notes will be in a separate metabox. And each component can have it's own metabox.

**Comment by DevinWalker** [comment]
Closing in favor of a full revamp of the donor screens.
