### ISSUE TITLE
fix: clarify minimum amount with "Reveal on Click" method

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#1360]
## Issue Overview

Donor could be confused about the minimum donation amount when using the "Reveal on Click" method because if they click "Donate" twice it does actually open the form regardless of whether they entered a proper minimum amount or not.

## Expected Behavior
The form should not be revealed if they do not enter the minimum amount regardless of how many times they click the "Donate" button.

## Current Behavior
Currently, if they enter an amount that is too small, and click twice on the reveal button, the form will open. But, the donor will see the error AGAIN if they click on the final DONATE button; which just makes for a bad experience overall.

## Possible Solution
I believe it's related to this issue:
https://github.com/WordImpress/Give/issues/712

Also, it seems we addressed this a while back ( https://github.com/WordImpress/Give/issues/44 ) but there was another recent issue about clicking the modal button twice a pre-populating the default minimum (and I can't find that issue # anywhere) which I think re-introduced this issue.

## Steps to Reproduce (for bugs)
1. Create a form with a custom minimum amount of $5
2. Set the display method to "Reveal Upon Click"
3. Go to the form and enter $2 as your amount, click once and the error appears; click again and the form is revealed.

**Comment by mikejhale** [comment]
Closing as we will be deprecating the reveal on click method
