### ISSUE TITLE
Add height: inherit to inputs to prevent theme conflits

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#1779]
## Issue Overview
Themes sometimes erroneously add a height to their input fields. Because we don't have a height rule at all it always messes with our Floating labels feature.

Here's an example:
https://wordpress.org/support/topic/billing-details-forms-misaligmnet/

## Expected Behavior
Fields should be tall enough to nest the floating labels in them correctly.

## Current Behavior
If a theme sets a height for `select` or `input` then they get messed up, even without `!important`

## Possible Solution
Add `height: inherit;` to
`form[id*=give-form] .form-row select,
form[id*=give-form] .form-row input`

There may be more inputs that we have to consider or specificity issues to watch for as well.

**Comment by mikejhale** [comment]
Will be address with focus on rebuilding Form UI
