### ISSUE TITLE
Markup errors when running W3 Validator

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#1798]
## Issue Overview
Our markup should be valid at all times. The W3 Validator is not perfect, but the issues it's highlighting here are valid in this case.

## Current Behavior
Run W3 Validator on this URL:
http://demo.gloriathemes.com/wp/charitywp/donations/donate-for-kindergarten-students/

Here are the results:
https://validator.w3.org/nu/?doc=http%3A%2F%2Fdemo.gloriathemes.com%2Fwp%2Fcharitywp%2Fdonations%2Fdonate-for-kindergarten-students%2F

Here are the errors listed:
- [ ] 1. Error: Element option without attribute label must not be empty. From line 494, column 22; to line 494, column 30  `value=""></option><optio`
- [ ] 2. Error: Element option without attribute label must not be empty. From line 509, column 43; to line 509, column 51`selected'></option><optio`
- [ ] 3. Error: The itemprop attribute was specified, but the element is not a property of any item. From line 280, column 4; to line 280, column 59 `ary">↩↩			<h1 itemprop="name" class="give-form-title entry-title">Donate`

## Expected Behavior
Our markup should be valid by default.

## Possible Solution
1. The `<option>` should not be empty, but rather have a placeholder text like "Choose your country" and that option should have `disabled="disabled"`

2. The `<option>` should not be empty, but rather have a placeholder text like "Choose your state/province" and that option should have `disabled="disabled"`

3. The `itemprop` has to be combined with `itemtype` like so:
`<h1 itemprop="name" class="give-form-title entry-title" itemtype="http://schema.org/WebPage">`

**Comment by DevinWalker** [comment]
Closing as we're focusing on refactoring our form HTML/markup
