### ISSUE TITLE
epic: improve search functionality in Give admin

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#1871]
## Issue Overview
Refactor Search API for form, donation, donor, log post type.
Current search has very limited options to search donations, but we should provide more option with simple integration API for search.

## Expected Behavior
A Simple API by which we can add search functionality to diff-diff give CPT

## Current Behavior
Need to add a filter for each option one by one to give any search featured.

## Possible Solution

- We can create a search API which will have following characteristics: Easy integration with all post type in Give core:

                      -- Donations
                      -- Forms
                      -- Donors
                      -- Logs

Any other ( maybe add by add-on )

- Easy customization:

              --Each post type has its own search criteria
- Third party support:
                  --Make it each to modify or edit search API functionality
For Example: If admin installs Form Field Manager add-on on their site then it will add some custom meta to each donation on which admin can expect to search, so it will be good if we provide support to add or remove and feature from search API.

## Related Issues and/or PRs

1. https://github.com/WordImpress/Give/issues/1823
2. https://github.com/WordImpress/Give/issues/621/
3. https://github.com/WordImpress/Give/issues/1783

## MORE INFORMATION
https://docs.google.com/a/wordimpress.com/document/d/1bXYKDgkfNDYVj1yyVlQXVU8wt5bfjWiSccLRnZZJQ4o/edit?usp=sharing

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
Working on the above issues

**Comment by ravinderk** [comment]
Need to break this issue into multiple issues.

**Comment by mikejhale** [comment]
Closing.
