### ISSUE TITLE
Inconsistency between hooks depending on form display mode selection.

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#2006]
## Issue Overview
I discovered this by dealing with Form Field Manager, but I am relatively certain the issue is with Give Core.

If you attach output to the same hook (`give_payment_mode_top` and `give_payment_mode_bottom` both exhibit this), it will display outside the hidden-before-click fields on modal, and inside the hidden-before-click fields on Reveal.

## Expected Behavior
Fields/output on the modal should be hidden before click on a 'reveal' form, and fields/output visible pre-click should be visible pre-click for both modal and reveal. 

## Current Behavior
They are visible for modal before you click, but not visible for reveal before you click.

## Steps to Reproduce (for bugs)

1. Create a new form
2. Select the "Modal" display under display options
3. Add form fields to a form using Form Field manager
3. Select "Above Payment options" as the location for the fields.
4. Save and view the form. The custom fields will be visible before clicking the modal.
5. Edit the form, change the display mode to "reveal"
6. Save and view the form
7. the fields will not be visible before the click.
8. repeat, but also with "below payment options" in step 4.

## Todos
- [ ] Tests

**Comment by Benunc** [comment]
Docs are still waiting on this distinction, for clarity.

**Comment by Benunc** [comment]
docs are still waiting on the answer to this.

**Comment by Benunc** [comment]
docs still waiting on this.

**Comment by DevinWalker** [comment]
@Benunc hold off writing docs for this for now as this is subject to change in 2.1 when we revamp a lot of how the form building process goes.

**Comment by mikejhale** [comment]
Will be address with focus on rebuilding Form UI
