### ISSUE TITLE
Remove duplicate or unnecessary capabilities

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#2105]
## Issue Overview
We have a lot of duplicate capabilities that are named as singular, when they should all instead be plural.

## Expected Behavior
That we only have the minimum custom capabilities required to run the plugin.

## Current Behavior
There are unnecessary, duplicate, and mis-named capabilities.

**DUPLICATES**
![image](https://user-images.githubusercontent.com/930724/30714703-b7637542-9ec8-11e7-89df-1b8d514bea99.png)

The following capabilities should be removed since they are duplicates and they are singular rather than plural:
* [ ] `assign_give_form_terms`
* [ ] `assign_give_payment_terms`
* [ ] `delete_give_form`
* [ ] `delete_give_form_terms`
* [ ] `delete_give_payment`
* [ ] `delete_give_payment_terms`
* [ ] `edit_give_form`
* [ ] `edit_give_form_terms`
* [ ] `edit_give_payment`
* [ ] `edit_give_payment_terms`
* [ ] `manage_give_form_terms`
* [ ] `manage_give_payment_terms`
* [ ] `view_give_form_stats`
* [ ] `view_give_payment_stats`

**UNUSED CAPABILITIES**

There are also some capabilities that are not used in the plugin at all that can be removed. Give does not support "terms" with our give_payments at all, so these are totally unnecessary.

* [ ] `delete_give_payment_terms`
* [ ] `assign_give_payment_terms`
* [ ] `edit_give_payment_terms`
* [ ] `manage_give_payment_terms`

**MISNAMED CAPABILITIES**

Per WordPress Core, all capabilities should be in the plural. Here's some singular capabilities that should instead be plural and are not duplicates:

* [ ] `read_give_form` change to `read_give_forms`
* [ ] `read_give_payment` change to `read_give_payments`

**Comment by mehul0810** [comment]
@mathetos @DevinWalker @ravinderk  I've analysed this issue and checked it in the code. Also, verified with capability manager plugin and it seems that we are using singular capabilities and removed plural capabilities in Give 1.7 at line https://github.com/WordImpress/Give/blob/release/2.0.2/includes/admin/upgrades/upgrade-functions.php#L642

I can see some are unused capabilities which i can remove. Can you please confirm whether the singular capabilities to be removed or the plural one's

Let me know your thoughts.

**Comment by mathetos** [comment]
@mehul0810 Ya, if we already started by removing the plural and sticking with the singular, then we should continue doing that.

**Comment by mikejhale** [comment]
Closing as this will be addressed with #4212

**Comment by mathetos** [comment]
@mikejhale These aren't technically the same issues. Perhaps #4212 can be update to make sure these duplicates get removed at the same time.
