### ISSUE TITLE
Add ability to send donation notes to the donor if needed

### ISSUE THREAD

**Issue by marutim** [impress-org/give#2159]
## Issue Overview
Add the ability to send donation notes to donor when needed. Currently only a donor notes can be added  in the donation dashboard and can not be send to the donor. The feature request can be referred to similar thing for order note in WooCommerce.

## Expected Behavior
Add the ability to send donation notes to donor when needed

## Helpscout link 
https://secure.helpscout.net/conversation/437657707/10543/?folderId=672199

## Screenshots
Screenshot - WooCommerce
![o95um6](https://user-images.githubusercontent.com/3498917/31128979-ecc33b76-a870-11e7-9b73-ecb2d00adbe1.jpg)

Screenshot - Give
![donations wp give wordpress](https://user-images.githubusercontent.com/3498917/31129045-1a684e90-a871-11e7-8c97-f16c3d7c97d4.png)

**Comment by ravinderk** [comment]
@marutim This can be a useful feature.

We can add a checkbox `Send the note to donor` after note textarea which is unchecked by default.

@DevinWalker What do you think?

**Comment by raftaar1191** [comment]
@marutim Nice suggestion 


@ravinderk I also think the same we should have that checkbox

**Comment by marutim** [comment]
Thank you @ravinderk @raftaar1191 

@ravinderk Checkbox sounds good to me, but I would like to add another confirmation before sending the Donation notes, something like, when the admin checks the checkbox a send button appears and only when that send button is clicked this note is send. I just want to make sure the notes doesn't get send by accident. These gets sent only when the admin wants to with his/her confirmation.

Let me know how do you think about this.

**Comment by mathetos** [comment]
Keep in mind the consistency that we're looking for with our Settings UI. I believe this option is a Yes/No, which means there should be two selectors, which would mean an inline radio is best here again.

A checkbox unfortunately depends highly on the wording of the label and can still get easily confused, whereas a "yes" | "no" is not easily confused; particularly when the question is "Send this note to the donor by email?"

**Comment by mehul0810** [comment]
@ravinderk There is a minor fix required in the default donor note email content. There is "may" word appearing twice as per the screenshot below.
![image](https://user-images.githubusercontent.com/1852711/47281995-250e4580-d5fb-11e8-8b92-4127b2e08a5c.png)

You can update the line https://github.com/impress-org/give/blob/f488f7469554ee41549ed0856b793a94dec1e09a/includes/admin/emails/class-donor-note-email.php#L52 for the fix.

Hence, re-opening the issue. Please fix and close the issue.

**Comment by ravinderk** [comment]
This issue has been fixed in: https://github.com/impress-org/give/commit/540f494d545419cf6268fc45d93e79ce33e66939

**Comment by ravinderk** [comment]
This issue has been fixed in: https://github.com/impress-org/give/commit/540f494d545419cf6268fc45d93e79ce33e66939

**Comment by ravinderk** [comment]
This issue has been fixed in: https://github.com/impress-org/give/commit/540f494d545419cf6268fc45d93e79ce33e66939
