### ISSUE TITLE
Add currency support to payment gateway

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#2172]
## Issue Overview

1. Most of the payment gateways have currency limitation which means they can only process certain currencies for donation. To prevent an admin from activating payment gateways for a non--supported currency each gateway add-on would need to have its own dependency management which isn't very effecient. See https://github.com/WordImpress/Give-PayUmoney/blob/3516d88c0fb11a721ef10914b6199c7ff1e537df/includes/admin/actions.php#L12. 

2. In currency switcher addon we added a setting to ask admin which payment gateways support which currency.
<img width="1099" alt="screen shot 2017-10-30 at 9 09 43 am" src="https://user-images.githubusercontent.com/1784821/32153726-42ff1140-bd52-11e7-9dfb-6bb7bdaaff2b.png">

For resolving and improving the code base we can add a class `Give_Payment_Gateways` which will handle registration and dependency logic and more. For example:
```
/**
 * Returns a list of all available gateways.
 *
 * @since 1.0
 * @return array $gateways All the available gateways
 */
function give_get_payment_gateways() {
	// Default, built-in gateways
	$gateways = array(
		'paypal' => array(
			'admin_label'    => __( 'PayPal Standard', 'give' ),
			'checkout_label' => __( 'PayPal', 'give' ),
		),
		'manual' => array(
			'admin_label'    => __( 'Test Donation', 'give' ),
			'checkout_label' => __( 'Test Donation', 'give' )
		),
	);

	return apply_filters( 'give_payment_gateways', $gateways );

}

// For backward compatibility, we can update give_get_payment_gateways fx.
function give_get_payment_gateways() {
	// Default, built-in gateways
	$gateways = array(
		'paypal' => array(
			'admin_label'    => __( 'PayPal Standard', 'give' ),
			'checkout_label' => __( 'PayPal', 'give' ),
                       //  'currencies'        => array()
                      // This param will accept array or string
		),
		'manual' => array(
			'admin_label'    => __( 'Test Donation', 'give' ),
			'checkout_label' => __( 'Test Donation', 'give' )
		),
	);

       foreach( $gateways as $gateway ){
          Give_Payment_Gateways::register( $gateway );
       }
	return Give_Payment_Gateways::get();
}
```

`Give_Payment_Gateways::register` array (to register single payment gateway )

**Comment by DevinWalker** [comment]
@ravinderk can you expand on your thoughts here? How will this work in your mind? What does it look like? How does it integrate with our current gateway add-ons, the future Currency Switcher add-on, etc. Until this gets more required detail I'm bumping off @mehul0810

**Comment by ravinderk** [comment]
@mehul0810 @DevinWalker Issue description updated. Let me know if you have any question.

**Comment by DevinWalker** [comment]
That's a much better description @ravinderk thank you - makes much more sense now. However, this is something I believe we can push until after 2.0 so I'm bumping it.

**Comment by mikejhale** [comment]
Due to the nature of payment gateways adding and removing supported currencies and the fact that many users don't update in a timely fashion we can't be responsible for maintaining a wide list like this.
