### ISSUE TITLE
Importer: Allow multiple Notes to be imported

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#2208]
## Issue Overview
User want to assign several different columns to the donation Notes section.

## Expected Behavior
When they map several different columns, they should each be added as an individual Note in the Donation Details screen.

## Current Behavior
The very last column mapped is added to Notes, all others are ignored or over-written by the last one.

## Steps to Reproduce (for bugs)
1. Do a CSV import
2. Map multiple fields to the "Notes" option
3. After the import is done, go to "Donations > Donations" and click on an imported donation and check the "Notes" section. You should see only one note (the last one mapped) is imported.

**Comment by mikejhale** [comment]
Closed due to lack of customer demand
