### ISSUE TITLE
Importing Donation and Importing Core Setting show have same templete

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#2238]
## Issue Overview
Currently, there are two diff template for the same type of template like `Importing Donation` and When `Importin Core Setting`
1> html-admin-page-import-core-settings.php
2> html-admin-page-import-donations.php
There should be one template that will define the structure of the Importer Page

Classes `Give_Import_Donations` and `Give_Import_Core_Settings` should be inherited from the same class
![image](https://user-images.githubusercontent.com/22215595/32024264-7f06aa10-b9f9-11e7-9d99-6d3e4f975228.png)

## Expected Behavior
One Single Template for importer submenu page

## Current Behavior
There are diff-diff template for each of the importer submenu

## Related Issues and/or PRs
https://github.com/WordImpress/Give/pull/2236

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@raftaar1191 Each import should have there own file but those files have similar code for like steps. We can make it DRY instead of merging file. Let me know if I got it wrong.

**Comment by mikejhale** [comment]
Not focused on this optimization at this point
