### ISSUE TITLE
Improve Responsive UI/UX on all pages in admin

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#2253]
## Issue Overview
While working on https://github.com/WordImpress/Give/issues/2139 noticed that there are lots of issues related to responsiveness which needs to be improved to make it more user friendly in all the devices.

I have pointed out some of the issues in below screenshot. However, needs to be analysed further and implemented in a better way:

![image](https://user-images.githubusercontent.com/1852711/32087360-e6fe6400-baf8-11e7-8d20-4465945fedd7.png)

![image](https://user-images.githubusercontent.com/1852711/32087388-11ac5c20-baf9-11e7-9504-6c2c4eb17d0d.png)

![image](https://user-images.githubusercontent.com/1852711/32087419-3dc5024e-baf9-11e7-821e-b04a655b61ec.png)

## Expected Behavior
Responsive layout throughout plugin

## Current Behavior
Breaking responsive UI/UX in some of the pages in admin.

## Todos
- [ ] Analyse all admin pages for responsiveness
- [ ] Improve Responsive UI/UX
- [ ] Tests

**Comment by DevinWalker** [comment]
Too broad an issue, and none of our customer have complained. Closing
