### ISSUE TITLE
PDF generation breaks when PHP "allow_url_fopen" directive is set to "On"

### ISSUE THREAD

**Issue by pryley** [impress-org/give#2357]
## Issue Overview
This is a rare issue as most servers have the PHP `allow_url_fopen` directive disabled.
However, when the directive is enabled it breaks PDF generation with the following PHP error.

`TCPDF ERROR: [Image] Unable to get the size of the image: https://example.com/wp-content/plugins/give/assets/images/give-logo-small.png`

Previous versions of TCPDF used `curl_init` to fetch the image file if `getimagesize` failed to work:

```php
/**
 * TCPDF v5.9.202
 *
 * @file:line    tcpdf.php:7961
 */
if (function_exists('curl_init')) {
    // try to get remote file data using cURL
    $cs = curl_init(); // curl session
    curl_setopt($cs, CURLOPT_URL, $file);
    curl_setopt($cs, CURLOPT_BINARYTRANSFER, true);
    curl_setopt($cs, CURLOPT_FAILONERROR, true);
    curl_setopt($cs, CURLOPT_RETURNTRANSFER, true);
    if ((ini_get('open_basedir') == '') AND (!ini_get('safe_mode'))) {
        curl_setopt($cs, CURLOPT_FOLLOWLOCATION, true);
    }
    curl_setopt($cs, CURLOPT_CONNECTTIMEOUT, 5);
    curl_setopt($cs, CURLOPT_TIMEOUT, 30);
    curl_setopt($cs, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($cs, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($cs, CURLOPT_USERAGENT, 'TCPDF');
    $imgdata = curl_exec($cs);
    curl_close($cs);
    // ...
}
```

The current version of TCPDF used in give-wp does the same, except it also requires `allow_url_fopen` to be disabled in order to use `curl_init` to fetch the image file if `getimagesize` fails to work:

```php
/**
 * TCPDF v6.2.13
 *
 * @file:line    include/tcpdf_static.php:1924
 */
if (!ini_get('allow_url_fopen')
    && function_exists('curl_init')
    && preg_match('%^(https?|ftp)://%', $path)
) {
    // try to get remote file data using cURL
    $crs = curl_init();
    curl_setopt($crs, CURLOPT_URL, $path);
    curl_setopt($crs, CURLOPT_BINARYTRANSFER, true);
    curl_setopt($crs, CURLOPT_FAILONERROR, true);
    curl_setopt($crs, CURLOPT_RETURNTRANSFER, true);
    if ((ini_get('open_basedir') == '') && (!ini_get('safe_mode'))) {
        curl_setopt($crs, CURLOPT_FOLLOWLOCATION, true);
    }
    curl_setopt($crs, CURLOPT_CONNECTTIMEOUT, 5);
    curl_setopt($crs, CURLOPT_TIMEOUT, 30);
    curl_setopt($crs, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($crs, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($crs, CURLOPT_USERAGENT, 'tc-lib-file');
    $ret = curl_exec($crs);
    curl_close($crs);
    // ...
}
```

As you can see, if `allow_url_fopen` is enabled, cURL will not be used and it will throw an error.

## Possible Solution

TCPDF allows you to pass image data instead of an URL string:

```php
/**
 * TCPDF v6.2.13
 *
 * @file:line    tcpdf.php:6839
 */
if ($file[0] === '@') {
    // image from string
    $imgdata = substr($file, 1);
}
```

You could make your own `ini_get('allow_url_fopen')` check and if it is enabled, run your own cURL function to get the image data, then pass the image data to TCPDF in place of the URL. The image data string must just be prefixed with a `@`.

## Steps to Reproduce
1. Enable PHP directive in your php.ini file: `allow_url_fopen = on`
2. Reload PHP
3. Generate a PDF (Donations → Tools → Export → Export PDF of Donations and Income)

**Comment by DevinWalker** [comment]
We haven't run into any customers complaining of this so I'm going to close this out. If customers are complaining we'll investigate further.
