### ISSUE TITLE
Different minimum donation level for one-off and recurring donations

### ISSUE THREAD

**Issue by Asparagirl** [impress-org/give#2406]
## Issue Overview
One of our donors contacted us and said she'd like to donate $5/month as a recurring donation. We currently enforce a $10 minimum donation, but we meant that as a hard floor for one-off donations. Can Give add a feature to have two different minimum donation levels based on the type of donation, recurring or one-off?

## Expected Behavior
Add the ability to set a minimum donation level for different *types* of donations.

If you really want to make it fancy, you could even add the option to set different minimum donations for different gateways, since some have higher fees than others. ;-)

**Comment by mikejhale** [comment]
Thank you for your request, we've reviewed it and but there are no immediate plans to add it at this time.
