### ISSUE TITLE
Improvement for Tools > System Info

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#2415]
## Issue Overview
**Suggestion:** We can improve the `Get System Report` functionality. 

We can change `Get System Report` to `Copy System Report` and on clicking the button will directly copy the system report to clipboard saving number of additional clicks for end user in the time of emergency.

To achieve the functionality, we can use something like: https://clipboardjs.com/

## Expected Behavior
![image](https://user-images.githubusercontent.com/1852711/33265424-b4f4ab9c-d397-11e7-8be3-2d6ae8ef2372.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/1852711/33265394-88fa2878-d397-11e7-9cf6-9cee2eae2c09.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mikejhale** [comment]
Closing as user is able to copy manually if needed.
