### ISSUE TITLE
feat: improve donor creation method

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#2424]
## Issue Overview
There currently isn't a good way to create new donors besides one obscure one on the donation details page. We should improve our plugin's functionality so that new donors can easily be created from the Donors listing page.

### Step 1:

Remove this strange way to create donors now:

![2017-11-28_01-33-45](https://user-images.githubusercontent.com/1571635/33312405-a1c56be8-d3dc-11e7-8496-9b11e1a6fd0a.png)

### Step 2:

Create "New Donors" page:

![2017-11-28_01-34-28](https://user-images.githubusercontent.com/1571635/33312423-b13ef5e4-d3dc-11e7-8358-8e579f8649bf.png)

**Additional concept coming soon for the "Create Donor" screen.**

**Comment by mikejhale** [comment]
Closed due to lack of customer demand
