### ISSUE TITLE
feat(font-awesome): add Font Awesome 5 SVG support

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#2478]
## Issue Overview

[Font Awesome 5](https://fontawesome.com/) just released with SVG support, which has several benefits compared to icon fonts.

- SVGs render crisply no matter the size or display resolution.
- SVGs are easier to style and align compared to icon fonts.
- SVGs can inherit the size and color of the surrounding text.
- SVGs animate smoothly, and animation is something I'd like to incorporate more of after Give 2.0.
- Font Awesome includes a huge library of well-designed icons so there should always be an appropriate icon for our use cases. Plus there will be a consistent look and feel of all the icons used throughout the plugin.

## Webpack and React Friendly

- There is an [npm package](https://www.npmjs.com/package/@fortawesome/fontawesome) that allows individual icons to be imported as modules.
- There is a [React component](https://www.npmjs.com/package/@fortawesome/react-fontawesome) that can be installed via npm.
- We can choose [only the icons we need](https://www.npmjs.com/package/@fortawesome/react-fontawesome#using-it-with-react) to ensure we're not loading more than necessary.

## Resources

https://fontawesome.com/get-started/svg-with-js
https://www.npmjs.com/package/@fortawesome/fontawesome
https://www.npmjs.com/package/@fortawesome/react-fontawesome

**Comment by kevinwhoffman** [comment]
Moving to Icebox. We'll reconsider when it is time to look at Form API and front-end form design.

**Comment by mikejhale** [comment]
Closing as this will be addressed in the new Forms API using Font Awesome
