### ISSUE TITLE
fix: remove Quick Edit

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#2485]
## Issue Overview
I have noticed we have not provided any setting under quick edit of donation form. So, we should add such settings under Quick Edit for better UX of donation form editing.

For Example, user wants to edit the donation amount of donation form. Then, the Quick Edit option comes to rescue and saves time for a user.

Here is the screenshot of Quick Edit Settings of WooCommerce:
![image](https://user-images.githubusercontent.com/1852711/33763142-53761058-dc35-11e7-9834-d493f5aa14bb.png)

## Possible Options to add under Quick Edit
- Donation Amount
- Donation Type ( Set or Multi-Level )
- Categories or Tags ( if enabled from Give Settings)
- Enable/Disable Goal and Set Goal Amount
- Enable Custom Donation Amount and Set Minimum Amount

Please add other possible options which can be added to Quick Edit.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by kevinwhoffman** [comment]
Quick Edit is not a very obvious feature of WordPress, and I don't think that form editing is done frequently enough to warrant the time necessary to implement quick edit fields. We'll discuss and decide whether to move forward.

**Comment by kevinwhoffman** [comment]
Per discussion with @DevinWalker, he will remove Quick Edit link from below form title.
