### ISSUE TITLE
fix(admin-report): reflect current timezone settings

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#2530]
## Issue Overview
While working on PR #2529, I've noticed an issue which is not obeying the Income Reports timeline when we set Timezone under `Settings > General`. Reports always show the Universal System Time even if we set the time zone from settings.

We can implement this when we revamp Reports UI in https://github.com/WordImpress/Give/issues/1525 

## Expected Behavior
If Time Zone is set from settings then Income Reports should obey it.

## Current Behavior

**TimeZone Settings**
![image](https://user-images.githubusercontent.com/1852711/34026711-e3903b9e-e17d-11e7-9bbe-79df4e5e6e76.png)

**Income Reports**
![image](https://user-images.githubusercontent.com/1852711/34026529-bc9ddb28-e17c-11e7-969b-dbb7535ee8e1.png)

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>

### WordPress Environment ###

Home URL: http://give20.local
Site URL: http://give20.local
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give20.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: N/A
Give Cache: Enabled
Upgraded From: 2.0.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give20.local/donation-confirmation/
Failure Page: http://give20.local/donation-failed/
Donation History Page: http://give20.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by mikejhale** [comment]
Closing this because the new reports devlepment will handle this based on the correct timezone
