### ISSUE TITLE
feat: choose location(s) of offline instructions

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#2543]
## Issue Overview
Currently, the Offline Donations instructions are shown in the form and the confirmation page. Additionally, if the admin doesn't want instructions shown in the form, then they might remove the instructions, but when offline donations instructions are not present, the donor can see an admin alert. 

![image](https://user-images.githubusercontent.com/930724/34174118-b7431322-e4ac-11e7-956c-00e737c6f1a1.png)

Also, there is a use-case where the admin might not want the instructions to be displayed directly in the form at all, but only on the Donation Confirmation page and in the email. We should support the ability to remove the instructions within the form.

So overall, here's the suggestion:

1) Add a setting in the form called "Instruction Location(s)"
2) The options should be a checkbox group, with the following options:
    - Within the form
    - Above the Donation Receipt Table
    - Below the Donation Receipt Table
3) The description should be: "Check the boxes of the locations where you would like the "Donation Instructions" to appear on."

Here's a preview:
![image](https://user-images.githubusercontent.com/930724/34174675-9384703c-e4ae-11e7-9ec1-2e3dfecbdb31.png)

Note that email instructions are treated separately already. This enhancement just gives more flexibility to admins that want to simplify their form presentation while still utilizing Offline Donations.

**Comment by kevinwhoffman** [comment]
@mathetos I agree we should definitely prevent the admin prompt from showing on the front-end form. I'm clear on that.

In my testing, the Donation Confirmation page for an offline donation does not include a receipt table. It only displays the offline instructions. Is there a scenario where a receipt table would appear for an offline donation? Because otherwise we only need 2 options: `Donation Form` and `Donation Confirmation Page`

**Comment by mathetos** [comment]
@kevinwhoffman Things might have changed a lot since I wrote this issue, I believe it was version 1.8.x so perhaps 2.0.x is different now. I trust your judgment.

**Comment by kevinwhoffman** [comment]
Per discussion with @DevinWalker, closing because the user can choose to keep a clean form and still present offline instructions separately in email.
