### ISSUE TITLE
fix(admin-donor): improve handling of empty address fields

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#2611]
## Issue Overview
While checking donor profile, I have noticed that adding an empty address to donor profile and trying to save it does nothing. 

![GIF](http://g.recordit.co/UlFVY6sYC1.gif)

## Expected Behavior
For Better UX, i have added 2 suggestions as mentioned below, 
1. Save Button should be disabled and there must be some of the required fields on filling those fields, the Save button should get enabled.
2. If Save button is clicked without entering any of the address fields then the fields should validate and show an error message.

## Current Behavior
Nothing is happening on clicking on Save when the address fields are empty.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>

### WordPress Environment ###

Home URL: http://give20.test
Site URL: http://give20.test
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give20.test
TLS Connection: 
TLS Connection: 
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instruction✔New Donor Register✔Donor Register✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give20.test/donation-confirmation/
Failure Page: http://give20.test/donation-failed/
Donation History Page: http://give20.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, PayPal Standard
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #54 ( 75L63342RL5674944 ) on 01/03/2018 at 10:44. Status VERIFIED
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Email Reports: ❌ Unlicensed – by WordImpress – 1.0.2
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.3.7
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.2.2
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.5.2
Give - Tributes: ❌ Unlicensed – by WordImpress – 1.3.3

### Inactive Plugins ###

Give - Form Field Manager: by WordImpress – 1.2.4
Give - Gift Aid: by WordImpress – 1.1
Give - PayFast Payment Gateway: by WordImpress – 1.0
Gutenberg: by Gutenberg Team – 1.9.1

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by DevinWalker** [comment]
Closing... I'd rather focus on refactoring the entire page than how this one element works. It may not be the best right now but most people won't attempt to save an empty address like you've outlined as the main issue.
