### ISSUE TITLE
feat: allow multiple donors

### ISSUE THREAD

**Issue by marutim** [impress-org/give#2617]
## Issue Overview
Add an option for the admin to enable which will allow multiple or Group donors. 

## Expected Behavior
Admin should have an option enabling which will let the user add multiple donors while donating. 

## Current Behavior
One can add only one donor per donation.

## Possible Solution
We can have something similar Multiple recipients for our Tributes add on.

## Related Helpscout link
https://secure.helpscout.net/conversation/493903544/12758/

**Quote from Customer's Help Scout Ticket:**

> While multiple recipients for eCards is a nice feature, it doesn't resolve my issue, which isn't multiple recipients, but multiple DONORS for a donation that includes a tribute. There may not have been many requests for this, but the issue is actually quite common: when a couple, or multiple family members, or some other group, send a donation together in honor or in memory of someone. Yes, it's true that I've added second donor fields using FFM, but that's only because there isn't another option in the Plugin for adding an additional donor to the same donation.

> So, here's my specific request. It's in two parts:

> Part 1: Add to the MAIN PLUGIN an additional field (or even better, the ability to add multiple additional fields) for (an) optional additional donor(s). The reason for putting this in the main plugin and not in the Tributes add-on is because it's important that the people managing donations have the ability to list all of the individuals who have contributed to any donation, regardless of whether or not a tribute is involved. (Our donors are using our FFM fields for this pretty frequently. If you're able to do what I'm requesting, that would replace those FFM fields.)

> Part 2: Add coding to the TRIBUTES add-on which would check for (an) additional donor(s) in the main plugin, and automatically add the additional donor(s) to mailed cards and eCards sent to the recipient of the tribute.

**Comment by malayladu** [comment]
@marutim It's a good suggestion.

I was having similar question. I am using GIve on http://srkps.in and last year I came across this scenario where I had to make a donation on behalf of my friends.

At that time I had to make a donation separately for each of them.

It would be great if we can add multiple donor in a same transaction.

**Comment by kevinwhoffman** [comment]
Iceboxing until Form API makes custom fields available anywhere in the form. Then a repeater could handle multiple donors and store them as donation meta. Until then, the existing FFM repeater field could handle something similar with limited positioning options.

**Comment by mikejhale** [comment]
Closing as this is not typical behavior in the online giving experience.
