### ISSUE TITLE
doc(wiki): add guidelines for Git communication

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#2642]
## Issue Overview

As we look to modernize the Give pipeline, I’d also like to propose some guidelines for Git commit messages that will help create more consistent and informative Git logs. If the team agrees, we could move these guidelines to [`CONTRIBUTING.md`](https://github.com/WordImpress/Give/blob/master/CONTRIBUTING.md).

## The seven rules of a great Git commit message

The [inspiration](https://chris.beams.io/posts/git-commit/) for these guidelines can be summarized in the following 7 points:

```
1. Separate subject from body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line
4. Do not end the subject line with a period
5. Use the imperative mood in the subject line
6. Wrap the body at 72 characters
7. Use the body to explain what and why vs. how
```

## Emphasize _Why_ instead of _How_

> In most cases, you can leave out details about how a change has been made. Code is generally self-explanatory in this regard (and if the code is so complex that it needs to be explained in prose, that’s what source comments are for). Just focus on making clear the reasons why you made the change in the first place—the way things worked before the change (and what was wrong with that), the way they work now, and why you decided to solve it the way you did.

## Example

You can see an example of consistent formatting in the [WPBR commit history](https://github.com/WordImpress/WP-Business-Reviews/commits/develop).

I've been following these guidelines for a few years. While I need to do a much better job of explaining the _why_, I find the formatting alone makes for better Git logs that are easier to scan over time.

## Considerations

Consistently formatting commit messages is an easy win. The more challenging task with these type of guidelines is balancing clarity with efficiency. After a few weeks I think it will become second nature as it did for me. Interested to hear your thoughts.

**Comment by ravinderk** [comment]
@DevinWalker We can use default git message template to improve commit message.
For Ref: https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template


Most of editor use git message template.

Source Tree
![screen shot 2018-01-10 at 11 40 58 am](https://user-images.githubusercontent.com/1784821/34758194-080feb12-f5fc-11e7-9fcb-778f4d326d0c.png)

Atom
<img width="856" alt="screen shot 2018-01-10 at 11 45 32 am" src="https://user-images.githubusercontent.com/1784821/34758195-084da222-f5fc-11e7-8ba7-c2284903b3ab.png">

**Comment by malayladu** [comment]
I agree with @kevinwhoffman on emphasize **Why** instead of **How**.

People can easily see **How** it's done but it's hard to understand **Why** it's done.

@ravinderk suggested a good point too. Using commit message template to describe Why & How would be a great deal like we follow issue template while creating a new issue on repository.

**Comment by kevinwhoffman** [comment]
Team, I have widened the scope of this issue to cover issues, commit messages, and pull requests. We generally perform these tasks in a sequential order, first creating an issue, then committing changes, and finally create a pull request. By following the guidelines below, we will provide clear and consistent communication from start to finish.

## Issue Guidelines

1. Capitalize the issue title.
2. Do not end the issue title with a period.
3. Use the imperative mood in the issue title.
4. Limit the issue title to 50 characters.
5. Write a goal-oriented issue title.
6. Do not combine unrelated goals into one issue.
7. Follow the issue template but remove any sections that do not apply.

**Example:** A properly formed Git issue title should always be able to complete the following sentence:

- The goal of this issue is to... *{your subject line here}*
- The goal of this issue is to... *Prevent white screen after submitting donation*

## Commit Message Guidelines

1. Capitalize the subject line.
2. Do not end the subject line with a period.
3. Use the imperative mood in the issue title.
4. Limit the subject line to 50 characters.
5. Separate subject from body with a blank line.
6. Wrap the body at 72 characters.
7. Use the body to explain what and why vs. how.

**Example:** A properly formed Git commit subject line should always be able to complete the following sentence:

- If applied, this commit will... *{your subject line here}*
- If applied, this commit will... *Refactor subsystem X for readability*

## Pull Request Guidelines

1. Format the pull request title as `Issue/{Issue Number} - {Issue Title}`.
2. Follow the pull request template but remove any sections that do not apply.

A properly formed Git pull request title should always include the issue number and title. Since the issue title should already be written in the goal-oriented imperative mood, then it ought to make be perfectly reusable as the pull request title. Using the issue number and title in the pull request creates a clear connection to the original issue while removing the need to think of a clever title. It's already done for you!

**Example:** Given an issue number `123` and issue title `Improve vertical rhythm of blog posts`, the relavant pull request should be named:

`Issue/123 - Improve vertical rhythm of blog posts`

**Comment by kevinwhoffman** [comment]
# Git Communication Guidelines

The purpose of these guidelines is to standardize Git communication throughout a team of developers with the following benefits:

- Better indication of the type and scope of changes affecting a project over time.
- Improved clarity of the relationship between issues, commits, and pull requests.
- Faster comprehension of changes without having to dig into the code.
- Reduced difficulty of naming things through formal guidelines.
- More granular version control in the event that changes need reverted.
- Faster onboarding of new team members through well-documented guidelines and procedures.
- Less friction for community contributors wondering how to communicate changes.
- Automated changelogs pre-organized by type.

## General Guidelines

The following formatting guidelines apply to all issues, commit messages, and pull requests.

### DO

- Always include `{type}({scope}):` prefixes. See the *Prefix Guidelines* below for more information.
- Format `scope` in kebab-case if it requires more than one word (lowercase words separated by a `-`).
- Use the [imperative mood](https://chris.beams.io/posts/git-commit/#imperative).
- Wrap any code, such as `Class_Name`, `method()`, `$property`, `$variable`, or `@tag`, in backticks.

### DO NOT

- Do not capitalize the `type` or `scope` within the prefix or the first word after the prefix.
- Do not end titles or subject lines with a period.
- Do not exceed 72 characters in your titles, subject lines, or body text.

## Prefix Guidelines

**`{type}({scope}):`**

Consistent prefixes that reference the `type` and `scope` of change improve communication in the following contexts:

- Issues - Prefixing issues immediately signals the type of change being proposed and which part of the project it affects.
- Commits - Prefixing commits logically groups together changes and makes the commit history easier to scan and understand especially during code reviews and debugging.
- Pull Requests - Prefixing pull requests again signals the type of change being merged and which part of the project it affects.

The idea is that when a developer encounters a prefix such as `build(webpack)` or `doc(donors-query)`, they will know exactly what type of change to expect without having to dig into the details.

### Type Prefixes

The `type` of change within the prefix is always required. `type` refers to the nature of the change associated with an issue, commit, or pull request. For consistency, the available types to choose from are limited to the following:

- `build` - A change that affects the build system or external dependencies (e.g. webpack, npm)
- `doc` - A documentation change
- `feat` - A new feature
- `fix` - A bug fix
- `font` - A font file that is added or removed
- `format` - A change that does not affect the meaning of code (e.g. white-space)
- `image` - An image file that is added or removed (e.g. JPG,GIF,PNG,SVG)
- `perf` - A code change that improves performance
- `refactor` - A code change that neither fixes a bug nor adds a feature
- `style` - A CSS style change
- `test` - A missing test or correction to an existing test

### Scope Prefixes

The `scope` of change within the prefix is optional but highly encouraged. `scope` can be anything specifying the location of the change. See *Tips for Determining Scope* in the *Appendix* of this document.

## Issue Guidelines

**{type}({scope}): {subject line}**

1. Write goal-oriented issue titles. Think about the problem that needs solved and turn it into a goal.
2. Limit each issue to a single goal. Create new issues for related goals and tag the related issue.
3. When multiple related issues comprise a single feature or release, consider relating them through an epic.
4. Follow the issue template within reason. Before submitting, remove all HTML comments and any headings that do not apply. This will result in cleaner presentation of issue when it is consumed via an API by third-party apps like Slack.

### Issue Examples

- build(webpack): add sourcemap support
- doc: add missing JS docs throughout the plugin

### Epic Examples

- feat(reports): revamp report screens
- release(2.1.0)

*Note: A release epic is the only case where a `subject line` may be omitted.*

## Commit Message Guidelines

```
{type}({scope}): {subject line}
{BLANK LINE}
{body}
{BLANK LINE}
{footer}
```

1. Separate subject line from body with a blank line.
2. Use the body to explain the motivation for the change and how you resolved it. An easy template is to use the first paragraph to explain the problem and the second paragraph to explain how you resolve it.
3. Optionally add a footer if the issue is meant to close an issue (e.g. `Closes #123`) or use it to document breaking changes.

### Commit Message Subject Line Examples

- build(webpack): add sourcemap support
- doc(my-class): add missing `@param` to `render()`
- fix(request): return `WP_Error` if request fails
- style(blank-slate): increase padding around logo

## Pull Request Guidelines

Format: **{issue title} #{issue number}**

1. Follow the pull request template within reason. Before submitting, remove all HTML comments and any headings that do not apply.
2. Add `Closes #{issue number}` if the pull request should close the issue upon merging.

*Tip: When you view an individual GitHub issue, it displays the issue title with the issue number trailing at the top of the page, so you can just copy and paste it as the pull request title.*

### Pull Request Examples

Given an issue number `123` and issue title `style(receipt): improve vertical rhythm`, the relevant pull request should be named:

`style(receipt): improve vertical rhythm #123`

## Appendix

### Tips for Determining Scope

1. To determine `scope` of PHP changes, slugify the name of the subpackage to which your change applies.
    - If the package is `Give/Emails`, then the scope is `emails`.
    - If the packge is `Plugin/Some_Package`, then the scope is `some-package`.
2. Sometimes a subpackage is not relevant, such as when applying CSS or JS changes. In these cases, define the `scope` as the slugified CSS component or JS module. Omit any project prefixes such as `give`.
    - If the CSS component is `give-blank-slate`, then the scope is `blank-slate`.
    - If the JS module contains a class named `GiveDonor`, then the scope is `donor`.
3. When none of the above are relevant, use the slugified filename as the `scope`.
    - If changing a file such as `admin-widgets.js` (which is just a collection of functions), then the scope is `admin-widgets`.
4. Finally, if the changes in question don't fit neatly into a single scope, don't stress about it. Just leave the scope out of the prefix.

Remember our goal is to group similar commits together and make them easier to scan in a commit log, on GitHub, or within Slack. So the actual name of the `scope` isn't as important as the consistency with which we use it over time.

### Articles

- https://chris.beams.io/posts/git-commit/
- http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
- https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines
- http://who-t.blogspot.co.at/2009/12/on-commit-messages.html
- https://github.com/erlang/otp/wiki/writing-good-commit-messages

### Projects

- [WordPress](https://make.wordpress.org/core/handbook/best-practices/commit-messages/)
- [Git](https://github.com/git/git/blob/master/Documentation/SubmittingPatches)
- [Linux](https://github.com/torvalds/subsurface-for-dirk/blob/master/README#L92-L120)
- [Angular](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit)

*Note: React has no formal Git communication guidelines, which is evident by its commit history.*

**Comment by kevinwhoffman** [comment]
Per discussion with @DevinWalker and @ravinderk, I'll be moving these guidelines into the [Give Wiki](https://github.com/WordImpress/Give/wiki). Once the Wiki is built out, it can be linked to from the `README.md` and/or `CONTRIBUTING.md`.

**Comment by kevinwhoffman** [comment]
Closing as the Development Handbook in the Wiki covers all of the above topics.
