### ISSUE TITLE
feat(admin-donation): add Quick View to Donations screen

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#2643]
## Issue Overview
We should Add a Quick **View option** in Give Donation Page Where admin can click on it a popup will get open and admin can see the Donation Details in Popup with Donation Details init

![image](https://user-images.githubusercontent.com/22215595/34760669-caaed606-f606-11e7-8ab0-813658be5205.png)

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/2644

**Comment by DevinWalker** [comment]
The quick view is not necessary in my opinion because of the columns already present within the view. Closing as not going to include.
