### ISSUE TITLE
feat(admin-donor): add Quick View to Donors screen

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#2644]
## Issue Overview
We should Add a Quick **View option** in Give Donors Page Where admin can click on it a popup will get open and admin can see the Donor Details in Popup with Donation and Donor details init

![image](https://user-images.githubusercontent.com/22215595/34760853-63086250-f607-11e7-9fa8-3032d01473d4.png)

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/2643

**Comment by DevinWalker** [comment]
I don't think this would be a helpful addition.
