### ISSUE TITLE
feat(donation): display the formatted amount of a donation

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#2646]
## Issue Overview
Unless I'm missing something we don't really have a great way to output a donation payment's pretty total amount. By pretty I mean:

1. Displays proper decimals
2. Proper separators for thousands and decimals
3. Displays proper currency code
4. Appropriate spacing 

There should be an easier way to get a formatted payment amount than:

```
$donation_amount = give_currency_filter( give_format_amount( give_get_meta( $payment_id, '_give_fee_donation_amount', true ) ), array( 'currency_code' => $payment->currency ) );
```

## Expected Behavior
- There is an easy way for developers to output a payment's formatted amount.

## Current Behavior
- You have a long nested list of functions

## Possible Solution
There should be a method within Give_Payment that allows us to output the "pretty" total. There should also be a helper function that we can use to simply pass the payment `ID` or `object` and it will return the pretty formatted using the newly created method:

```
function give_get_payment_formatted_amount( $payment ) {
// Check if $payment is ID or object
// If ID turn into new object
// Return value using newly created method.
}
```

**Comment by ravinderk** [comment]
@DevinWalker We already updated `give_donation_amount` for that.

For ref: https://github.com/WordImpress/Give/blob/6fd04074fa1db7d764874c729e94c2800fa7a398/includes/payments/functions.php#L1198

Let me know if you still need any improvement.

**Comment by DevinWalker** [comment]
That works. We should write an article on developers.givewp.com describing how to appropriately output amounts from payments so it's clearly defined.

**Comment by kevinwhoffman** [comment]
@DevinWalker looks like the functionality is there but we're waiting on a post for the developers blog. If that's the case, please close this out and create a separate documentation issue. Thanks.

**Comment by mikejhale** [comment]
Closing due to functionality being in Give Core, but still lacking blog post on it.
