### ISSUE TITLE
perf(admin-setting): improve query performance

### ISSUE THREAD

**Issue by mqudsi** [impress-org/give#2699]
WP-Give has a _really_ bad query plan for the admin backend that includes a separate query per row of results (instead of a join) and duplicate queries without caching.

There is no quick fix for this, it needs to be completely architectured to first obtain all relevant information via a few SQL queries that *aren't* along the lines of

```php
foreach ($donations as $donation) {
//SQL query here, WHERE id = $donation->id
}
```

and aren't
```php
foreach ($posts as $post) {
//SELECT * FROM posts WHERE id = $post->id
}
```

Simply loading `/wp-admin/edit.php?post_type=give_forms&page=give-payment-history` executes **259 queries**, many of which _are the same query with the same parameters_. 

![image](https://user-images.githubusercontent.com/606923/35295899-1a9b6ee8-0040-11e8-8409-ecb68850cfd7.png)

Just going to `/wp-admin/edit.php?post_type=give_forums&page=give-settings` results in duplicate queries selecting *all* columns from `wp_posts` for *all* posts with virtually no limit (`LIMIT 0, 999`) repeated 50 times:

![image](https://user-images.githubusercontent.com/606923/35296040-7423a688-0040-11e8-805b-61d9c9367c93.png)

Also, by default WP-Give installs a dashboard plugin that is active simply visiting `/wp-admin/` and causes these same queries to be executed. I had to comment out that code to make the dashboard usable.

**Comment by DevinWalker** [comment]
Hey @mqudsi - We've been working hard to improve our queries - see #1932 #1944 #2121 

I agree there are some queries, like that long monstrosity you're showing within Recurring, need resolving. However, the one you mention about the dashboard widget should now be resolved, I believe. 

What version of Give were you using when you were looking into this?

**Comment by mqudsi** [comment]
This hasn't been fixed as of 2.0.6.

Here's what simply logging in to `/wp-admin/` looks like:

![image](https://user-images.githubusercontent.com/606923/39389477-8d3ef804-4a4e-11e8-9995-f3b14820d868.png)

I'm sorry, but that is _insane_. 

`update_meta_cache()` ran this query 344 times:

```sql
SELECT payment_id, meta_key, meta_value
FROM wp_give_paymentmeta
WHERE payment_id IN (13783)
ORDER BY meta_id ASC
```

and this query **614** times:
```sql
SELECT meta_id
FROM wp_give_paymentmeta
WHERE meta_key = '_thumbnail_id'
AND payment_id = 13783
```

as a result of 345 calls to `update_meta_cache()`.

**Comment by mqudsi** [comment]
Additionally, `get_option` for `give_completed_upgrades` is called 3 times

1:

```php
do_action('admin_init')
wp-includes/plugin.php:453
Give_Updates->__change_donations_label()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:212
Give_Updates->get_total_update_count()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:1016
Give_Updates->get_pending_db_update_count()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:1031
Give_Updates->get_updates()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:979
give_get_completed_upgrades()
wp-content/plugins/give/includes/misc-functions.php:1252
get_option()
wp-includes/option.php:98
```

2:

```php
do_action('admin_menu')
wp-includes/plugin.php:453
Give_Updates->__register_menu()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:252
Give_Updates->get_total_update_count()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:1016
Give_Updates->get_pending_db_update_count()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:1031
Give_Updates->get_updates()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:979
give_get_completed_upgrades()
wp-content/plugins/give/includes/misc-functions.php:1252
get_option()
wp-includes/option.php:98
```

```
do_action('admin_notices')
wp-includes/plugin.php:453
Give_Updates->__show_notice()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:652
Give_Updates->get_total_new_db_update_count()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:1059
Give_Updates->get_pending_db_update_count()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:1031
Give_Updates->get_updates()
wp-content/plugins/give/includes/admin/upgrades/class-give-updates.php:979
give_get_completed_upgrades()
wp-content/plugins/give/includes/misc-functions.php:1252
get_option()
wp-includes/option.php:98
```

**Comment by DevinWalker** [comment]
Hey @mqudsi - I agree, loading the dashboard right now with many donations is very slow. That's why in 2.1 we've optimized this substantially. It's going to be released this upcoming week so please re-review your queries load time and number of queries post update. 

@ravinderk is also looking into your additional optimization feedback and reducing the number of queries to only the number of objects is our big priority right now. We appreciate your additional feedback and code references.

**Comment by mqudsi** [comment]
@ravinderk @DevinWalker it's not an issue with the number of donations (which isn't *that* high). I didn't mean "a query *like* this is being run a million times" but rather "this *exact* query is being run a million times," as in, there's a bug and the same query is being run to update the metadata for the same donation.

**Comment by ravinderk** [comment]
@DevinWalker Closing this issue because last year we worked on admin loading performance and it is fine now. I will create a seperate issue for recurring admin loading performance.
