### ISSUE TITLE
fix(admin-donor): display correct donor details of changed donor

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#2704]
## Issue Overview

![81ecghvva7](https://user-images.githubusercontent.com/1784821/35339551-e55c02b2-0146-11e8-824d-1d8a7e04a1ed.gif)

## Expected Behavior

Donor info inside donor detail meta box must update after choosing a new donor.

## Current Behavior

I am not seeing any immediate effect in donor information after changing donor.

## Possible Solution

Use JS to update donor infomation in donor detail meta box

**Comment by DevinWalker** [comment]
Closing - clicking on "Update" for now suffices until we can use React to update without jQuery.
