### ISSUE TITLE
Provide users with options on settings export.

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#2716]
## Issue Overview
The Give settings export is a powerful tool, but if I am an agency creating 25 Give sites for clients, and I want to speed up my workflow by importing settings, the current exporter exports _everything_ which makes for a difficult (and potentially security breaching) process.

different clients will have different Stripe accounts, for example. 

## Expected Behavior
I should be able to export the following (for example)
- pdf receipt layouts
- currency settings
- country settings
- etc

...Without exporting the following
- payment gateway API keys
- paypal standard email
- etc

## Current Behavior
Currently, the give settings export exports _everything_

## Possible Solution
checkboxes to unselect the settings that you want to not export.

## Steps to Reproduce (for bugs)
1. Export give settings on a site with a payment gateway set up.
2. the resulting JSON has gateway API keys in it.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by Benunc** [comment]
Further thoughts:

I think that the default behavior would to avoid exporting anything related to a payment gateway or third party service like Mailchimp, etc. 

Make users explicitly check that they want to export that portion of the settings.

**Comment by ravinderk** [comment]
Close this pr in favor of #2829 https://github.com/WordImpress/Give/compare/c6cbbc3155ba...7110dda04d29
