### ISSUE TITLE
feat(admin-setting): use Chosen dropdown for page settings

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#2717]
Task detail:
1. Convert field to chosen
2. Add ajax feature ( https://github.com/WordImpress/Give/issues/2445#issuecomment-349150804 )

**Comment by DevinWalker** [comment]
This has been resolved:

![2018-10-09_23-01-59.png](https://images.zenhubusercontent.com/573e05b6bf93871ccd9b4d55/890ad7d8-3979-4fe8-a499-a0e0c6bac78d)
