### ISSUE TITLE
dep(gateway): deprecate unused `$saved_value` parameter

### ISSUE THREAD

**Issue by tw2113** [impress-org/give#2720]
```
function give_default_gateway_callback( $field_arr, $saved_value ) {
	$id          = $field_arr['id'];
	$gateways    = give_get_enabled_payment_gateways();
	$saved_value = give_get_default_gateway( null );
       
        ...
}
```

$parameter `$saved_value` is not used at all, instead the variable gets overwritten right away.

Also the @param value should probably be "mixed", if not removed/deprecated completely, as string/bool is passed in two different spots.

**Comment by DevinWalker** [comment]
Closing in favor of #3003 which is a larger removal of legacy code.
