### ISSUE TITLE
test: ensure parameter types accurately reflect arguments

### ISSUE THREAD

**Issue by tw2113** [impress-org/give#2721]
```
$payment_id = give_check_variable( give_clean( $_GET ), 'isset_empty', 0, 'preview_id' );
```

and 

```
give_check_variable( give_clean( $_GET ), 'isset_empty', 0, 'user_id' );
```

Scrutinizer is interpreting the 3rd parameters as integers and the function expects boolean. Recommending changing the two 0's to boolean `false`

**Comment by tw2113** [comment]
May be invalid as the intended defaults may be meant to be integer.

**Comment by ravinderk** [comment]
@tw2113  Third parameter contains `default value` and can be `mixed` type. So it is good to assign any type of default value to param which we want to validate.

Let me know if you want more information on that.

Closing this issue for now.
