### ISSUE TITLE
feat(admin-tool): log email notifications

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#2738]
## Issue Overview

Add log section to track email notifications.

## Expected Behavior

Need a place where admin can check quickly which email send to whom and when.

## Current Behavior

No way to email notifications.

**Comment by mathetos** [comment]
I think it's an excellent idea, but I think it should be a free Add-on. When I think of our core purposes, logging emails isn't it. There are several good plugins that do it, but having our own Addon would allow us to show JUST Give emails in one central location that is seamless with our UI.

I think the following features would be really important:

1) Setting to automatically delete emails older that a defined date or a defined number of emails
2) Preview the emails in a browser tab
3) Bulk delete the log
4) Optionally, automatically clear the whole log every last day of the month or something to that effect.

**Comment by ravinderk** [comment]
@mathetos For point 4, I created separate issue: https://github.com/WordImpress/Give/issues/2739

**Comment by DevinWalker** [comment]
Closing as this isn't our job but services like SendGrid, SES, and plugins that can monitor and log WP's emails.
