### ISSUE TITLE
build(eslint): automate JavaScript linting prior to commit

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#2792]
## Issue Overview

I reviewed many pull request for `Give` and found that most of the developers forget to fix code formatting issue in javascript.

To resolve this issue we can sniff files change on commit. To achieve that we can create `hooks` folder inside `.github` ( move existing template to `template` folder ) and write step to set developer environment for `Give`.

Ref:
https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/
https://gist.github.com/wesbos/8aec9d2ff7f7cf9dd65ca2c20d5dfc23

**Note:** This process at least reduces one cycle of review and save time too 💯

**Comment by Sidsector9** [comment]
@ravinderk IMO shell scripts should live in a separate directory in the root, as demonstrated [here](https://github.com/Sidsector9/Give-dummy) 

Also, we need to inform the developers that they need to update Git to 2.9+

**Comment by ravinderk** [comment]
```
Call Member: me and @DevinWalker 
Call Summary: We can handle it after 2.1 because there will be lot of javascript refactorization will happen in 2.1
```

**Comment by raftaar1191** [comment]
Slack discussion link: https://givewp.slack.com/archives/C0FAGC83C/p1518152232000027

**Comment by mikejhale** [comment]
Will be addressed in a new optimized build process
