### ISSUE TITLE
test: warn developer if text domain is misspelled

### ISSUE THREAD

**Issue by Sidsector9** [impress-org/give#2797]
## Issue Overview
Developers can unintentionally misspell the text-domain `give`

## Expected Behavior
Check if text-domain is spelled correctly while using i18n functions.

## Current Behavior
No check for text-domain

## Possible Solution
Add the below lines to the `phpcs.ruleset.xml` file
```xml
<rule ref="WordPress.WP.I18n">
	<properties>
		<property name="text_domain" type="array" value="give" />
	</properties>
</rule>
```

## Acceptance Crieteria

- [ ] There developer is warned when any text domain is used that does not match `give`.

**Comment by kevinwhoffman** [comment]
@nishitlangaliya Please implement this rule for PHPCS in Give core. It should warn the developer when any text domain is used that does not match `give`.

Post a short video demonstrating the rule when you are done.

**Comment by nishitlangaliya** [comment]
@kevinwhoffman , I have implemented the rule and posted my testing video in PR please check for the same and let me know if any query.

Thanks.
