### ISSUE TITLE
refactor: improve storage and handling of notes

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#2825]
## Issue Overview

`notes` autoload whenever we will create `Give_Donor` object. There two things which I found:
1. `notes` is not need all time, so not worth to load each time.
2. we are appending each note to `notes` list which is not a good way to preserve notes.

## Expected Behavior

A better way to handle `notes`.

## Current Behavior

`notes` loads in `Give_Donor` object even if we are not using.

**Comment by kevinwhoffman** [comment]
@ravinderk Is this still an issue after the move to custom comment tables in Give 2.3.0? If not, please close.

**Comment by ravinderk** [comment]
@kevinwhoffmanI am closing this issue since we move notes to custom comment table. I will open other issues for performance improvemtn.
