### ISSUE TITLE
fix(compat): create a test environment for Microsoft server-related issues

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#2832]
## Issue Overview
Increasingly in support, we get tickets with Microsoft servers, where issues are difficult to replicate in a Linux/Docker local environment. 

This issue has two goals: 
1. Establish a set of best practices for the support team and Dev team to work together to resolve windows server issues.
2. Establish a shared environment or set of environments where Windows server setups can be replicated.

## Expected Behavior
If a customer submits a ticket with Microsoft IIS 7.5 and PHP 5.4 we need a way to replicate that server environment in the same way I can replicate LAMP environments. 

## Current Behavior
I was able to spin up one Microsoft Azure site, but it's (a) running IIS 10 and I don't see a way to switch that and (b) possibly costing me money to run. (I had to submit a card number to get signed up)

To exacerbate the need, I currently have one ticket where PDF receipts is not working at all on the customer's site and another with an Ajax error that I can't replicate elsewhere

## Related
- https://secure.helpscout.net/conversation/590682811/19296?folderId=848135
- https://secure.helpscout.net/conversation/524868261/14400/?folderId=672199

**Comment by DevinWalker** [comment]
This issue was incorrectly marked as closed in the PR above. I've reopened to reflect that.

**Comment by Benunc** [comment]
Would love to give the customer currently stuck on a PDF receipts issue that is Windows-related an idea about how we are attempting to resolve this.

**Comment by raftaar1191** [comment]
[Vagrant](https://www.vagrantup.com/) can be used get the desire working environment and then try to regenerate this issues


I have some idea in how to setup the Vagrant. 

Should I create some doc on how to setup the Vagrant and get the desire Working Environment

**Comment by kevinwhoffman** [comment]
After discussing with @DevinWalker, we are not going to pursue a local environment setup for Windows servers. For most of us on Mac, this would require virtual machines (maybe several of them) to match the possible versions of IIS in use by customers. It would also require a separate debugging workflow within the Windows environment. If these Windows issues do become more common, we may look into a hosting plan that allows us to fire up a Windows server and do some quick testing.

**Comment by DevinWalker** [comment]
Just to add to this... I researched hosting options and Microsoft Azure seems like the best option however the inability to adjust the IIS version is a big limitation. I did not find a suitable alternative. Perhaps there is a MS Plesk environment available that's out there that I'm missing but I didn't find Media Temple supporting that o
