### ISSUE TITLE
fix(form): allow mouse-free navigation in Safari with billing addresses

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#2877]
## Issue Overview
In order to navigate through the form without a mouse, if billing addresses are enabled for a gateway, tabbing from ZIP code to the next field should take you to the donate button. It doesnt, currently.

## Expected Behavior
Tabbing from billing address fields to the next field should not skip a field. 

## Current Behavior
The Donate button is skipped, only in Safari.

## Steps to Reproduce (for bugs)
1. Enable PayPal Standard and the "Collect Billing Information" fields.
2. Fill out the form without using a mouse, in the safari browser.
3. After filling out the ZIP field, press "TAB" 
4. The donate field should be highlighted, but it's not. The next field on the page is (or the first field in the event that the donation field is last on the page).

I tried on multiple styles of form (multilevel, set, display fields, modal, etc), and it didn't seem to matter. I also tried with and without an Email Marketing add-on active (which puts checkboxes in between the ZIP and the Donate button.) That did not seem to matter, either.

## WordPress Environment
<details>
### WordPress Environment ###

Home URL: http://localgive.local
Site URL: http://localgive.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: localgive.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.20
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.6
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: 2.0.4
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://localgive.local/donation-confirmation/
Failure Page: http://localgive.local/donation-failed/
Donation History Page: http://localgive.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.3.3
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.2.7
Give - MailChimp: ❌ Unlicensed – by WordImpress – 1.4
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 1.5.2

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.2
Ben's Helper Functions: by BenUNC –
Better Search Replace: by Delicious Brains – 1.3.2
Debug Bar: by wordpressdotorg – 0.9
Debug Bar Post Meta: by whyisjake – 0.5.4
Duplicate Post: by Enrico Battocchi – 3.2.1
Elegant Themes Support: by Elegant Themes – 1.3
Give - 2Checkout Gateway: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Currency Switcher: by WordImpress – 1.0.1
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.1.1
Give - Fee Recovery: by WordImpress – 1.4
Give - Form Countdown: by WordImpress – 1.0
Give - Gift Aid: by WordImpress – 1.1
Give - GoCardless Gateway: by WordImpress – 1.1.2
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.2
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - iATS Payment Solutions: by WordImpress – 1.0.2
Give - Manual Donations: by WordImpress – 1.3.2
Give - Old Meta Switcher: by WordImpress – 1.0
Give - Paymill Gateway: by WordImpress – 1.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.4
Give - PayUmoney: by WordImpress – 1.0.1
Give - PDF Receipts: by WordImpress – 2.2.4
Give - Per Form Gateways: by WordImpress – 1.0.1
Give - Razorpay: by WordImpress – 1.1.3
Give - Recurring Donations: by WordImpress – 1.5.7
Give - Recurring Helper: by WordImpress – 1.0
Give - Tributes: by WordImpress – 1.4.1
Give - Update Goal Progress: by Matt Cromwell – 1.0
Give - WePay Gateway: by WordImpress – 1.3.1
Give - WP All Import Addon: by Ben Meredith – 1.0
Give - Zapier: by WordImpress – 1.1.2
Give Stripe Cleanup.: by BenUNC –
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.2.5
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.8
Hello Dolly: by Matt Mullenweg – 1.6
MailChimp for WordPress: by ibericode – 4.2
MailChimp User Sync: by ibericode – 1.7
Query Monitor: by John Blackbourn – 2.17.0
Shortcode in Menus: by Gagan Deep Singh – 3.4
Transients Manager: by Pippin Williamson – 1.7.4
User Switching: by John Blackbourn – 1.3.0
WPBakery Page Builder: by Michael M - WPBakery.com – 5.3
WP Crontrol: by John Blackbourn & contributors – 1.6.2
WP Simple Pay (Lite Version): by WP Simple Pay – 2.0.8
Yoast SEO: by Team Yoast – 6.2

### Active MU Plugins ###

hide-give-license-warning.php: by  –
Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

## Hardware/ Software Versions
<details>
MacBook Pro (Retina, 13-inch, Early 2015)

2.7 GHz Intel Core i5

Safari Version 11.0.3 (11604.5.6.1.1)

</details>

**Comment by DevinWalker** [comment]
Seems to be working fine for me in `Version 12.0 (14606.1.36.1.9)`:

![2019-01-09_20-45-22](https://user-images.githubusercontent.com/1571635/50946743-a681b100-144f-11e9-906f-693354b98de5.gif)

Closing unless replicable.
