### ISSUE TITLE
feat: support custom icons for add-ons

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#2890]
## User Story
As a Give User, I'm a little skeptical of plugins that look generic. It feels more polished and professional to see plugin icons in the plugin update screen rather than a generic one.

![image](https://user-images.githubusercontent.com/930724/37235762-34c9d702-23b6-11e8-96ae-712919181fb7.png)

## Current Behavior
I currently see these generic images which don't evoke confidence.

## Expected Behavior
I expect to be impressed with all of Give's Add-ons and presentation.

## Possible Solution
See possible filter here, which could be added into Give Core's licensing logic:
https://renventura.com/adding-update-icons-for-commercial-plugins/

I would expect that the images would be pulled from the EDD post type and not have to be shipped with the Add-on at all, so they could be updated from our site whenever we like.

**Comment by DevinWalker** [comment]
This can be closed because we now have support for custom icons in 2.5.0+ 

We don't have designs for the specific add-ons yet, though, so we are showing the Give "G" icon in the place of a custom icon. This looks pretty good in my opinion and will work moving forward for now.
