### ISSUE TITLE
epic(donor): implement donor wall

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#2898]
## User Story

As a Give user, I want to allow donors to opt in and display their donation so that others are encouraged to give.

## Current Behavior

I currently have no method of displaying donors who contributed to a cause without having to add custom code.

## Expected Behavior

I expect to have the option to display donors based on the expectations set from other crowdfunding platforms.

## Possible Solution

Research the prior work done in the [`Give-Display-Donors`](https://github.com/WordImpress/Give-Display-Donors) repo. Then design and implement donor wall.

**Comment by kevinwhoffman** [comment]
@DevinWalker Will donor wall functionality include the ability for the donor to leave a comment? If so I think the comment field could conditionally display only if the user opts in to be displayed in the donor wall.

**Comment by DevinWalker** [comment]
Closing as this has been completed
