### ISSUE TITLE
epic(admin-license): improve license activation

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#2904]
## User Story

As a new Give customer, I want a simple and clear method of activating the add-ons that I just purchased so that I can get to work actually using them.

## Current Behavior

I currently am annoyed when I have to activate multiple licenses for add-ons.

## Expected Behavior

I expect to activate the bundle I just purchased through a single interaction.

## Possible Solution

Redesign the licenses page so that the main section has bundle license activation options. Create another section or tab/page with options for individual add-on activation.

**Comment by mikejhale** [comment]
Work has been completed.
