### ISSUE TITLE
Translations are not being replace

### ISSUE THREAD

**Issue by andynguy3n** [impress-org/give#2971]
## User Story
As an admin. I want to translate this plugin to the language of my country

## Current Behavior
I currently using give-vi.mo and give-vi.po inside the folder: languages/give/ but it didn't work
What I have translated is:
```
#: includes/forms/template.php:758
msgid "Credit Card Info"
msgstr "Thông tin thẻ tín dụng"
```
![screen shot 2018-03-30 at 12 42 01 pm](https://user-images.githubusercontent.com/10527554/38125996-cdeb2b04-3417-11e8-9742-92b5daa085b1.png)

give-vi.mo: https://pastebin.com/cuM5tyG3
give-vi.po: https://pastebin.com/652chCmk

## Expected Behavior
I expect my translation is gonna replace the current text

## Possible Solution
I can edit directly give.pot but it doesn't recommend because with every update it will be lost

## Steps to Reproduce
- Went to https://translate.wordpress.org/projects/wp-plugins/give
- Selected "Vietnamese"
- Selected "Stable (latest release)"
- Exported - "all current" - as "Portable Object Message Catalog (.po/.pot)"
- Used PoEdit (https://poedit.net)
![screen shot 2018-03-30 at 12 48 12 pm](https://user-images.githubusercontent.com/10527554/38126118-a30f5a12-3418-11e8-8321-073faeea6dae.png)

**Comment by mikejhale** [comment]
Sorry for the late reply, however if you are still having issues we'd be happy to help you on wordpress.org support forum.
