### ISSUE TITLE
refactor(admin-donor): Add donor avatar filter for extensibility

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#2988]
## User Story
As a Give developer, I want to be able to customize the output of the Give donor profile image programmatically in order to integrate other third-party tools for more fine-tuned customization.

## Current Behavior
Currently, there is no filter for the Give donor profile image.

## Expected Behavior
I expect a filter to be present.

## Possible Solution
Add filter here:
https://github.com/WordImpress/Give/blob/release/2.1/includes/admin/donors/donors.php#L333

Like so:
`<?php echo apply_filters( 'give_donor_avatar_image_output',get_avatar( $donor->email ) ); ?>`

**Comment by DevinWalker** [comment]
Closing as we're using Gravatars now for donor avatars.
