### ISSUE TITLE
style(admin-form): merge "Shortcode" column into "Name column"

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3026]
## User Story
As an `admin`, I want to merge "Shortcode" column into "Name", so that I will get more space in form listing.

![image](https://user-images.githubusercontent.com/1784821/38655695-c824b336-3e33-11e8-9711-7245c31f05fe.png)

**Comment by kevinwhoffman** [comment]
Closing as the `Copy Shortcode` button is now in place.
