### ISSUE TITLE
fix(admin-setting): update menu css when there are lots of menu

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#3186]
## User Story

As a `Developer`, I don't want that CSS should get a break when there are lots of add-ons is activating 

## Current Behavior

I currently see UI getting break

## Expected Behavior

I expect that UI should not get a break

## Visuals
![image](https://user-images.githubusercontent.com/22215595/39657677-ec26999c-5027-11e8-8b24-bd0964ec3e48.png)

**Comment by DevinWalker** [comment]
Closing as this doesn't happen for 99% of people.
