### ISSUE TITLE
feat(admin-page): Add Menu to show number of pages related to Give

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#3237]
## User Story

As an `admin`, I want to know how many numbers of pages are related to Give

## Current Behavior

I currently not able to get the total number of Give Page count 

## Expected Behavior
I expect to show Give Menu which shows me a number of pages in that are related to Give

## Visuals
![image](https://user-images.githubusercontent.com/22215595/40281860-f042cf4c-5c83-11e8-8546-d188e11cf4d1.png)

**Comment by ravinderk** [comment]
@raftaar1191 It will be also good if we will able to search page content for `Give` shortcodes if found then they will appear in this list.

**Comment by raftaar1191** [comment]
Nice add up  @ravinderk I like this idea 

We can easily do this I guess

**Comment by mikejhale** [comment]
Closing due to lack of customer demand.
