### ISSUE TITLE
fix(admin-add-on): add-ons content description cluttered 

### ISSUE THREAD

**Issue by jaydeeprami** [impress-org/give#3250]
## User Story

As an `Admin`, I want `to see nicely set content for the listing of Add-ons` so that `I can see add-ons content properly and not cluttered`.

## Current Behavior
I currently see cluttered text on Add-on listing tab for few Add-on content.

## Expected Behavior
I expect to see nicely set add-on content for all the add-ons in the listing.

## Steps to Reproduce
1. Go to Add-ons listing tab

## Visuals
![screenshot-giverec test-2018 05 23-12-00-13](https://user-images.githubusercontent.com/15060983/40407726-f5a8968c-5e82-11e8-9245-005bf3fdb957.png)

## Tasks
- [ ] Fix

## Environment

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://giverec.test
Site URL: http://giverec.test
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: giverec.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.3
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: 2.1.3
Test Mode: Enabled
Currency Code: EUR
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://giverec.test/donation-confirmation/
Failure Page: http://giverec.test/donation-failed/
Donation History Page: http://giverec.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #273 ( 1SF329999A1063702 ) on  at . Status VERIFIED
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Query Monitor: by John Blackbourn & contributors – 3.0.0

### Inactive Plugins ###

Easy Digital Downloads: by Easy Digital Downloads – 2.9
Easy Digital Downloads - Authorize.net Gateway: by Easy Digital Downloads – 1.1.1
Easy Digital Downloads - Recurring Payments: by Easy Digital Downloads – 2.7.23
Easy Digital Downloads - Stripe Payment Gateway: by Easy Digital Downloads – 2.6.13
Give - Authorize.net Gateway: by WordImpress – 1.4.2
Give - Currency Switcher: by WordImpress – 1.0.3
Give - Fee Recovery: by WordImpress – 1.6
Give - Form Field Manager: by WordImpress – 1.3
Give - GoCardless Gateway: by WordImpress – 1.1.2
Give - Manual Donations: by WordImpress – 1.3.1
Give - Mollie Gateway: by WordImpress – 1.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.5
Give - PDF Receipts: by WordImpress – 2.3
Give - Recurring Donations: by WordImpress – 1.6.1
Give - Stripe Gateway: by WordImpress – 2.0.3
Give - Tributes: by WordImpress – 1.4.2
Gutenberg: by Gutenberg Team – 2.8.0

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: x.x.x</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: x.x.x</li>
    </ul>
</details>

**Comment by kevinwhoffman** [comment]
Closing as we will include a new layout in #2058.
