### ISSUE TITLE
fix: improve responsiveness of Export Donations screen

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3318]
## User Story
As a user, I want to see the export donations page vertically in mobile so that it is easy to view content in smaller devices for better UX.

## Current Behavior
I currently can see the horizontal scroll on mobile devices.

## Expected Behavior
I expect to be completely responsive UI

## Visuals
![image](https://user-images.githubusercontent.com/1852711/40914246-0682f164-6815-11e8-891b-f520885681f4.png)

## Related
- https://github.com/WordImpress/Give/issues/3266

## Tasks
- [ ] Check in all the responsive UI 
- [ ] Fix the issue
- [ ] Testing

**Comment by kevinwhoffman** [comment]
Closing since no customer has reported and exports are more likely to occur on desktop.
