### ISSUE TITLE
fix: ensure gateway list is styled correctly in Edge

### ISSUE THREAD

**Issue by emgk** [impress-org/give#3323]
## User Story
As a `Give-Admin`, I want to see the gateway list UI proper in IE browser so that can manage/re-order properly.

## Current Behavior
Currently, gateway list is not showing properly. see screenshot.

## Expected Behavior
Gateway list should not vanish in IE browser.

## Steps to Reproduce
1. Open Give Setting > Gateway page in IE browser.

## Visuals
![give-setting](https://user-images.githubusercontent.com/14994452/40968036-381a5542-68d2-11e8-9fdd-21cc8360cac0.png)

## Tasks
- [ ] Fix 
- [ ] Test

## Environment

<details>
    <summary>WordPress System Info</summary>
    
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Microsoft Windows</li>
        <li>Version: 8</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Edge</li>
        <li>Version: 11</li>
    </ul>
</details>

**Comment by mathetos** [comment]
Just tested with MS Edge on a live site running Give 2.5.2 and all is totally fine. See here:

![IE-GiveWP-Reorder-Gateways](https://user-images.githubusercontent.com/930724/61398076-1ac66280-a880-11e9-8d9f-84a62dffe250.gif)

Closing
