### ISSUE TITLE
refactor: remove repetitive sanitization of post variables

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3327]
## User Story
As a user, I want to process donation with minimal processing so that donating becomes quick.

## Current Behavior
I currently can see that there is the main function `give_process_donation_form` which have many internal functions to manage validations and other processing stuff. But, each of the function has their own sanitization of post variables which is passed through `give_clean` due to which it will do the same task in all the functions, in turn, increasing processing time for donation.

For example,
https://github.com/WordImpress/Give/blob/release/2.1.5/includes/process-donation.php#L31
https://github.com/WordImpress/Give/blob/release/2.1.5/includes/process-donation.php#L293
https://github.com/WordImpress/Give/blob/release/2.1.5/includes/process-donation.php#L395
and more.

## Expected Behavior
I expect to sanitize post variable once within `give_process_donation_form` function and use the sanitized variables in all the functions within it.

## Tasks
- [x] Investigate the number of functions using repetitive sanitization of post variables and replace it with general fn within Give core. Ref: https://github.com/impress-org/give/issues/3857
- [x] Testing the whole donation process even with add-ons

**Comment by ravinderk** [comment]
It has been resolved in https://github.com/impress-org/give/pull/4102. Closing it

**Comment by DevinWalker** [comment]
Note: this was decided to not be included because of complications with add-ons and other factors.
