### ISSUE TITLE
perf(donor-wall): review donor wall shortcode performance

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3360]
## ToDo
Test shortcode with
- [x] Fee recovery
- [x] Currency Switcher

**Comment by ravinderk** [comment]
@DevinWalker I am bumping up this issue from `2.2.0` because fee and currency switcher addon will recalculate donor donation amount to show actual donation amount. For this, these add-ons will refetch all or form or donor-related donation to calculate donation total.
To prevent improve performance we can develop stat API which help will prevent fee and currency switcher addon to recalculate donation amount each time https://github.com/WordImpress/Give/issues/3195

**Comment by kevinwhoffman** [comment]
Closing since donor wall performance will be addressed as part of the Stats API epic in https://github.com/impress-org/give/issues/3722
