### ISSUE TITLE
refactor(donation): replace and use .attr instead of .data

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3369]
## User Story
As a developer, I want to replace and use `.attr` instead of `.data` so that there won't be any conflict using ES6.

jQuery `.data` and Javascript `.dataset` or `.getAttribute` works differently so we are facing conflict while fetching the data using ES6 when the data attribute is set with jQuery.

## Current Behavior
I currently can see lots of another usage of `.data` in JS

## Expected Behavior
I expect to replace all the `.data` with `.attr`

## Tasks
- [ ] Replace .data with .attr
- [ ] Testing

**Comment by DevinWalker** [comment]
Closing as duplicate of https://github.com/impress-org/give/issues/3326#issuecomment-453369417
