### ISSUE TITLE
fix(pdf-receipt): receipt table header not shown on mobile page

### ISSUE THREAD

**Issue by Champdor** [impress-org/give#3376]
## User Story
As a donor I want to see the Receipt heading in the Donation History table on mobile.

If I view the Donation History page on mobile all the column headings are displayed but the Receipt heading which is generated (I think) by Give - PDF Receipt add-on.

## Current Behavior
Currently the said cell is visible on desktop pages but disappear in mobile view.

## Expected Behavior
Should be visible on mobile pages.

## Possible Solution
Give the heading text class="title-for-mobile"

## Steps to Reproduce
View Donation History page on mobile (or resize browser to 400 px width).

## Tasks
Fix the issue.

**Comment by mathetos** [comment]
Hi there, I believe this is most likely a Theme issue, and not a bug. This Repo is primarily for bugs for development. 

I'd be happy to review any trouble you're having if you can submit the issue to our Free Support forum on WP.org: https://wordpress.org/support/plugin/give

Thanks!
