### ISSUE TITLE
fix: allow admin to change separator per currency

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3382]
@samsmith89 commented on [Fri Jun 15 2018](https://github.com/WordImpress/Give-Currency-Switcher/issues/170)

## User Story
As a site admin, I want to set the thousand and decimal separator so that I can provide more clarity for my donors.

Marking as fix and not feat, because the customer states that the current separators are not displaying as expected.

## Current Behavior
I currently can only set this on a global basis.

## Expected Behavior
I expect to be able to set the separators on a per currency basis.

## Steps to Reproduce
Steps provided by Customer:
1. Expected behavior with USD, EUR, GBP, CAD, DKK, HKD, JPY, MYR, MXN, SGD, CHF, THB, AED, KWD, PEN
2. Thousands and decimal separators are reversed for NOK, ARS
3. Thousands separator becomes " " (space) and decimal separator "," for SEK

## Visuals
![screen shot 2018-06-15 at 9 06 46 am](https://user-images.githubusercontent.com/20672471/41469525-80c8a70c-707b-11e8-8e5d-a863540f58e0.png)

## Related
https://secure.helpscout.net/conversation/576771301/18088?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://givecurrency.local
Site URL: http://givecurrency.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givecurrency.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 2.1.4
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://givecurrency.local/donation-confirmation/
Failure Page: http://givecurrency.local/donation-failed/
Donation History Page: http://givecurrency.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Razorpay, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.2
Give - Donation Plugin: ❌ Unlicensed – by WordImpress – 2.1.4
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.1.4
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 2.0.5

### Other Active Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0

### Inactive Plugins ###

qTranslate-X: by qTranslate Team – 3.4.6.8

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by Champdor** [comment]
I second that. Hungarian forint (HUF) needs exactly the same as in the visuals.

**Comment by kevinwhoffman** [comment]
@ravinderk Now that we have defined appropriate separators and positions in [`give/includes/currencies-list.php`](https://github.com/impress-org/give/blob/release/2.4.0/includes/currencies-list.php), I think this can be closed. Please review and close if you agree.

**Comment by ravinderk** [comment]
@kevinwhoffman You right. closing this one because every currency now has there owned formatting settings and we call also modify then with `give_register_currency` or `give_currencies` filter
