### ISSUE TITLE
feat(form): add ability to display both percentage and amount given in goal

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3408]
## User Story
As a site admin, I want to be able to show multiple options for values in the Donation Goal. Like the percentage and amount contributed, or the amount raised and the number of donors in my form so that I have more control over the information displayed.

## Current Behavior
I currently can only display one of four values:
1. Number of Donations
2. Number of Donors
3. Percentage raised 
4. Amount raised

## Expected Behavior
I expect to be able to show a combination of the above-mentioned values.

## Related
https://secure.helpscout.net/conversation/608881522/20641?folderId=1823994

**Comment by kevinwhoffman** [comment]
Discussed with @DevinWalker. This is snippet territory or custom development. We already provide several display options for different goal types. Closing as wontfix.
