### ISSUE TITLE
fix: prevent tooltip span from wrapping input element

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3499]
## User Story

As a `Give User` I expect to be able to style the checkboxes in my Give forms in a consistent manner. 

## Current Behavior

I currently struggle with the "Create an account" checkbox because it resides within the `<span>` of the tooltip contrary to the Terms & Conditions checkbox and other checkboxes which correctly are NOT wrapped in a `<span>`.

## Expected Behavior

I expect that similar form inputs throughout the Give form would have identical markup to ensure simple and consistent styling with minimal CSS.

## Possible Solution

It's not clear to me yet why this function results in the `<span>` wrapping the `<input>` element but this is where that happens:
https://github.com/WordImpress/Give/blob/release/2.2/includes/forms/template.php#L1288-L1296 

It seems this is actually intentional in order to trigger a tooltip directly on the checkbox, but (1) it's just not awesome markup; (2) it creates style problems. See Visuals below for an example.

I think in order to show that Registration is "required", we should instead customize the `(?)` tooltip to indicate that, since that is visually where donors will look for clarifying information. There's nothing to indicate that they should look for additional information while hovering over the checkbox -- plus you have to actually click the checkbox on mobile to trigger that tooltip, so overall it's not a good experience.

Additionally, I don't believe the hint.css requires that the element be a `<span>`, we can just use the `<i>` to trigger the tooltip.

**CURRENT MARKUP**
```
<label for="give-create-account-578">
					<span aria-label="Registration is required to donate." class="hint--top hint--bounce" rel="tooltip">
						<input
							type="checkbox" name="give_create_account" value="on" id="give-create-account-578"
							class="give-input give-disabled" checked="">
					</span> <span>Create an account</span>
					<span class="give-tooltip hint--top hint--medium hint--bounce"
					      aria-label="Create an account on the site to see and manage donation history."
					      rel="tooltip"><i class="give-icon give-icon-question"></i></span> </label>
```

**SUGGESTED MARKUP**

Ideally a simple fix to that function will result in this markup:
```
<label for="give-create-account-578">
                    <input type="checkbox" name="give_create_account" value="on" id="give-create-account-578" class="give-input give-disabled" checked="">Create an account
                    <i class="give-icon give-icon-question give-tooltip hint--top hint--medium hint--bounce" aria-label="Create an account on the site to see and manage donation history." rel="tooltip"></i>
</label>
```

## Visuals

![image](https://user-images.githubusercontent.com/930724/42840642-626d997a-89bc-11e8-8c2c-73d70b547bae.png)

## Acceptance Criteria
- [x] The markup is consistent with other checkboxes in Give form, similar to the example above.
- [x] The tooltip still works as intended.
- [x] The markup is consistent in all variations of whether the form requires registration or is optional.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak, @ravinderk 
Topic: Update HTML markup as per Matt suggestion  
Result: I'll look over it and if hint.css will break/affect to other functionality into the plugin then leave that for tooltip only and provide an update to Kevin for that.

**Comment by kakshak** [comment]
@kevinwhoffman I checked the suggested markup for tool-tip and here is the scenario for that.
- In current markup `<input>` is not wrapped into `<span>`. So, that is already updated.
- The old markup for the tooltip is designed globally. To make the changes as per Matt's suggestion, we need to change lot the HTML, CSS and JS and this change will take a lot of CSS makeover which is functional globally as of now. So, It will be good if we kept the html as it is that is now only for tooltip.

Below is the new/current markeup

```
<label for="give-create-account-10">
	<input type="checkbox" name="give_create_account" value="on" id="give-create-account-10" class="give-input">Create an account
	<span class="give-tooltip hint--top hint--medium hint--bounce" aria-label="Create an account on the site to see and manage donation history." rel="tooltip">
		<i class="give-icon give-icon-question"></i>
	</span>
</label>
```
Please let me know your thoughts on this.

**Comment by kevinwhoffman** [comment]
I have reviewed the current markup in Give v2.3.0 and confirmed the checkbox is not wrapped within the tooltip span. Leave the tooltips markup as is. Closing.
