### ISSUE TITLE
fix: format dates to WordPress `date_format`

### ISSUE THREAD

**Issue by jr70** [impress-org/give#3502]
## User Story

As a `Give Admin`, I want the `start/end date filter format` in the Donations admin page to match my locale so that `I have a consistent user experience`.

My website has UK English (en_GB) as the site language so I expect all dates to be formatted as `dd/mm/yyyy`.
## Current Behavior

Currently the date filter boxes have a placeholder of `mm/dd/yyyy` and when a date is selected from the dropdown calendar it is returned in the same US date format.

## Expected Behavior

I expect to see `dd/mm/yyyy` as the placeholder and have the date returned from the calendar dropdown formatted to `dd/mm/yyyy`.

## Acceptance Criteria

- [x] The date picker supports all date format (US or non-US) based on WordPress date settings.
- [x] Supporting WP date format does not affect other functionality like donation exports.

## Related
https://secure.helpscout.net/conversation/671557137/26233
https://secure.helpscout.net/conversation/658188284/25003?folderId=672197

**Comment by kevinwhoffman** [comment]
@jr70 Thank you for the detailed issue. I've assigned @Sidsector9 to confirm the issue and work on a fix in an upcoming maintenance release of Give `2.2.1`.

**Comment by raftaar1191** [comment]
## Finding 
We need to fix the date format at other places to

![image](https://user-images.githubusercontent.com/22215595/43043843-9d7614b6-8db8-11e8-88b0-d5b4a30814cb.png)


![image](https://user-images.githubusercontent.com/22215595/43043848-b96d5d3c-8db8-11e8-8ed3-beb6e923293c.png)



@ravinderk should I create a new issue for this or else will fix this in the current issue as well

**Comment by raftaar1191** [comment]
Closing this issue as after running `npm run dev` this issue was solved

**Comment by mathetos** [comment]
Reopening as we have a new customer reporting this same problem. To clarify, the original report was NOT about the Export functionality, but the Donations screen. This screen:
![image](https://user-images.githubusercontent.com/930724/46113800-bc22e180-c1a4-11e8-820d-88c8684feb5e.png)

## Steps to Replicate:
1. Go to "Settings > General"
2. For the "Date Format" setting, use `j F, Y` or some other non-U.S. date format
3. Navigate to "Donations > Donations" and attempt to use the Date Filter at the top of the donations table. It will not fill the fields correctly. 

Customer reported here:
https://secure.helpscout.net/conversation/658188284/25003/

**Comment by kevinwhoffman** [comment]
@Sidsector9 I recently fixed a similar issue in WPBR https://github.com/WordImpress/wp-business-reviews/pull/259

I think it has to do with certain PHP date formats not being compatible with JS date formats.

**Comment by marutim** [comment]
Along with that, if the date format is set to dd/mm/yyyy, the export donations do not work at all. It alerts the admin with the following error
![image](https://user-images.githubusercontent.com/3498917/46167848-853bf100-c2b4-11e8-930f-163415e1fe4b.png)

The fix should make sure that export functionality should work with all date formats.
