### ISSUE TITLE
fix: email tags not working for specific email templates.

### ISSUE THREAD

**Issue by Sidsector9** [impress-org/give#3510]
## User Story
As a `user`, I want to see the description of only those email tags which are specific to the email notification type so that I don't use email tags which don't belong to the particular context.

As per observation, the following email tags should not be part of the following email notification type:
- **New Donation**: `{reset_password_link}`
- **Donation Receipt**: `{reset_password_link}`,
- **New User Registration**: `{reset_password_link}`, `{email_access_link}`
- **User Registration Information**: `{email_access_link}`

## Current Behavior
The above email tags do not work in their respective email notifications.

## Expected Behavior
I expect to chose only those email template tags which are specific to the given context.

## Tasks
- [ ] Remove email template tags which are not applicable to the respective email botifications.

**Comment by kevinwhoffman** [comment]
@DevinWalker checked `{reset_password_link}` in the Donation Receipt email and confirmed this is still an issue. We should make sure any tags that appear in the email edit screen work as intended.

**Comment by ravinderk** [comment]
@DevinWalker I was able to reproduce this issue:

**New Donation**: {reset_password_link} --> working now
**Donation Receipt**: {reset_password_link}, --> Working now
**New User Registration**: {reset_password_link}, <s>{email_access_link}</s> this is not pass of allowed email tag for this email
**User Registration Information**: <s>{email_access_link}</s> this is not pass of allowed email tag for this email

Testing Video: https://www.loom.com/share/56ba83e6a2394bd5bf7461dcbbdb0d56
