### ISSUE TITLE
fix(form): perform country/state list update logic on onpage to improve processing speed

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3529]
## User Story
As a `donor`, I want process donation faster. We have multiple ajax request on donation form for validation and one of them is for country/state list update. We can reduce this ajax query by performing that in on the page. On page means import country and state list to page as a JSON object and then set state list from that object when country change.

![image](https://user-images.githubusercontent.com/1784821/43391943-c4762170-940f-11e8-91ba-48e15b24ce2f.png)

**Comment by kevinwhoffman** [comment]
Iceboxing until we address the Form API.

**Comment by mikejhale** [comment]
Closing as current form performance is acceptable.
