### ISSUE TITLE
feat(donation): feat to provided an per page option setting which will display number of donation   

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#3557]
## User Story

As an `Admin`, I want UI setting where I can control the number of donation that can be displayed on the Donation history page, manage pagiation and any other place. Like we have in WordPress Dashboard -> Setting -> Reading > Blog pages show at most

## Current Behavior

I currently need to edit in shortcode param or use a filter to do that 

## Expected Behavior

I expect to change it from UI

## Possible Solution
![image](https://user-images.githubusercontent.com/22215595/43581544-f4be43f8-9676-11e8-888a-4146f132e134.png)

**Comment by raftaar1191** [comment]
@kevinwhoffman @ravinderk 

What are your opinion on this issue

**Comment by kevinwhoffman** [comment]
Closing as this is possible in the shortcode already.
