### ISSUE TITLE
feat: allow login with email address WordPress does

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3563]
## User Story
As an `admin`, I want `donors` to allow to login with an email address so that they do not have to remember there email `username`.

![image](https://user-images.githubusercontent.com/1784821/43626213-8735b652-970e-11e8-8319-e881214a04cd.png)

**Comment by kevinwhoffman** [comment]
@kakshak The WordPress login screen allows users to log in with either their username or password, but the login form within Give only seems to allow usernames. See if you can update the logic to accept email addresses like the WP core login form does.
