### ISSUE TITLE
Ask for .htaccess password when admin directory is password protected 

### ISSUE THREAD

**Issue by Jasi2169** [impress-org/give#3572]
Ask for .htaccess password when admin directory is password protected,

It does work fine without password but for more security i have enabled admin directory password in my hosts cpanel so if i click donate then it opens .htaccess password if i cancel it it stays please wait...

i dont think i need to provide that password to user so fix it

**Comment by kevinwhoffman** [comment]
Hi @Jasi2169 we've looked into this and there is no way we can make Give work if the admin directory is password-protected. This will likely cause issues with several other plugins and WordPress core.

**Comment by Jasi2169** [comment]
i have like other 7-9 plugins working fine for me like elementor,ithemes security,yoast,limit login,maintenance etc no issues on them
