### ISSUE TITLE
fix(donor-wall): display comments on multisite with donor wall

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#3623]
## User Story

As a `give admin`, I expect `the donor wall to display comments on Multisite environments`

## Current Behavior
When using multisite, the comments on a donation do not display on a multisite environment in the donor wall.

## Expected Behavior

I expect the comments to display

## Steps to Reproduce
1. Install a multisite environment, and network activate Give core.
2. Create a few donations with comments
3. Create a donor wall shortcode on a new page
4. The comments do not show up.

## Related
- https://secure.helpscout.net/conversation/640775471/23446/?folderId=848135

## Tasks

- [ ] ensure the comments display on the donor wall in all environments
- [ ] ensure that donatiosn without comments display correctly as well. 

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://multigivewp.dev
Site URL: http://multigivewp.dev
WP Version: 4.9.8
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: multigivewp.dev
TLS Connection: Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 188

Warning: file_get_contents(): Failed to enable crypto in /app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 188

Warning: file_get_contents(https://www.howsmyssl.com/a/check): failed to open stream: operation failed in /app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 188
TLS Connection: 
Server Info: Flywheel/4.1.0
PHP Version: 5.6.20
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
PHP Max Upload Size: 1 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2k - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.36
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.3
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information❌Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://multigivewp.dev/donation-confirmation/
Failure Page: http://multigivewp.dev/donation-failed/
Donation History Page: http://multigivewp.dev/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Disabled

### Inactive Plugins ###

Give - 2Checkout Gateway: by WordImpress – 1.0.2
Give - Authorize.net Gateway: by WordImpress – 1.2.3
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0
Give - CSV Toolbox: by WordImpress – 1.0
Give - Dwolla Gateway: by WordImpress – 1.1
Give - Email Reports: by WordImpress – 1.0.1
Give - Fee Recovery: by WordImpress – 1.2.4
Give - Form Countdown: by WordImpress – 1.0
Give - Form Field Manager: by WordImpress – 1.2
Give - GoCardless Gateway: by WordImpress – 1.0.0
Give - Google Analytics Donation Tracking: by WordImpress – 1.0
Give - MailChimp: by WordImpress – 1.3.6
Give - Manual Donations: by WordImpress – 1.2
Give - Old Meta Switcher: by WordImpress – 1.0
Give - Paymill Gateway: by WordImpress – 1.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.3
Give - PayUmoney: by WordImpress – 1.0.1
Give - PDF Receipts: by WordImpress – 2.0.8
Give - Per Form Emails: by WordImpress – 1.0.2
Give - Per Form Gateways: by WordImpress – 1.0.1
Give - Recurring Donations: by WordImpress – 1.3.1
Give - Recurring Helper: by WordImpress – 1.0
Give - Stripe Gateway: by WordImpress – 1.5
Give - Tributes: by WordImpress – 1.1
Give - Update Goal Progress: by Matt Cromwell – 1.0
Give - WePay Gateway: by WordImpress – 1.3.1
Give - WP All Import Addon: by Ben Meredith – 1.0
Give - Zapier: by WordImpress – 1.1.2

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by Sidsector9** [comment]
Hey @Benunc , I'm able to see the donation comments on my end on a multi-site, can you watch this video and kindly revert back?

https://www.useloom.com/share/faebd97b524e4eb1bb4a13c995701616

**Comment by ravinderk** [comment]
@DevinWalker This issue will be taken care in this epic issue: https://github.com/wordimpress/give/issues/3623

So bumping it to `2.3.0`

**Comment by kevinwhoffman** [comment]
@ravinderk Did you address this in the epic related to the custom comment table? If so, please close.

**Comment by ravinderk** [comment]
@kevinwhoffman yes, it has been fixed, so closing this.

**Comment by kevinwhoffman** [comment]
For clarity, this issue regarding comment visibility does not seem to be fixed in latest `release/2.3.0` so we will resolve in #3744.
