### ISSUE TITLE
feat: add option to import and export donor comment 

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#3682]
## User Story

As an Admin, I want to import Donor Comment from CSV and also export Donor Comment when exporting the donation

## Visuals
1. At the time of exporting the donation, I do not see any columns that display `Donor Comments`![image](https://user-images.githubusercontent.com/22215595/45519531-1601cf80-b7d3-11e8-823a-50564aff5996.png)

2.  Also did not find any fields for importing donor comment from CSV
![image](https://user-images.githubusercontent.com/22215595/45519597-637e3c80-b7d3-11e8-8afe-43231bfb7d6a.png)

**Comment by kevinwhoffman** [comment]
Moving to icebox until we complete the migration of comments to custom table.

**Comment by kevinwhoffman** [comment]
Closing in favor of #3743 which focuses on exporting comments.
