### ISSUE TITLE
fix: ensure Give blocks are compatible with latest Gutenberg

### ISSUE THREAD

**Issue by Sidsector9** [impress-org/give#3697]
## Current Behavior
Currently none of the Give blocks work with Gutenberg 3.8.0 since Give is using certain JS functions which are deprecated in the latest Gutenberg version. 

## Expected Behavior
I expect all the Give Blocks to work with the latest Gutenberg version.

## Steps to Reproduce
1. Install Gutenberg 3.8.0
2. Try to add any of the Give Blocks

None of the blocks show up.

## Acceptance Criteria
- [ ] Make Give Blocks compatible with latest Gutenberg version.
- [ ] Test all the Give Blocks.

**Comment by mathetos** [comment]
Just came here to make this issue myself.

**Comment by Sidsector9** [comment]
I'm facing a problem resolving the asynchronous response of `wp.api.collections.Give_forms()` to get the Form List added to the Form Block. Once this is fixed, this PR will be merge-ready.

I have discussed this with @ravinderk and he will be looking into this.

**Comment by kevinwhoffman** [comment]
@ravinderk WordPress 5.0 Beta 1 has released, so please make sure you are using it when developing the Give blocks. https://wordpress.org/news/2018/10/wordpress-5-0-beta-1/

**Comment by kevinwhoffman** [comment]
After discussion with @ravinderk we are closing this in favor of a new issue with acceptance criteria relative to WP 5.0 Beta.
