### ISSUE TITLE
fix: give plugin count and display all the add-on on plugin menu page 

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#3700]
## Current Behavior

I currently can see the Give Plugin menu count is not coming proper and also the list of the plugin that is being shown is also not the same

## Expected Behavior

I expect the menu count and the list of the plugin show should be perfect 

## Steps to Reproduce
Check the video

## Visuals
Video Link: https://screencast-o-matic.com/watch/cFQYQ0qPdF

![image](https://user-images.githubusercontent.com/22215595/45808941-a5801480-bce4-11e8-9fc0-9884721d1a1c.png)

![image](https://user-images.githubusercontent.com/22215595/45809124-1293aa00-bce5-11e8-8181-398d40bcd977.png)

**Comment by kevinwhoffman** [comment]
@Sidsector9 See if you can recreate this issue by installing Give core and Stripe add-on and then check and see if `Give (2)` displays correctly at the top of the Plugins page. If it does not, take steps to fix it and try to recreate with more add-ons.

**Comment by Sidsector9** [comment]
@kevinwhoffman What should be the correct author? GiveWP or WordImpress?

**Comment by kevinwhoffman** [comment]
@Sidsector9 Update the logic of the filter to display all plugins that start with `Give -`. This is the only way to display the expected results without changing the author of several add-ons.
