### ISSUE TITLE
fix: remedy server load for high traffic sites

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#3713]
# Bug Report

## User Story

As a site admin for a high traffic site, I want Give resources to not load on every ajax call so that my site performance is not affected.

Directly from the user:

> The key issue is that the init is loaded into the plugins_loaded hook which means that for every request and every ajax call - across the entire site - Give is being loaded even though we technically only need the plugin's functionality on a few different pages (donate, donor management, etc). It's easy to turn off the JS and CSS for the plugin on unrelated pages, but we can't keep the PHP code from being loaded into the hook since that has nothing to do with JS or CSS and simply seems to be built into the plugin's functionality. I have a developer I am working with and the way he phrased it to be was as follows: "We need to find a way to not have the Give plugin's PHP force loaded every time there is a server request".
> 
> 
> If that is not possible, I completely understand and I wouldn't ask you guys to rewrite your code as a result - it just means I have to look elsewhere. If you want to dig around the WP Admin or WHM part of our site, I am happy to send you credentials, but maybe what we are asking is simply not possible.
> 
> 
> I have attached a screenshot from New Relic for a test we did yesterday showing response time before and after disabling all Give plugins. Again, not a lifesaving difference but still very meaningful considering our foundation makes up for a tiny fraction of the overall site traffic and site functions.
> 

<img width="774" alt="screen shot 2018-09-26 at 10 08 49 am" src="https://user-images.githubusercontent.com/9629102/46220745-1775e080-c319-11e8-9b2a-bc073257ad69.png">

> also - here is a screenshot showing you how Give compares to the other plugins that require top resources on the server. We process about 50-100 orders a day and have about 2-3K users on the Ultimate Member part of our site. As far as donations are concerned, we get maybe a few a week to put that in comparison. Anyway, just trying to put this all in perspective for you to see if there is anything we can do. Thanks again for your assistance…

<img width="1154" alt="screen shot 2018-09-26 at 5 28 23 pm" src="https://user-images.githubusercontent.com/9629102/46220795-41c79e00-c319-11e8-84ca-94e8232a8515.png">

## Current Behavior

See the above screenshots

## Expected Behavior
I expect Give not to drmatically affect site performance

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
This requires a high traffic site to replicate, but the data above seems to indicate that it is a legit concern.

## Related
https://secure.helpscout.net/conversation/671554261/26231/

## Acceptance Criteria
- [ ] the Give PHP is not executed on every ajax call site-wide.
- [ ] if that's not possible, some workarounds are suggested for this particular user, in the form of code snippets.

**Comment by kevcampb** [comment]
This is likely closely related to the number of filters that give adds to core objects. For example on get_post_metadata, give adds 5 filters. On normal sites I'd expect there are 0 filters on this option.

```
Give_DB_Payment_Meta::__get_meta
Give_DB_Form_Meta::__get_meta
_give_20_bc_get_old_payment_meta
_give_20_bc_get_new_payment_meta
give_bc_v20_get_payment_meta
```

There are some quick improvements that can be made here by altering the conditional logic at the start of these methods. These methods only operate on certain meta keys, and will return without action for other keys. Unfortunately this test occurs after calling some methods (give_has_upgrade_completed, get_post_type) which incur additional costs. Reordering these seems straightforward.

Regardless of ordering, this number of filters will still be really heavy for some sites. Wordpress menus make a lot of calls to get_post_meta, and even just this number of function calls alone is significant.

There are a lot of javascript scripts which are added but not required on the majority of pages. Some of these are quite heavy and render blocking.

A quick workaround for users may be to only load give plugins where required, either using something like https://wordpress.org/plugins/plugin-organizer/ or by taking the approaches mentioned in https://stackoverflow.com/questions/6235338/wordpress-loading-javascript-only-where-shortcode-appears

**Comment by ravinderk** [comment]
@kevcampb Thanks for the comment.
 
FYI we already have an issue to remove backward compatibility code.  Your suggestion is part of it: https://github.com/impress-org/give/issues/3003

@kevcampb Which Give version are you using because, In `2.4.0`, we reorganized file and code for early exit meta query filter. Which will improve plugin few performances a little bit.
ref: https://github.com/impress-org/give/issues/3871

We are actively working on plugin performance.

**Comment by kevcampb** [comment]
@ravinderk we haven't upgraded to 2.4.x yet. Briefly looking at the code there's still at least 4 filters applied to get_post_meta, and the same problematic code is there, so I'm not sure it will change anything. Will let you know if there's an improvement when we next do a round of package updates.

**Comment by DevinWalker** [comment]
@kevcampb 	we continue to work hard on improving the plugin's performance. In 2.5.0 we've implemented further optimizations and this work is ongoing.

1. We've used BlackFire to validate our plugin performance (faster than Woo or EDD now)
2. Query monitor is continually running on our local dev environments
3. Continual code audits for optimization

As such, I'm going to close out this specific issue as complete. Please feel free to open any new issues related to performance and we will review!
