### ISSUE TITLE
fix: replace `Card Name` with `Cardholder Name`

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#3714]
# Bug Report

## User Story

As a Donor, I frequently confuse "Card name" to mean "American Express/Visa/Mastercard/etc" when it should read "Cardholder Name" for simplicity and clarity.

## Current Behavior
Currently in Give core on this line https://github.com/WordImpress/Give/blob/master/includes/forms/template.php#L981

...and give-stripe in this line
https://github.com/WordImpress/Give-Stripe/blob/master/includes/give-stripe-helpers.php#L157

...and twocheckout on this line
https://github.com/WordImpress/Give-2Checkout/blob/master/includes/give-twocheckout-helpers.php#L85

It reads "Card name" and even the associated tooltips are not very helpful "The name printed on the front of the card" could also be "American Express"

## Expected Behavior
I expect the Field to read "Cardholder Name" (note capitalization) and all associated tool tips to be more helpful as well. Something like "The name of the credit card account holder."

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Enable any add-on that accepts cards
2. The field is displayed confusingly.

## Acceptance Criteria

- [X] The field label is changed from `Name on the Card` to `Cardholder Name`.
- [X] The input placeholder is changed from `Card Name` to `Cardholder Name`.
- [X] The tooltip reads: `The name of the credit card account holder.`
- [X] The above changes have been verified in the following plugins:
    - [X] Give core
    - [x] Stripe
    - [x] Square
    - [X] 2Checkout

**Comment by kevinwhoffman** [comment]
@nishitlangaliya See the acceptance criteria above. You should submit a PR for Give core and a PR for 2Checkout to update the strings in question.

Mehul has already updates Stripe so no need to worry about that.

**Comment by mehul0810** [comment]
@kevinwhoffman Just to update, I've updated this issue for Square, not Stripe. I'll update it for Stripe today as I'm doing all the tasks of Stripe. Let me know if there is any change.
