### ISSUE TITLE
Custom Stripe webhook actions are being hijacked by Recurring plugin

### ISSUE THREAD

**Issue by spingary** [impress-org/give#3716]
# Bug Report

## User Story
As a developer, I want to create a custom action for the Stripe webhook so that I can do additional processing with the other events that Stripe sends.

## Current Behavior
I create a function and add_action for a Stripe webhook event, but Stripe Recurring plugin intercepts it and then doesn't execute my function because it isn't looking for the main Stripe plugin hooks, and then returns a status message ("Something went wrong with processing the payment gateway event") to Stripe then exits.

## Expected Behavior
The Recurring Donations plugin should either listen to a different stripe listener parameter, or call the actions of the Stripe plugin after calling actions of its own plugin.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [X] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Add action code for Stripe listener:
```
function stripe_charge_succeed_event($event) {
  // code to do some stuff with the event object
}
add_action( 'give_stripe_event_charge.succeeded', 'stripe_charge_succeed_event');
```
2. Test the webhook call through Stripe
3. Get "Something went wrong with processing the payment gateway event" as response.

## Possible Solution

My quick fix is to simply change my action to a Recurring action, like this:

`add_action( 'give_recurring_stripe_event_charge.succeeded', 'stripe_charge_succeed_event');`

A better fix might be to have the Recurring plugin also do the main Stripe plugin actions:

In Recurring plugin's give-recurring-stripe.php: 

```
	public function process_stripe_event( $event_id ) {

		try {

			// Retrieve the event from Stripe via event ID for security.
			$stripe_event = \Stripe\Event::retrieve( $event_id );

			switch ( $stripe_event->type ) {
SNIPPED
			}

			do_action( 'give_recurring_stripe_event_' . $stripe_event->type, $stripe_event );
>>> add         do_action('give_stripe_event_' . $stripe_event->type, $stripe_event );
			return $stripe_event->type;

```

## Acceptance Criteria
- [X] Stripe webhook actions are executed without using recurring action call

**Comment by mehul0810** [comment]
@spingary We have supported recurring for the popular payment gateways( like we have for Stripe) in the recurring add-on. So, we have a different filter to do additional steps for one time donations and recurring donations separately during webhook call.

So, I would suggest you use it as below:
```
function my_prefix_do_something( $stripe_event ) {
	// Do something as per your need.
}
add_action( 'give_stripe_event_{event_type}', 'my_prefix_do_something' );
add_action( 'give_recurring_stripe_event_{event_type}', 'my_prefix_do_something' );
```

> I create a function and add_action for a Stripe webhook event, but Stripe Recurring plugin intercepts it and then doesn't execute my function because it isn't looking for the main Stripe plugin hooks, and then returns a status message ("Something went wrong with processing the payment gateway event") to Stripe then exits.

I've already opened a new issue to handle this scenario for proper development practices. https://github.com/impress-org/give-stripe/issues/356

Closing this issue for now.

Please feel free to re-open this issue, if you still have any questions.
