### ISSUE TITLE
Recurring Donations plugin's Stripe webhook not looking for the right key

### ISSUE THREAD

**Issue by spingary** [impress-org/give#3717]
# Bug Report

## User Story
When creating custom action for Stripe's webhook, I noticed that the process_webhooks() function was looking for the wrong key in Stripe's event data object.  My actions are then never called.  I'm wondering if this would also prevent the recurring actions from recording those Stripe transactions?  (Sorry, just started on this site and I have no recurring transactions to see if this is true or not).

## Current Behavior
When testing webhook calls from Stripe, they're always being returned as "Something went wrong with processing the payment gateway event."

## Expected Behavior
It should execute my webhook based on the event type.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [X] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Add action code for Stripe listener:

```
function stripe_charge_succeed_event($event) {
  // code to do some stuff with the event object
}
add_action( 'give_stripe_recurring_event_charge.succeeded', 'stripe_charge_succeed_event');
```

2. Test the webhook from Stripe
3. Get "Something went wrong with processing the payment gateway event" as response.

## Possible Solution

The process_webhooks() function (in Recurring plugin) is looking for

`$event_json->data->object->charge` 

in this bit of code:

```
			if ( ! empty( $event_json->data->object->charge ) ) {

				// Process Stripe Event, if donation id exists.
				$result = $this->process_stripe_event( $event_json->id );
			}
```

But my Stripe data being sent does not have the key. It does have data->object with a value of "charge":

```
{
  "object": {
    "id": "ch_1DFl1wGbeGPjvk5tXcVydh68",
    "object": "charge",
```

**In my Stripe account I am using the latest API version. Could this be the problem?    I am not using Stripe Connect - I am using Stripe API keys, so Stripe is not matching API versions for me.**  

Still, I feel that the code should not look for the "charge" as a validation to process the webhook. What if my custom action needs to act on non-charge related events?  

The main Stripe plugin's process_webhooks() function does not have this if condition.  So if we can get [3716](https://github.com/impress-org/give/issues/3716) fixed, then I can use that action call instead of the recurring one.

## Related
[Custom Stripe webhook actions are being hijacked by Recurring plugin](https://github.com/impress-org/give/issues/3716)

## Acceptance Criteria
- [X] Custom Stripe event webhooks actions execute as designed

**Comment by mehul0810** [comment]
@spingary Thanks for submitting a detailed issue.

> I'm wondering if this would also prevent the recurring actions from recording those Stripe transactions?

No, It will not prevent any recurring actions from recording during Stripe transactions even if you receive "Something went wrong with processing the payment gateway event" as a response. 

> When testing webhook calls from Stripe, they're always being returned as "Something went wrong with processing the payment gateway event."

We have already worked for this within recurring add-on. However, the Stripe add-on needs the same improvement. We will move this issue to Stripe repository and fix it.

> The `process_webhooks()` function (in Recurring plugin) is looking for `$event_json->data->object->charge`

> Still, I feel that the code should not look for the "charge" as a validation to process the webhook. What if my custom action needs to act on non-charge related events?

We are no longer having this check for `process_webhooks()` in recurring add-on `1.8.0`. So, if you're using the same version then you can use "Test Webhook" with action `give_recurring_stripe_event_{event type}`.

CC: @DevinWalker @kevinwhoffman

**Comment by mehul0810** [comment]
Issue moved to [impress-org/give-stripe #356](https://github.com/impress-org/give-stripe/issues/356) via [**ZenHub**](https://www.zenhub.com/)
