### ISSUE TITLE
fix: ensure compatibility with Thrive Architect page builder

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#3728]
# Bug Report

## User Story

As an admin, I want to use Thrive Architect and Give alongside each other without conflict so that I can visually build my site but right now I'm limited because the TinyMCE is displaying Give's shortcode drop-down menu and covering my formatting options.

This is an identical issue to https://github.com/impress-org/give/issues/3171 but for the Thrive builder.

## Current Behavior
![screen shot 2018-10-03 at 10 17 48 am](https://user-images.githubusercontent.com/9629102/46416493-a148f380-c6f5-11e8-8638-ed876447599b.png)

## Expected Behavior
I expect the Give shortcode builder to not cover the inputs.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install Thrive Architect Page builder (this is difficult because they prevent it from being used without an active license. I was able to make it functional by adding an option to wp_options indicating that the license is active, but still the WordPress content widget was not functional. The easiest way to replicate is with a full duplicator package installed locally of the site, attached to this issue in slack. I will also add a zip of the plugin to that.)
2. On a new page being edited by the Thrive Architect interface, attempt to insert the WordPress Content widget.
3. You will see the above error.

## Possible Solution
add an additional check for Thrive here (and following): https://github.com/impress-org/give/pull/3201/commits/1999229b7f2fc87c301b405290632964e210faca#diff-28aac9bc1c8569ab27000e85f746b3baR81

## Related
https://secure.helpscout.net/conversation/675492467/26519?folderId=848135

## Acceptance Criteria

- [ ] The Shortcode builder doesn't malfunction
- [ ] The shortcode builder continues to work on non-thrive pages

## Environment

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: redacted
Site URL: redacted
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: (#9)
Page for Posts: Unset
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: 
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.2.10
PHP Post Max Size: 128 MB
PHP Time Limit: 90
PHP Max Input Vars: 2000
PHP Max Upload Size: 128 MB
cURL Version: 7.61.0, OpenSSL/1.0.2p
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions❌New User Registration❌User Registration Information✔Email access
Upgraded From: 2.2.5
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://redacted/order-confirmation/
Failure Page: https://redacted/order-failed/
Donation History Page: https://redacted/order-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - AWeber: ❌ Unlicensed – by WordImpress – 1.0.3

### Other Active Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.2
Really Simple SSL: by Rogier Lankhorst, Mark Wolters – 3.0.5
Thrive Architect: by Thrive Themes – 2.0.52

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.8
Give - Form Field Manager: by WordImpress – 1.3
Hello Dolly: by Matt Mullenweg – 1.7

### Theme ###

Name: Astra
Version: 1.5.1
Author URL: http://wpastra.com/about/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by kevinwhoffman** [comment]
Closing. Customer reports that Thrive fixed the issue.
