### ISSUE TITLE
fix: prevent notice when bulk deleting donors

### ISSUE THREAD

**Issue by nishitlangaliya** [impress-org/give#3729]
# Bug Report

## User Story

As a `admin`  I want to perform bulk delete Donors without any notices

## Current Behavior
- While performing bulk delete actions for donors it shows `Notice: Undefined index: ID `

## Expected Behavior
 I should be able to bulk delete donors without any notices or error in admin section.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [X] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Go to 'yoursite'/ wp-admin/edit.php?post_type=give_forms&page=give-donors
2. Select one or more donors from list.
3. Perform bulk delete action

## Visuals

https://www.useloom.com/share/7868da7707cf4c868b77c3fd873c31c1

## Acceptance Criteria
- [ ] Make sure `Notice: Undefined index: ID` do not come when perform bulk delete for donors

**Comment by kevinwhoffman** [comment]
@nishitlangaliya I was able to confirm the issue as described in your video. I've mode this to top of your sprint backlog so we can try to resolve this before Give v2.2.6 releases.
