### ISSUE TITLE
Donor wall will not show comments when specifying form id

### ISSUE THREAD

**Issue by apricejr1** [impress-org/give#3731]
Even when using the Give shortcode generator for the donor wall, if you select the donor form from which to pull data for the donor wall (name, amount, date, comment, etc.) it will not show comments. The only time comments are displayed is when you do not select a donor form. We have a fundraiser starting in a couple of days and need this functionality to work. Happy to pay for priority support if it means the donor wall works.

**Comment by mathetos** [comment]
Hi @apricejr1 -- this is related to this larger issue which you can follow here:
https://github.com/impress-org/give/issues/3623#issuecomment-415109775

You can see that we already have a fix in place for the next version of Give. 

Thanks for reporting this.
