### ISSUE TITLE
feat: run database upgrade on rest api instead of admin-ajax.php

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3735]
## User Story
As an admin, I want to run the database upgrade with any issue.

Run database update on `admin-ajax.php` is not safe because few servers restrict `admin-ajax`.php access which cause of stalled database upgrade process.

## Possible Solution
Run databse updates on rest API.

## Acceptance Criteria
- [ ] Register new public rest API endpoint `bg-process` which we will use in future for processing any task in the background.
- [ ] Tweak existing JS and PHP code for background database updater to run an update on rest API

**Comment by kevinwhoffman** [comment]
Closing per team discussion. We will stick with admin-ajax for now.
