### ISSUE TITLE
fix: prevent nonce verification error during login

### ISSUE THREAD

**Issue by kakshak** [impress-org/give#3740]
# Bug Report

## User Story
As a user, I don't want to display `Nonce verification has failed` message if I am entering the correct login details so that `user does not get confused regarding login`.

## Current Behavior
I currently entering the correct user details from Give donation form but it displays `Nonce verification has failed`.

## Expected Behavior
That message should not display if a user entering the correct details.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. View any donation form to front-side
2. Enter correct user details
3. Nonce verification has failed message is displayed

## Visuals
https://www.useloom.com/share/ce210f5175484676bbd46dd7427059a2

## Acceptance Criteria
- [x] If the user enters correct details, the Nonce message should not display into form
- [x] Testing that functionality

## Environment
<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Microsoft Windows</li>
        <li>Version: 10</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: 69.0.3497.100</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>

WordPress Information
--
Home URL: | http://givetest.local
Site URL: | http://givetest.local
WP Version: | 4.9.8
WP Multisite: | –
WP Memory Limit: | 256 MB
WP Debug Mode: | Yes
WP Cron: | Yes
Language: | en_US
Upload Directory Location: | http://givetest.local/wp-content/uploads
Server Information
Server Info: | Apache/2.4.10 (Debian)
Server IP Address: | 172.17.0.5
Server Protocol: | c7952525b6dc
Server Administrator: | webmaster@localhost
Server Web Port: | 80
CGI Version: | CGI/1.1
PHP Version: | 5.3.29 - Recommend PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: | 1,000 MB
PHP Time Limit: | 900
PHP Max Input Vars: | 3000
GD Library: | Yes, version: bundled (2.1.0 compatible)
cURL Version: | 7.38.0, OpenSSL/1.0.2h
SUHOSIN Installed: | –
MySQL Version: | 5.6.34
Max Upload Size: | 1,000 MB
Default Timezone is UTC: | Yes
PHP Error Log File Location: | /app/public/wp-content/debug.log
fsockopen/cURL: | Yes
SoapClient: | Yes
DOMDocument: | Yes
GZip: | Yes
Multibyte String: | Yes
Remote Get Status: | Yes
Current Theme
Name: | Twenty Seventeen
Version: | 1.7
Author URL: | https://wordpress.org/
Child Theme: | No. If you're want to modifying a theme, it safe to create a child theme. See: How to create a child theme
Active Plugins (2)
Give - Donation Plugin | WordImpress 2.3.0
WP System Info | Nurul Amin 1.2

</details>

**Comment by kevinwhoffman** [comment]
@mehul0810 Please try to replicate and confirm the bug. If the nonce error is occurring in latest 2.3.0 branch, please explain why and take steps to resolve.

**Comment by DevinWalker** [comment]
I've replicated and can confirm the bug.
