### ISSUE TITLE
fix: correct default behavior of donor wall

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#3744]
# Bug Report

## User Story

As a Give admin, I want the donor wall to display one block per donation with a comment (if available) so that each donation is accurately reflected on the donor wall.

## Current Behavior

See the video of my donor wall test in the latest `release/2.3.0` branch. There are two major issues:

1. Multiple donations from the same donor are currently being combined into one block. For example, if someone donates $1 and then makes another $1 donation to the same form, they only appear once in the donor wall with a combined total of $2. This is not the expected behavior.
2. Donor comments are currently not displaying at all. It does not matter if `form_id` is provided in the shortcode or not. I can't seem to get any comments to display on the wall.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Create a form with Donor Comments enabled.
2. Create several donations with comments. Be sure to donate more than once with the same email address.
3. Embed a `[give_donor_wall]` shortcode on a page. Note that all donations from the same donor are combined into one block on the donor wall. Also note comments do not display at all.

## Visuals

https://www.useloom.com/share/f21b5141a07140738113dd450d83bcc2

## Related

- A user reported the same behavior in the .org support forums: https://wordpress.org/support/topic/individual-separate-donations-are-combined/
- https://github.com/impress-org/give/issues/3623

## Acceptance Criteria

- [x] A donation with comment created in Give 2.2.5 displays correctly on the donor wall in Give 2.3.0. This ensures that existing comments added before 2.3.0 will display after the plugin update.
- [x] The following criteria are true in Give 2.3.0 both before _and_ after the database upgrade that migrates comments to a custom table. This ensures that comments added before the db upgrade display, as well as those added after.
- [x] Each individual donation appears as its own block in the donor wall.
- [x] If the same donor donates twice to the same form, two blocks appear on the donor wall.
- [x] If a donor comment exists for the donation, it is displayed in the donor wall unless the shortcode attribute explicitly disables comments.
- [x] Each option in the Donor Wall shortcode generator has been tested to ensure the front-end appearance matches the selected options.
- [ ] All of the above criteria hold true when the donor wall is used in a multisite install.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
        <li>Version: 10.10.5</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: 69.0.3497.100</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
### WordPress Environment ###

Home URL: http://tempgive230.test
Site URL: http://tempgive230.test
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: tempgive230.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.13.9
PHP Version: 7.2.2
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 128 MB
cURL Version: 7.43.0, SecureTransport
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://tempgive230.test/donation-confirmation/
Failure Page: http://tempgive230.test/donation-failed/
Donation History Page: http://tempgive230.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Other Active Plugins ###

Simply Show Hooks: by Stuart O'Brien, cxThemes – 1.2.1
Transients Manager: by Pippin Williamson – 1.7.5
User Switching: by John Blackbourn & contributors – 1.4.0

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@kevinwhoffman can we discuss about recurring addon also, like how donor wall will behave for recurring payments ( Main payment  subscription and renewals )

**Comment by ravinderk** [comment]
Slack Chat Summary

Participants: @DevinWalker, @kevinwhoffman , @ravinderk 
Link: https://givewp.slack.com/archives/C0FAGC83C/p1539153128000100
Topic: How donor wall will work with recurring payments
Result: As per discussion we will only show parent subscription payments on donor wall and  we will not renewals on the donor wall.
