### ISSUE TITLE
feat: load donor wall gravatars after page load

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3758]
# Feature Request

## User Story
As a site owner, I want to donor wall shortcode but this shortcode has performance issue because it loads donor gravatar before the page load.

To improve performance we can load gravatar after page load if shortcode attribute `avatar` set to `true`.

Ref: for more information read `Suggestion` section in Pr description: https://github.com/impress-org/give/pull/3752

## Acceptance Criteria
- [x] Output donor name initials by default.
- [x] Use `data` attribute to store `avatar` shortcode attribute value.
- [x] If `avatar` set to `true` load gravatar with `https://www.npmjs.com/package/gravatar-api` js library.

**Comment by nishitlangaliya** [comment]
## Slack Call Summary

Participants: @ravinderk , @nishitlangaliya 
Topic: Discussion on how to load donor wall gravatars after page load
Result: I had a confusion how to proceed with load gravatars after page load. @ravinderk guide me to proceed and as per suggestion, I am moving forward with it.
