### ISSUE TITLE
feat: add user_role to give_register shortcode

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3767]
# Feature Request

## User Story

As a Give Admin, I want to use the `give_register` shortcode and designate what user Role should be given to any user that registers via that form. 

## Possible Solution
Ideally, the shortcode would have a new argument: `user_roles`

Here's how it would work:
* If empty, the users would just get the WordPress default user role
* If there is ONE user role name inserted then all users would get that user role automatically
* If there are multiple user roles listed in that argument (comma separated), then in the register form a select field would be output to allow the user to choose from the available users roles.

## Acceptance Criteria

- [ ] The argument is added to the shortcode function
- [ ] If the argument is empty the WordPress default User Role would be applied to the user automatically (which is the current functionality)
- [ ] If one user role is present, that user role would get applied to the user automatically instead of the default WordPress user role
- [ ] If multiple user roles are present in the argument, a select field would appear in the register form for the user to choose from.
- [ ] When the user registers and the User role select field is present and they choose any option, that user role is always applied to that user correctly as intended.

**Comment by kevinwhoffman** [comment]
I understand the _who_ and _what_, but I'm missing the _why_ from the user story.

I agree it would be helpful to define the user role in the shortcode so that an admin can grant certain capabilities to registrants.

I am less convinced of the payoff in implementing a front-end UI for selecting from multiple roles. This front-end element increases complexity and dev time, so we need to better understand why it's important.

**Comment by kevinwhoffman** [comment]
Discussed with @DevinWalker and we felt like this functionality goes best with peer-to-peer. Moving to the new repo.

**Comment by kevinwhoffman** [comment]
Issue moved to [impress-org/give-peer-to-peer #2](https://github.com/impress-org/give-peer-to-peer/issues/2) via [**ZenHub**](https://www.zenhub.com/)
