### ISSUE TITLE
fix: pass donor comment content to Akismet api request when doing spam validation

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3768]
# Bug Report

## User Story
As an admin, I want also want donor comment to validate.

## Current Behavior
We are not passing donor comment content to Akismet API request: https://github.com/impress-org/give/blob/702b1223e3007d16dacca019df1f9888e48c3c9f/includes/filters.php#L83,

but in Akismet API documentation we can see that `comment_content` is a valid request param: https://akismet.com/development/api/#comment-check.

## Expected Behavior
Need to validate donor comment too.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria
- [x] Pass `$_POST['give_comment']` as `comment_content` for spam validation if donor comment active for that specific form.
- [x] Review why we are passing each value of `$_SERVER` to Akismet API request, because I did not see that in sample code: https://akismet.com/development/api/#comment-check.

**Comment by jaydeeprami** [comment]
@ravinderk 

Regarding this,

>  Review why we are passing each value of $_SERVER to Akismet API request, because I did not see that in sample code: https://akismet.com/development/api/#comment-check.

As per Akismet documentation, We should have to pass each value of  $_SERVER to Akismet API request. As these data are highly useful to Akismet. 

Please check section `Other server environmental variables ` in https://akismet.com/development/api/#comment-check API documentation.
