### ISSUE TITLE
fix: improve donor note email template

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#3776]
# Bug Report

## User Story

As an admin I want correspondence to my donors to be similar to other emails they receive. The "Donor Note" title should also be updated to be something more helpful for the donor to understand.

## Current Behavior

The email not currently differs from others sent and is sloppily written.

## Bug Type

- [x] This describes new functionality that doesn't work as expected pre-release.

## Visuals

![2018-10-16_20-22-25](https://user-images.githubusercontent.com/1571635/47060321-04b93380-d182-11e8-93cc-a0f554a26da6.png)

## Possible Solution

The default email header should be:

> New Donation Note Added

The email template should be:

> Dear {name},
> 
> A note has just been added to your donation:
> 
> {donor_note}
> 
> For your reference, you may may view your donation details by clicking the link below:
> {receipt_link}
> 
> Thank you,
> 
> {sitename}
> 

## Acceptance Criteria

- [x] I can view the donor note email and see a correctly written heading and email template

**Comment by kevinwhoffman** [comment]
@kakshak Please bump this to the top of your list since it is regarding donor note functionality added in 2.3.0 and we're looking to release this week.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak , @ravinderk 
Topic: Discussion on `{donor_note}` template tags  
Result: I've confusion regarding `{donor_note}` template tags and that is resolved.
