### ISSUE TITLE
feat: add gravatar support to the admin donors screens

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#3777]
# Feature Request

## User Story

As an admin I want to see the gravatars of my donors so that I can more easily distinguish them and interact with a better visual appearance on the donor screens.

## Visuals

**Donor Listing Screen**

![donor listing screen](https://user-images.githubusercontent.com/1571635/47061403-29170f00-d186-11e8-9abc-e6df48185768.jpg)

**Single Donor Detail View**

![2018-10-16_20-57-24](https://user-images.githubusercontent.com/1571635/47061406-2caa9600-d186-11e8-8361-b0d3791caa72.png)

## Acceptance Criteria

- [x] Avatars load asynchronously on the donor listing page as to not slow down page load speed
- [x] Avatars load normally on donor details screen
- [x] Donors without avatars list donor's initials like the donor wall
- [x] Avatars are clickable to go to the donor details screen on the donor listing screen
- [x] There are not tooltips for the donor avatar element
- [x] Donor avatars are circular on both screens
- [x] The font used by the donor's initials for non-gravatars should be default WP installs font.

**Comment by ravinderk** [comment]
@DevinWalker I think, it will be helpful if we will add the donor avatars on the donation list also.
