### ISSUE TITLE
fix: remove `Anonymous Donor` field from donor details

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#3781]
# Bug Report

## User Story

As a Give admin, I want to remove the `Anonymous Donor` field from the Donor details screen so that it does not cause confusion between the idea of an anonymous donor and an anonymous donation.

### This functionality is being used:
In `Give v2.3.0` an anonymous donation is denoted by the presence of a donation meta key where `_give_anonymous_donation` === `1`. This key determines whether the donation is displayed in the donor wall and works as intended.

### This functionality is not being used:
In addition, donor meta keys are also added that don't seem to be serving any purpose and do not accurately reflect whether the donor has made an anonymous donation:

- `_give_anonymous_donor_form_8` where `8` is the form ID.
- `_give_anonymous_donor`

I think this is a leftover effect from when donations were being combined on the donor wall, but we have since decided to display all donations individually based on anonymity per donation.

## Expected Behavior

I expect to only store an anonymous key in donation meta, but not donor meta. The donor meta keys should not be added when a donation occurs and the `Anonymous Donor` field should be removed from the Donor details screen.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. In `Give v2.3.0`, create a form with comments and anonymous checkbox enabled.
2. Enter a comment and check anonymous before submitting donation.
3. Visit donor details screen to reveal that `Anonymous Donor: No` is visible even though the individual donation was anonymous.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/47106479-a4bf9d00-d214-11e8-9068-64ea40b302a9.png)

## Acceptance Criteria

- [x] The `Anonymous Donor` field is removed from the Donor details screen in WP admin.
- [x] When a donation form with anonymous checkbox is submitted, the value of the checkbox is stored as donation meta with a key of  `_give_anonymous_donation` and value of `1` or `0`.
- [x] No keys are added to the donor meta regarding anonymous donations since we already have that covered in donation meta.

**Comment by kevinwhoffman** [comment]
@ravinderk Please confirm that the donor meta fields are no longer necessary in order to handle anonymous donations. If they are not necessary, please remove that field in Donor details screen and prevent those keys from being stored in the future.

**Comment by ravinderk** [comment]
@kevinwhoffman Yes, they are not useful and I will create Pr to remove them
