### ISSUE TITLE
feat: add style to standout anonymous donation in donation list

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3783]
# Feature Request

## User Story
As an admin, I want something which will help me to quickly identify anonymous donation in the list.

![image](https://user-images.githubusercontent.com/1784821/47145645-d0f81e00-d2e7-11e8-9c6a-60e022f6a8d4.png)

## Acceptance Criteria
- [ ] Create a class for approved color for anonymous donation
- [ ] Add color class to donation row in the list.

**Comment by kevinwhoffman** [comment]
@ravinderk Please provide the _why_ part of the user story. Why would this be useful for an admin? I can see why it would be helpful in development, but we need to make sure new features serve the end users.

If implemented, I would advise against coloring the background row as yellow could signal "caution" or a problem with the processing of the donation.

**Comment by ravinderk** [comment]
@kevinwhoffman I create this issue because it was not easy for me to know that donation is anonymous or not till I do not open donation detail. But I most of the user does not need this at this point to point, so closing this issue.
