### ISSUE TITLE
fix: ensure compatibility with Give and Intelligence plugin

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3787]
# Bug Report

## User Story

As a site admin, I want Give to be compatible with the Intelligence plugin so that I can use it as an analytics tracking solution on my site.

We use the Intelligence plugin in combination with other functionality on our site, which is very important for us.

## Current Behavior
Upon submission of a donation, I'm presented with a fatal PHP error. 

## Expected Behavior
I want to use both plugins on my site without incompatibilities or errors.

## Bug Type
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Download and activate the plugin from the provided link.
2. Submit a donation through Give.
3. See the fatal error that is displayed

Password protected download link:
https://drive.google.com/file/d/1kpk48YXcjFO1uOYZGgYGMiG4XzuiBHkB/view?usp=sharing

## Visuals

![screen shot 2018-10-19 at 8 50 18 am](https://user-images.githubusercontent.com/20672471/47219567-292d2f80-d37d-11e8-98f4-19c36fed8d74.png)

## Related
https://secure.helpscout.net/conversation/687468831/27486

Link to the plugin website:
https://intelligencewp.com/

## Acceptance Criteria

- [ ] Both plugins are activated and Give submits donations without issue.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report✔Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.3
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.3
Give - Braintree Gateway: ✔ Licensed – by WordImpress – 1.2.2
Give - CCAvenue Gateway: ✔ Licensed – by WordImpress – 1.0.2
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Gift Aid: ❌ Unlicensed – by WordImpress – 1.1.6
Give - MailChimp: ✔ Licensed – by WordImpress – 1.4.1
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0.1
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.2.0
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0

### Other Active Plugins ###

Give - Fee Recovery: by GiveWP – 1.7.2
Give - Form Field Manager: by GiveWP – 1.4.0
Give - Google Analytics Donation Tracking: by GiveWP – 1.2.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - PayPal Pro Gateway: by GiveWP – 1.2.0
Give - Recurring Donations: by GiveWP – 1.8.1
Give - Stripe Gateway: by GiveWP – 2.1.1
Intelligence: by LevelTen – 1.3.1
Sam's Helper Function: by WordImpress – 1.0

### Inactive Plugins ###

All-in-One WP Migration: by ServMask – 6.73
Contact Form 7: by Takayuki Miyoshi – 5.0.4
Give - Donation Upsells for WooCommerce: by WordImpress – 1.0.3
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
User Role Editor: by Vladimir Garagulya – 4.44
WooCommerce: by Automattic – 3.4.5
WordPress Importer: by wordpressdotorg – 0.6.4
WP Business Reviews: by Impress.org – 1.0.0

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by DevinWalker** [comment]
This is resolved in `release/2.3.0` with the move from WP Comments to our own custom comments table.
