### ISSUE TITLE
feat: provide option that controls the order of forms in the form grid

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3792]
# Feature Request

## User Story

As a site admin, I want to have the option to change the order the forms display in the form grid, so if I have many of them displayed on one page the donors are able to consistently sort through them.

## Possible Solution
Add two new fields to the shortcode builder:

- `Order By` : `order_by`
    - `Date Created` : `date` (based on date created)
    - `Form Name` : `name` (based on first letter of form name)
    - `Amount Donated` : `amount_donated` (based on `_give_form_earnings` form meta key)
    - `Number of Donations` : `number_donations` (based on `_give_form_sales` form meta key)
    - `Menu Order` : `menu_order` (based on WordPress menu order)
    - `Provided Form IDs` : `post__in` (based on provided form IDs in the field above)
- `Order` : `order`
    - `Descending` : `DESC`
    - `Ascending` : `ASC`

## Visuals

Two new fields `Order` and `Order By` will be added as shown below:
![image](https://user-images.githubusercontent.com/1938671/47413166-948b4e80-d73b-11e8-838a-eb2eabd24029.png)

## Related
https://secure.helpscout.net/conversation/691090425/27745

## Acceptance Criteria

- [x] The fields and values described under Possible Solution have been added to the shortcode builder.
- [x] The front-end form grid reflects the order selected in the shortcode builder.

**Comment by kevinwhoffman** [comment]
@kakshak Let's schedule a call later this week to define the acceptance criteria before you begin.

**Comment by samsmith89** [comment]
@kevinwhoffman Let me know if it's too late for this issue, but I just had another request today to have the option to order forms by when they expire or forms that are closest to reaching their goal.

If you would like me to create another issue I can, or if this falls outside of the scope and they should reach out to third-party development.

**Comment by kevinwhoffman** [comment]
@samsmith89 Create a new issue as this one has merged and closed. I looked into ordering by "closest to goal" before and I'm not sure it's possible because we do not store goal progress on its own. You can make the feature request and we'll look into it further.
