### ISSUE TITLE
fix: improve production script

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#3803]
# Bug Report

## User Story

As a developer, I want `npm run production` to run smoothly without deleted TCPDF fonts in the Git staging area so that we don't accidentally commit these changes.

## Current Behavior

When I run `npm run production`, the Git staging area becomes littered with TCPDF fonts that are not used in production.

This happens because TCPDF files are removed via webpack as part of the production script:
https://github.com/impress-org/give/blob/cc2f428cb82cb1b6598694d49b9098d3ca933496/webpack.config.js#L177-L178

## Expected Behavior

These files should not be deleted until the plugin is being packaged for distribution.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.2.5.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Run `npm run production`.
2. Run `git status` to view the deleted TCPDF fonts.

## Visuals

Git staging area after `npm run production` is completed.
![image](https://user-images.githubusercontent.com/1938671/47411155-e0d39000-d735-11e8-8a76-7e0f611c1ef6.png)

## Possible Solution

Possibly move the deletion of these files to the shell script that bundles the plugin prior to release.

https://github.com/impress-org/give/blob/cc2f428cb82cb1b6598694d49b9098d3ca933496/webpack.config.js#L177-L178

## Acceptance Criteria

- [x] When `npm run production` is complete, the Git staging area is clear.
- [x] The TCPDF files are removed through some other means prior to release.
- [x] Necessary `vendor` files are included in the bundled plugin prior to release.

**Comment by DevinWalker** [comment]
Resolved in commit above.
