### ISSUE TITLE
fix: improve donations search

### ISSUE THREAD

**Issue by nishitlangaliya** [impress-org/give#3806]
# Bug Report

## User Story

As a `admin`, I want result based on input given in search box in donations list.

## Current Behavior
Currently no result founds against the string

## Expected Behavior
It should search result based on string given like firstname, lastname or string like

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [X] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Go to admin -> Donations list
2.  Try to search any string in search inputbox

## Visuals

https://www.useloom.com/share/52e5c89fd91d4c9ebb90606ffa3fe9a7

## Acceptance Criteria
- [ ] Make sure search box gives proper result based on any string
- [ ] Make sure it works with combination of other filters

**Comment by kevinwhoffman** [comment]
@nishitlangaliya I confirmed I am not getting any results from this search bar either. @DevinWalker and I will discuss and provide further direction for acceptance criteria.

**Comment by kevinwhoffman** [comment]
@nishitlangaliya As we discussed on the team call, the donation search should work the same as the donor search. It should accept `Name, Email, or Donation ID`. If you are handling this behavior in another PR, just make sure you close this issue as part of it.

**Comment by nishitlangaliya** [comment]
@kevinwhoffman , Closing this issue in favor of https://github.com/impress-org/give/pull/3808.
