### ISSUE TITLE
feat: give option to export donation totals on per-form basis

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3811]
# Feature Request

## User Story

As a site admin, I want to have an option to export the totals of each form in the "Export Income and Donation Stats" section, so that I can easily show how each form is performing without having to do the math from an export of all the donations.

## Visuals
![screen_shot_2018-10-29_at_3_21_09_pm](https://user-images.githubusercontent.com/20672471/47674811-8f406080-db8e-11e8-8a58-9a323414a390.png)

## Possible Solution
Possibly having a checkbox for a breakdown per-form or something of that nature. I'm not claiming to know the best way to integrate this though.

## Related

https://secure.helpscout.net/conversation/695238849/28115

## Acceptance Criteria

- [ ] There is an option somewhere in the backend that allows me to export a report of totals based on each form.

**Comment by kevinwhoffman** [comment]
Discussed with @DevinWalker, closing as it should be possible to calculate form totals with the current export + a formula in Google Sheets/Excel. We'll look into more robust options in the reports revamp.
