### ISSUE TITLE
fix: ensure Give blocks are compatible with latest Gutenberg

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3813]
# Bug Report

## User Story
As an admin, I want to ensure that Give blocks will work fine with WordPress future release with Gutenberg editor so that I can use Give blocks to create pages.

ref: https://github.com/impress-org/give/issues/3697

## Current Behavior
Give blocks are not working fine with WP 5.0 Beta.

## Expected Behavior
Give blocks must work fine with WP 5.0 Beta or above.

## Bug Type

- [X] This bug describes functionality that once worked as expected before 5.0 > WP.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install latest WP version: https://wordpress.org/news/2018/10/wordpress-5-0-beta-1/
2. Create a new page
3. Use any of Give block. You will get an error in the browser inspector tool's console tab.

## Visuals
![image](https://user-images.githubusercontent.com/1784821/47696198-ada86980-dc2b-11e8-9e89-31036bdb1d50.png)

## Acceptance Criteria
- [x] Refresh React concepts.
- [x] Review Gutenberg API https://wordpress.org/gutenberg/handbook/.
- [x] Fix broken Give blocks.
  - [x] Donation Form block
  - [x] Donor Wall block
  - [x] Form Grid block
- [ ] Review settings available for editing on block setting panel for all blocks and add if anyone missing
  - [ ] Donation Form block
  - [x] Donor Wall block
  - [x] Form Grid block

**Comment by ravinderk** [comment]
@kevinwhoffman @DevinWalker I worked on this issue and now blocks are working with WP 5.0.0 Beta but I am facing one issue. Gutenberg API somewhere caches API results before render and it will not rerender block if past query repeat. I check for a solution but did not find.

I know somewhere maybe we need to bypass this function or manually call cache deletion function: https://github.com/WordPress/gutenberg/blob/aec940810eaa73e9fe54c2a0e3dd591634158aa5/packages/data/src/resolvers-cache-middleware.js#L25

I will reach out to gutenberg pro developers and let know about it.

**Comment by ravinderk** [comment]
@kevinwhoffman or @DevinWalker can you take care of styling issues: https://github.com/impress-org/give/pull/3827#issuecomment-435811205

**Comment by kevinwhoffman** [comment]
I'll create a new issue to resolve block styling issues. Leave this open for now.

**Comment by kevinwhoffman** [comment]
Closing. Remaining block issues for WP 5.0 will be resolved in #3887.
