### ISSUE TITLE
fix: improve language on multiple payment gateway add-ons.

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#3814]
# Bug Report

## User Story
As a give user, I want the language to be clear and understandable for labels 

## Current Behavior
Currently the language is not clear, and has improper grammar for the following add-ons:

Gocardless
Iats
Paytm
CCavenue
Razorpay
PayuMoney

...and potential others. 

## Expected Behavior
I expect the language to be more clear.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Open any of the payment gateways listed above in Donations > Settings > Payment Gateways (tab)
2. See the language for the front end label.

## Visuals
![screen shot 2018-10-29 at 5 44 51 pm](https://user-images.githubusercontent.com/9629102/47717204-82b61980-dc1b-11e8-92a1-184f3fd46f2a.png)

## Possible Solution
The string for each one of those should be 
> This label appears on the front end of the donation form.

## Acceptance Criteria
- [x] the string `will be appear` does not show up in any of the repos https://github.com/search?q=org%3Aimpress-org+%22will+be+appear%22&type=Code

**Comment by kevinwhoffman** [comment]
@nishitlangaliya This will require separate PRs for each of the affected add-ons mentioned above. Please update with the following string:

> This label appears on the front end of the form.

**Comment by DevinWalker** [comment]
This string isn't displayed anywhere, but it has been resolved in case in the future we may need to use it.
