### ISSUE TITLE
feat: improve ordering of donor wall

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#3816]
# Feature Request

## User Story

As a user, I want more control over the `order` and `orderby` parameters of the donor wall so that I can display donors in the order I want.

From the user:

> I was thinking we’d be able to do a [ give_donor_wall form_id=”1234″ donors_per_page=”5″ orderby=”total” ] to do like a “Wall of Fame” for our best donors.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/47741515-dbec7000-dc50-11e8-80bc-7c09fd660c47.png)

## Possible Solution

**Add the following fields to the shortcode builder:**

`Order`
- `Descending` : `DESC` (default)
- `Ascending` : `ASC`

`Order by`
- `Date` : `date` (default)
- `Donation Amount` : `donation_amount`

**Possibly filter the following values:**

https://github.com/impress-org/give/blob/83aa79a3b33a90a8c13719ec22c65ed0621c306c/includes/donors/class-give-donor-wall.php#L301

https://github.com/impress-org/give/blob/83aa79a3b33a90a8c13719ec22c65ed0621c306c/includes/donors/class-give-donor-wall.php#L414

## Related

https://wordpress.org/support/topic/orderby-in-donor_wall/

## Acceptance Criteria

- [x] An `Order` field is available in the shortcode builder which defines the `order` parameter.
- [x] An `Order by` field is available in the shortocde builder which defines the `orderby` parameter.
- [x] Ordering by `date` causes donors to be displayed chronologically.
- [x] Ordering by `donation_amount` causes donors to be ordered based on the size of each individual donation.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak , @mehul0810  
Topic: Discussion about query regarding `Donation Amount`
Result: I am confused at the query and I have a conversion with Mehul that how to resolve that using custom query but We need to figure out a way that how we can modify that in a simplified way. So, I am looking over it right now and if I required help then I'll make a conversation with Mehul.

**Comment by ravinderk** [comment]
@kevinwhoffman I found that `Order By` setting is missing from Gutenberg block, so I am working on fix.

![image](https://user-images.githubusercontent.com/1784821/51176418-dcf17d00-18e2-11e9-917a-4f6f3aa32a4c.png)

**Comment by ravinderk** [comment]
Issue has been fixed in https://github.com/impress-org/give/compare/a768249be35b...f16fc4c4d188
