### ISSUE TITLE
fix: improve organization of emails table

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#3817]
# Bug Report

## User Story

As a user, I want a clear understanding of the intended audience for each email so that I can easily distinguish between donor and admin emails.

## Current Behavior

All emails exist in the same table, and some emails are essentially the same email with different audiences. The only way to know the purpose of the email is to infer it from the list of email addresses in the Recipients column.

## Expected Behavior

I expect to look at the list of emails and immediately know which emails are sent to donors and which are sent to admins.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. View Donations > Settings > Emails tab.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/47765083-a1112900-dc9e-11e8-8d00-dcb0364edde3.png)

## Possible Solution

Split the list of emails into two tables labeled `Admin Notifications` and `Donor Notifications`. These tables would be stacked vertically in the Emails tab using the existing table format, but split into two separate tables for clarity.

We should also consider reviewing the names of each email to see if we can establish a consistent naming convention.

## Acceptance Criteria

- [x] Settings > Emails has been updated from 2 tabs to 4 tabs: Email Settings, Donor Emails, Admin Emails, Contact Information
- [x] The Email Settings tab only includes fields currently listed as Email Sender Options.
- [x] The Donor Emails tab includes a table of donor emails only.
- [x] The Admin Emails tab includes a table of admin emails only.
- [x] All add-ons that populate these tables with emails have been updated to ensure donor and admin emails are added to the correct table.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak @ravinderk 
Topic: Discussion about Acceptance Criteria `The affected add-ons have had their minimum Give core version updated to match the version in which this change is implemented.`  
Result: I've discussed with Ravinder that Add-on doesn't require to have had a minimum version of Give core because by default it falls into an appropriate email address. It doesn't break any functionality but if @kevinwhoffman still wants to add that then please let me know about it.

**Comment by kevinwhoffman** [comment]
@kakshak If the add-ons do not need a minimum version declared, then I will remove the acceptance criteria for that. Let me know if the PR is otherwise ready to review.
