### ISSUE TITLE
feat: show all donations in donor wall and use "Anonymous" as the name for anon donors

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3826]
# Feature Request

## User Story

As a NGO using Give, I want to use the donor wall feature, but I want that all the donations appear and use the word "Anonymous Donor" when donors opt to be anonymous.

1/ if we have 10 donors listed on the wall, and their donations add up to $1000, but our Amount Raised shows $1500, that just looks weird. Like maybe we are fudging numbers.

2/ More importantly, if we have anonymous donors, at least we *have* donors, and other potential donors should see that donors *are* participating in the campaign. This creates a ‘call to action’ and ‘safety in numbers’ that helps others to decide to participate in an ‘active’ campaign as well.

It would be nice to (maybe optionally) list Anonymous Donors (anonymously, of course) 🙂 as an entry on the Donor Wall.

## Possible Solution
This could be supported as an additional shortcode argument, like `show_anonymous_donors=true|false`

We might additionally consider another argument called `show_anonmous_comments=true|false` This would only apply if the first argument was true.

## Related

* [original user request](https://wordpress.org/support/topic/anonymous-donor-display/)

## Acceptance Criteria

- [x] Anonymous donations appear in the donor wall by default.
- [x] Anonymous donations display the following fields:
    - [x] Amount
    - [x] `Anonymous` as the name
    - [x] Date
    - [x] A generic [user avatar](https://fontawesome.com/icons/user-circle?style=solid)
- [x] Comments for anonymous donations are never displayed under any condition.
- [x] A new shortcode parameter `anonymous` is available to determine the visibility of anonymous donations within the donor wall.
- [x] If `anonymous` is `true` (default), then anonymous donations are included.
- [x] If `anonymous` is `false`, then anonymous donations are excluded.
- [x] The shortcode builder displays the `Anonymous` field with values:
    - [x] `Show` : `true`
    - [x] `Hide` : `false`
- [x] The tooltip of the `Anonymous` field in the shortcode builder reads `Determines whether anonymous donations are included.`
- [x] The label of the front-end anonymous checkbox reads: `Hide name and comment from everyone but the administrator.`
- [x] The tooltip of the front-end anonymous checkbox reads: `Would you like your donation to be displayed from an anonymous source?`
- [x] Add `anonymous` attribute setting to Donor Wall Gutenberg block.
- [x] Hide anonymous donation if `only_comments` set to `true`. ignore `anonymous` attribute value.

**Comment by kevinwhoffman** [comment]
@kakshak We need to discuss with team how to handle display of anonymous donors. Acceptance criteria may change.

**Comment by kevinwhoffman** [comment]
On the team call we discussed displaying anonymous donations in the donor wall by default. This means if the donation was marked anonymous, then it would display:

- Amount
- `Anonymous` as the name
- A generic avatar

This is in line with other platforms such as GoFundMe.

We decided that anonymous comments should not be displayed for privacy purposes. However, mixing anonymous donations without comments and other donations with comments will likely result in a lot of awkward white space in a grid format. In a three-column grid, one comment will stretch the height of the row while anonymous donations will have nothing to fill that space.

This needs further discussion before defining the default behavior.

@mathetos What do you think about displaying anonymous donations by default and concerns over its effect on presentation?

**Comment by mathetos** [comment]
We've had feedback already that the Donor Wall presentation is already lackluster. It might be worth a bit of a UI redesign anyway, and that would make this task far easier.

I think the value to ORGS using Donor Wall to show Anonymous donations without names/faces/comments is the primary concern or goal here. I believe we can get that done and a new design that we're proud of.

**Comment by kevinwhoffman** [comment]
## Slack Chat Summary

Participants: @kevinwhoffman @DevinWalker @mathetos 
Topic: Anonymous behavior
Result: We agree to display anonymous donations by default with an attribute to exclude anonymous donations from the wall if desired. We also agree to not allow the possibility of displaying comments for anonymous donations. Finally the tooltip and description around the anonymous UI needs reviewed for clarity. New acceptance criteria will follow.

**Comment by kakshak** [comment]
@kevinwhoffman I need to discuss regarding functionality for this and acceptance criteria regarding that. Let me know when you're available. So, we can discuss this.

**Comment by kevinwhoffman** [comment]
@kakshak See acceptance criteria as we need to clarify the front-end label and tooltip for the anonymous checkbox.

![image](https://user-images.githubusercontent.com/1938671/48824031-02be3380-ed31-11e8-9691-e41fe74c9556.png)

**Comment by mathetos** [comment]
@kevinwhoffman If there's an issue on improving Donor Wall appearance, let's make sure we're not using `!important` everywhere in the donor wall as well:
![image](https://user-images.githubusercontent.com/930724/48872544-603c9980-ed9e-11e8-9818-085d7580cc07.png)

**Comment by mathetos** [comment]
Most likely it would also be better to sort the donors with comments to be first as well, for symmetry:

![image](https://user-images.githubusercontent.com/930724/48872704-33d54d00-ed9f-11e8-8f68-cd7941cfd7cd.png)

**Comment by ravinderk** [comment]
@kevinwhoffmanI updated **Acceptance Criteria**.

![image](https://user-images.githubusercontent.com/1784821/49008743-a3c74700-f194-11e8-9a17-3e8060de253f.png)
