### ISSUE TITLE
fix: resolve incompatibility with WPML String Translation plugin

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3828]
# Bug Report

## User Story

As a site admin, I want to be able to make settings changes and save them in the backend of Give so that I can make necessary changes to the plugin.

## Current Behavior
Currently, with WPML String Translation installed with the WPML Multilingual CMS main plugin, setting changes aren't being saved in the backend of Give. I'm on the latest version of each plugin, and when the page refreshes the settings don't take effect and aren't saved. 

It takes multiple saves and page reloads for the settings to take effect. I need to disable the WPML plugin, make a setting change in Give, and then reactivate the plugin for it to work as intended.

## Expected Behavior
I expect to have both plugins activated and make settings changes in Give.

## Bug Type

- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Run the site at the link provided.
2. Ensure that WPML Multilingual CMS and WPML String Translation are activated
3. Change the test payment gateway from enabled/disabled.
4. When the page reloads see that the settings change isn't recognized

Link to the site download and credentials are attached to the generated Slack message in the #development channel.

## Visuals

Screencast of the issue:
https://screencast-o-matic.com/watch/cFXioeYPyC

## Related

https://secure.helpscout.net/conversation/700001042/28577

## Acceptance Criteria

- [ ] I can make setting changes with WPML String Translation and WPML Multilingual CMS activated.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://danaeu.local
Site URL: http://danaeu.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Donation form (#36)
Page for Posts: Unset
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: danaeu.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.20
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration❌User Registration Information✔Donor Note✔Email access✔Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: –
Test Mode: Disabled
Currency Code: EUR
Currency Position: Before
Decimal Separator: ,
Thousands Separator: .
Success Page: http://danaeu.local/en/donation-confirmation/
Failure Page: http://danaeu.local/en/donation-failed/
Donation History Page: http://danaeu.local/en/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: French Checks & Bank Transfers, PayPal Standard, Stripe - Credit Card, Stripe iDEAL, GoCardless
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #1983 ( 12U52291491357907 ) on 11/05/2018 at 19:23. Status VERIFIED
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Billing Address to Adress Details: ❌ Unlicensed – by WordImpress – 1.0
Give - Do not require fields: ❌ Unlicensed – by WordImpress – 1.0
Give - Fee Recovery: ❌ Unlicensed – by GiveWP – 1.7.2
Give - Goal WMPL compatible: ❌ Unlicensed – by WordImpress – 1.0
Give - GoCardless Gateway: ✔ Licensed – by WordImpress – 1.2.1
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - Off line to French Checks: ❌ Unlicensed – by WordImpress – 1.0
Give - PayPal Pro Gateway: ✔ Licensed – by WordImpress – 1.1.4
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.8.1
Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.1

### Other Active Plugins ###

All-in-One WP Migration: by ServMask – 6.76
Bugsnag Error Monitoring: by Bugsnag Inc. – 1.3.1
Count Per Day: by Tom Braider – 3.5.9
Error Log Monitor: by Janis Elsts – 1.6.2
Give - GDPR optin mailing privacy: by Plum Village – 1.0
Give Salesforce Integration: by Rajendra Kumar Bhochalya & Pham Hanh – 2.0.0
WP Mail SMTP: by WPForms – 1.3.3
WPML Multilingual CMS: by OnTheGoSystems – 4.0.8
WPML String Translation: by OnTheGoSystems – 2.8.8
WP PHP Console: by Fulvio Notarstefano – 1.5.2
WP Sync DB: by Sean Lang – 1.5

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.8
Give - Custom Amount Selected: by WordImpress – 1.0
SiteOrigin CSS: by SiteOrigin – 1.2.3
WPML Translation Management: by OnTheGoSystems – 2.6.8

### Active MU Plugins ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
Stop long comments: by WPEngine – 0.0.4
WP Engine System: by WP Engine – 3.2.1

### Theme ###

Name: Dana
Version: 1.0.3
Author URL: http://rkb.io
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by kevinwhoffman** [comment]
Discussed with @DevinWalker, we are closing as wontfix for a specific conflict with add-on of WPML. Re-open if other reports arise.
