### ISSUE TITLE
fix: prevent nonce error when deleting a donor from the donors screen

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3832]
# Bug Report

## User Story

As a Give admin who is a non-English speaker, I want to be able to delete donors from the Donor's screen in my native language.

## Current Behavior

Currently, if I have my local site set to "Espanol" and fully translated Give PO and MO files, when I go to delete a donor from the donors screen, I get the following error which prevents me from deleting the donor:
![image](https://user-images.githubusercontent.com/930724/48441437-5c769a80-e740-11e8-9776-a0c2752c6720.png)

## Expected Behavior

I expect to be able to delete the donor from this screen successfully.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Set your site to be on "Espanol". 
2. Download these translated Mo/Po files and place them in `wp-content/languages/plugins` : [give-es_ES.zip](https://github.com/impress-org/give/files/2577955/give-es_ES.zip)
3. Go to "Donations > Donors"
4. Hover over a donor and click on "Delete" then choose the additional options and click on the blue "Delete" button.
5. You should get the above nonce verification error message in Spanish.
6. Now set your site to be on "English" again and try the same process. It should work successfully.

Note, that while on Spanish, you can navigate to "Donations > Donors > View Donor" and then click on the "Delete Donor" tab and successfully delete the Donor from there without problem.

## Acceptance Criteria

- [x] I can delete a donor successfully while my site is set to Spanish and my local Po/Mo files for Give are set correctly.
- [x] This fix doesn't negatively impact any other Give translations.

## Environment

<details>
    ### WordPress Environment ###

Home URL: https://fundaciongomaespuma.test
Site URL: https://fundaciongomaespuma.test
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Inicio (#2)
Page for Posts: Actualidad (#193)
Table Prefix Length: 09om60D7_
Table Prefix Length: 9
Table Prefix Status: Acceptable
Admin AJAX: Accesible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: fundaciongomaespuma.test
TLS Connection: Usos de conexión TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1.000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.52.1, OpenSSL/1.0.2l
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Anuncio remoto: ✔
Control Remoto: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Activado
Database Updates: Todas las actualizaciones de la base de datos se completaron.
Give Cache: Activado
Give Cache: ✔Nueva donación✔Recibo de donación✔Nueva donación offline✔Instrucciones de donación offline✔Registro de nuevo usuario✔Información de registro de usuario✔Nombre del donante✔Acceso de correo electrónico
Upgraded From: 2.1.7
Test Mode: Desactivado
Currency Code: EUR
Currency Position: Después
Decimal Separator: ,
Thousands Separator: .
Success Page: https://fundaciongomaespuma.test/colabora/confirmacion-de-donacion/
Failure Page: https://fundaciongomaespuma.test/colabora/la-donacion-fallo/
Donation History Page: https://fundaciongomaespuma.test/colabora/historial-de-donaciones/
Give Forms Slug: /donations/
Enabled Payment Gateways: Estándar de PayPal, Donación offline
Default Payment Gateway: Estándar de PayPal
PayPal IPN Verification: Activado
PayPal IPN Notifications: IPN recibido por #10630 ( 7ES16575L2179850Y ) en 10/31/2018 a 19:33. Estado VERIFIED
Donor Email Access: Activado

### Other Active Plugins ###

Elementor: por Elementor.com – 2.2.7
Elementor Contact Form DB: por Sean Barton - Tortoise IT – 1.2
Elementor Extras: por Namogo – 1.9.15
Elementor Pro: por Elementor.com – 2.1.11
Enhanced Media Library: por wpUXsolutions – 2.7.2

### Inactive Plugins ###

Akismet Anti-Spam: por Automattic – 4.0.8
Classic Editor: por WordPress Contributors – 0.5
Code Snippets: por Shea Bunge – 2.12.0
Duplicate Post: por Enrico Battocchi – 3.2.2
Duplicator: por Snap Creek – 1.2.52
Easy EU Cookie law: por Albertolabs.com – 1.3.3.1
Fundación Gomaespuma: por Andrés Sedano –
Give - Currency Switcher: por WordImpress – 1.1
Give - Email Reports: por WordImpress – 1.1.2
Give - Fee Recovery: por GiveWP – 1.7.2
Give - Form Field Manager: por GiveWP – 1.4.0
Give - Google Analytics Donation Tracking: por WordImpress – 1.1.4
Give - MailChimp: por WordImpress – 1.4.1
Give - Manual Donations: por WordImpress – 1.4
Give - PDF Receipts: por WordImpress – 2.3
Give - Per Form Gateways: por WordImpress – 1.0.1
Give - Recurring Donations: por WordImpress – 1.8.1
Give - Stripe Gateway: por GiveWP – 2.1.1
Give - Tributes: por WordImpress – 1.4.2
GP Premium: por Tom Usborne – 1.7.3
Health Check & Troubleshooting: por The WordPress.org community – 1.2.1
Hello Dolly: por Matt Mullenweg – 1.7
Loco Translate: por Tim Whitlock – 2.1.5
Menu Items Visibility Control: por Hassan Derakhshandeh – 0.3.7
myStickymenu: por m.r.d.a – 2.0.5
Nav Menu Roles: por Kathy Darling – 1.9.2
PopBox For Elementor: por Zulfikar Nore – 1.0.7
Redirect After Login: por marcelotorres – 0.1.8
Simple Share Buttons Adder: por Simple Share Buttons – 7.4.18
Social Media and Share Icons (Ultimate Social Media): por UltimatelySocial – 2.0.6
Sticky Header Effects for Elementor: por Rwattner – 1.2.2
Sticky Menu (or Anything!) on Scroll: por Mark Senff – 2.1.1
TinyMCE Advanced: por Andrew Ozz – 4.8.0
Ultimate Social Media PLUS: por social share pro – 2.9.4
WidgetKit for Elementor: por Themesgrove – 1.2.0
WordPress Importer: por wordpressdotorg – 0.6.4
WP Customer Area: por MarvinLabs – 7.5.2
WP Mail SMTP: por WPForms – 1.3.3
WP Super Cache: por Automattic – 1.6.4

### Active MU Plugins ###

Bypass Login: por Stephen Carnam – 1.1.0
Health Check Troubleshooting Mode: por  – 1.5.0

### Theme ###

Name: GeneratePress Child
Version: 2.0.2.1522927594
Author URL: https://tomusborne.com
Child Theme: Si
Parent Theme Name: GeneratePress
Parent Theme Version: 2.1.4
Parent Theme Author URL: https://tomusborne.com

</details>

**Comment by kakshak** [comment]
**Slack Call Summary**

**Participant:** @kakshak @ravinderk @mehul0810 
**Topic:** How `donor` parameter will be generated
**Discussion:** I am confused regarding how the `donor` parameter is generated but after looking over the functionality that @mehul0810 developed, he has helped me to find that code from where this is generated.

**Comment by mathetos** [comment]
This user got it resolved by resetting his VPN... so it always seems to get resolved in one way or another still, but I still believe there is a root issue that is causing this.
https://wordpress.org/support/topic/paypal-standard-sometimes-works

**Comment by kakshak** [comment]
Slack Call Summary

Participant: @kakshak @mehul0810
Topic: Issue in creating `_wpnonce` field
Discussion: I have query while generating `_wpnonce` field while deleting the donors. @mehul0810 Helped me to resolve that.
