### ISSUE TITLE
feat: add ability to search through donor wall

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3835]
# Feature Request

## User Story

As a site admin, I want my donors to have the ability to search through the donor wall so that donors can look for other donors within the wall.

## Possible Solution
Adding a search bar at the top of the donor wall.

## Related

https://secure.helpscout.net/conversation/706546145/29080

## Acceptance Criteria

- [ ] donors can search the donor wall of a form with a search field on the page.

**Comment by DevinWalker** [comment]
The donor wall really isn't meant to be a search directory. It brings up more privacy concerns and I haven't seen major sites enabling any features like this so I don't think we have plans to implement such a feature in our plugin anytime soon.
