### ISSUE TITLE
fix: improve styling for all drop-downs in give short-codes

### ISSUE THREAD

**Issue by kakshak** [impress-org/give#3838]
# Bug Report

## User Story
As an admin user, I want to see proper styling while hovering the options from the drop-down at the time of inserting Give short-code into page/post.

## Current Behavior
Currently, while entering the short-code into page/post from the Give shortcodes then while hover over other options from drop-down the styling is not proper.

## Expected Behavior
I except that styling to display properly.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Go to Pages/Posts > Add/edit any page/post.
2. Click on `Give Shortcodes` above the WYSIWYG editor (Donor Wall)
3. Try to change the value from the drop-down by hovering other option.
4. You can see the styling is not looks good or proper.

## Visuals
https://www.useloom.com/share/8003e558a1344e109727bbb42a2fe3e0

## Acceptance Criteria
- [ ] All the options are properly visible into Give shortcodes drop-down.
- [ ] All the browser should have the same behavior with updated styling.
- [ ] The styling should be proper in `Page` as well as in `Post` type.

## Environment
<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Microsoft Windows</li>
        <li>Version: 10</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
	### WordPress Environment ###

Home URL: http://givetest.local
Site URL: http://givetest.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givetest.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access✔Renewal Receipt Email✔Renewal Receipt Email✔Subscription Cancelled Email✔Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.3.0
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://givetest.local/donation-confirmation/
Failure Page: http://givetest.local/donation-failed/
Donation History Page: http://givetest.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, PayPal Standard
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.8.2

### Other Active Plugins ###

Page Builder by SiteOrigin: by SiteOrigin – 2.9.1
SiteOrigin Widgets Bundle: by SiteOrigin – 1.13.2

### Inactive Plugins ###

Contact Form 7: by Takayuki Miyoshi – 5.0.4
Easy Digital Downloads: by Easy Digital Downloads – 2.9.8
Give - Braintree Gateway: by WordImpress – 1.2.2
Give - Currency Switcher: by GiveWP – 1.3.0
Give - Donation Upsells for WooCommerce: by WordImpress – 1.0.4
Give - Form Countdown: by WordImpress – 1.0.1
Give - Gift Aid: by WordImpress – 1.1.6
Give - Manual Donations: by WordImpress – 1.4.2
Give - Stripe Gateway: by GiveWP – 2.1.2
Give - Tributes: by WordImpress – 1.5.0
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
Timetable Responsive Schedule For WordPress: by QuanticaLabs – 3.1
WooCommerce: by Automattic – 3.4.5
WooCommerce Quick Checkout: by WordImpress – 2.0.0
WordPress Reset: by Aristeides Stathopoulos, Matt Martz – 1.4.1

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by nishitlangaliya** [comment]
@kevinwhoffman , I have gone through the video and try to reproduce issue but I am not seeing any style issue as per video. I have prepared my testing video.

https://www.useloom.com/share/6fb4b8f8d47f4bc3bda1e3dcd77cef48
