### ISSUE TITLE
fix: prevent DB upgrade from stalling when server blocks admin-ajax.php "start background update" request

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3843]
# Bug Report

## User Story
As an admin, I want hassle free DB updates

## Description
On the WPEngine server, we are facing an issue where admin-ajax.php works but somehow background updates does not trigger. On page DB update also does not run because of admin-ajax.php works. We have to find a way to automatically trigger on page DB update if somehow background update does not start.

For example: https://secure.helpscout.net/conversation/691051621/27741/

## Acceptance Criteria
- [ ] Run on page ajax DB update if background update does not start.

**Comment by kevinwhoffman** [comment]
@ravinderk Please provide an update for this one as well regarding whether it can be ready for 2.4.0.

**Comment by ravinderk** [comment]
@kevinwhoffman Only a few users having this issue on WPEngine and Recently nobody reports it. We did not also to replicate this issue on WPEngine as I testing this on the  @Benunc's  website. We can `icebox` this feature for now

**Comment by ravinderk** [comment]
closing in favor of https://github.com/impress-org/give/issues/4082
