### ISSUE TITLE
feat: add search bar to Donation Forms screen

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#3845]
# Feature Request

## User Story

As a user, I want a search bar on the Donation Forms screen so that it I have more control over searching for forms like I do with donations and donors.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/48536483-baa89800-e87c-11e8-9a8f-fcdc2f8faad6.png)

## Possible Solution

Use the same search bar UI from the Donations screen, but make sure the behavior reflects the acceptance criteria below.

The `Forms` dropdown should contain the following options:

- Any Goal Status
- Goal Achieved
- Goal In Progress
- Goal Not Set

## Acceptance Criteria

- [x] The old search box in the upper right has been removed.
- [x] When a string is entered into search, only forms whose names or IDs that contain that string are displayed.
- [x] When start and end dates are provided, only forms published between those dates are displayed.
- [x] When only a start date is provided, it shows all forms created after that date.
- [x] When only an end date is provided, it shows all forms created before that date.
- [x] When `Any Goal Status` is selected, all forms are displayed.
- [x] When `Goal Achieved` is selected, only forms with completed goals are displayed.
- [x] When `Goal In Progress` is selected, only forms with incomplete goals are displayed.
- [x] When `Goal Not Set` is selected, only forms without goals are displayed.
- [x] The date filters work with a non-default date format in WP settings.
- [x] Each field label is aligned vertically with its respective input.
- [x] Use the custom table to render form list table (`WP_LIst_Table`).

**Comment by nishitlangaliya** [comment]
## Slack Call Summary

Participants: @nishitlangaliya @ravinderk 
Topic: Discussion Regarding dependency of  #3818 
Result: I had a query regarding dependency of #3818 so for that @ravinderk suggested to take pull of this branch and merge into my current branch and once I will finish from my side I will create PR and create dependency of #3818.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak @ravinderk 
Topic: Discussion Regarding list the table using `WP_List_Table`
Result: I had a query regarding advanced search functionality after migrating the data using `WP_List_Table` but @ravinderk suggested that create the PR for that and he will work around this functionality and look over it.
