### ISSUE TITLE
fix: remove legacy code of donation forms export tool

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3848]
# Bug Report

## User Story
As a developer, I want to remove legacy code for donation forms export tool so that it doesn't acquire unnecessarily space.

## Current Behavior
I've noticed that the file https://github.com/impress-org/give/blob/master/includes/admin/tools/export/class-batch-export-forms.php is no longer used in any export tool. Please correct me if I'm wrong.

## Expected Behavior
Remove all the legacy code we are no longer using it.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Visuals
There is no export tool related to donation forms
![image](https://user-images.githubusercontent.com/1852711/48597509-35a8a600-e984-11e8-9660-baf8cd0d0baf.png)

## Related
- https://github.com/impress-org/give/issues/3847 (If the donation forms tool exists then this is the valid issue otherwise close this related issue as well)

## Acceptance Criteria
- [ ] Discuss whether the donation forms export tool is required or exists.

**Comment by kevinwhoffman** [comment]
@ravinderk Can you provide a second opinion on whether this code can be removed? It does not appear that we have a tool to import forms, so I can't see the value in exporting them at this time. Let us know if we're missing anything.

**Comment by ravinderk** [comment]
@kevinwhoffman I also did not find any use of this code in past. Since all forms are unique and easy to create, so I also did not find it useful to export and import on another site.

But I want to take @mathetos  suggestion on this.

**Comment by mathetos** [comment]
I don't know the history behind that code. The default WordPress export tool works fine for form exports and imports as far as I know. If that is true then we can safely remove that for sure. Otherwise, if the default export isn't sufficient then we might want to explore a formal form export/import tool.

**Comment by kevinwhoffman** [comment]
Thanks everyone. Let's get a final decision from @DevinWalker since he wrote the class and may know if there were other plans for it.

**Comment by DevinWalker** [comment]
This code is legacy code that was pulled over from EDD awhile back that was never implemented. I think it's a good template for exporting donation forms but it's unlikely we'll use the same method once we overhaul how forms are created.

**Comment by DevinWalker** [comment]
Resolved 02625ad6f02a2debf662cf1c25034983dc0c6cbf
