### ISSUE TITLE
feat: create some general fn to handle super global variables

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3857]
# Feature Request

## User Story
As a developer, I want to use super global variables properly so that their usage is sanitized properly and can help get rid of WPCS errors to achieve better score when Tide Project is implemented sooner or later.

Sometimes, there are code found in core or add-ons where we have not sanitized the super global variables like `$_GET`, `$_POST`, and `$_SERVER` which can lead to possible vulnerabilities.

## Possible Solution
Create a general function (maybe name it `give_get_global_variable`) which will contain a parameter `$type` (GET, POST, and SERVER) then in that function we will wrap the superglobal variables with `filter_input_array` method of PHP and `give_clean` method of Give core.

**Note:** We will create the function for now and will test whether it is working fine or not. Then, we will use it whenever we will find it in direct access usage of super global variables in Give Core.

## Acceptance Criteria
- [x] Create a general function
- [x] Test the function
- [x] Do not cache sanitize super global because the code will break if any add-on or core changes super global manually. https://github.com/impress-org/give/blob/b10f3fabec43b2ffd2b0e78f6149c52db1582849/includes/process-donation.php#L185

**Comment by ravinderk** [comment]
this functionality has been revert back. You will get more detailed information on https://github.com/impress-org/give/issues/4103
