### ISSUE TITLE
feat: provide option to export donors that have canceled a recurring donation yet haven't setup another one

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3859]
# Feature Request

## User Story

As a site admin, I want an option in the Export Donors section that will export a CSV file that will only include donors that have canceled a recurring donation, but haven't set up another one so that I can reach back out to those past donors.

This will allow me to quickly know which donors have given in the past but haven't signed up for another subscription. This also helps me not bug donors that are already giving on a recurring basis.

## Possible Solution
Possibly have a way to conditionally check if a donor has an active subscription and if so, they are excluded from the export.

## Related

https://secure.helpscout.net/conversation/709299780/29310

## Acceptance Criteria

- [ ] Have an option to generate a CSV file that only includes donors that have given a recurring donation in the past but don't have an active subscription.

**Comment by kevinwhoffman** [comment]
Closing as edge case, very specific request.
