### ISSUE TITLE
fix: ensure sourcemaps are working properly

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#3860]
# Bug Report

## User Story

As a developer, I want sourcemaps working so that I can easily inspect SaSS in dev tools.

## Bug Type

- [x] This bug describes functionality that once worked as expected.

## Acceptance Criteria

- [ ] I can run `npm run watch` and view sourcemaps linking back to the appropriate SaSS line number.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak @ravinderk @mehul0810 
Topic: Discussion regarding sourcemap code in dev tools
Discussion: I and @ravinderk discuss this as I don't know much about sourcemaps but @ravinderk suggested that to check with @mehul0810 as there is no sourcemaps files are generated. So, I talked with @mehul0810 and he shows me that in dev tool sourcemaps files are not generated. So, I'll create one video and upload that in the comment for confirmation.

**Comment by kakshak** [comment]
@DevinWalker @kevinwhoffman I've undrstood that right now, sourcemaps are not working properly for Give but we need to correct them and based on that I've recorded the video for what I understand for this task. Can you please look over it and let me know your thoughts on this?

## Video
https://www.useloom.com/share/cb9f4896723f49c989ad0d7e375442a4

**Comment by ravinderk** [comment]
@kakshak Yes. You are correct. This is an issue which we want to fix.

**Comment by kakshak** [comment]
@kevinwhoffman I've looked over it and spent around `2` hours for this task and I think I required more time in it because I don't know much about `sourcemaps` functionality. Let me know if you want that I'll spent more time in it.
