### ISSUE TITLE
fix: prevent error when exporting CSV between two dates

### ISSUE THREAD

**Issue by marutim** [impress-org/give#3864]
# Bug Report

## User Story

As an admin, I would like to export Donor CSV seamlessly without any issue.

Now I see the error "No data found for export parameters." when I select two dates to export the CSV but when you do not set any dates or want to export all the CSV data, it works as intended.

## Current Behavior

Does not export Donors CSV between two dates

## Expected Behavior

It should export the CSV if data is available between the dates.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.

## Steps to Reproduce

This issue was discovered while trying to replicate the same for Gift aid donations CSV.

I had difficulty replicating this issue in my regular setup but I could replicate the issue in a new setup with the following steps

1. Set a new setup with Give and Gift aid add-on.
2. Go to the General settings and make sure to set the date to "F j, Y" format
3. Now create a donation form with Gift aid enabled.
4. Do a couple of test donations.
5. Go to Donations >> Tools >> Export >> Try and export Donors CSV with date intervals an w/o date intervals. You should be able to do that without any issue.
6. Now change the date format to "d/m/y" and save changes.
7. Go to  to Donations >> Tools >> Export >> Try and export Donors CSV with date intervals an w/o date intervals. You should be able to export CSV without date intervals whereas you will see an error "No data found for export parameters." when you try to export CSV between two dates.

## Visuals

![general settings wp give gift aid wordpress](https://user-images.githubusercontent.com/3498917/48862042-23e35a80-edeb-11e8-8014-15de48a3c356.png)
![2](https://user-images.githubusercontent.com/3498917/48862045-25ad1e00-edeb-11e8-9cd6-4da25af19b4f.png)
![3](https://user-images.githubusercontent.com/3498917/48862051-2776e180-edeb-11e8-8ae8-475a2521f285.png)
![4](https://user-images.githubusercontent.com/3498917/48862108-4d03eb00-edeb-11e8-9da3-07a343025db2.png)

## Related

HS link: https://secure.helpscout.net/conversation/693351876/27948?folderId=1457790

## Acceptance Criteria

- [ ] Should be able to export donors CSV between dates.
- [ ] Should be able to export all donors CSV ( without setting the dates )

## Environment

<details>
   ### WordPress Environment ###

Home URL: http://wp-give-gift-aid.local
Site URL: http://wp-give-gift-aid.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: wp-give-gift-aid.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.52.1, OpenSSL/1.0.2l
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://wp-give-gift-aid.local/donation-confirmation/
Failure Page: http://wp-give-gift-aid.local/donation-failed/
Donation History Page: http://wp-give-gift-aid.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Gift Aid: ❌ Unlicensed – by WordImpress – 1.1.6

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by kevinwhoffman** [comment]
@nishitlangaliya Please ensure that your PR for this issue fixes any export where start and end dates are selected. For example, Maruti has indicated that this is an issue with the Give core `Export Donors` functionality and in `Gift Aid Donations` export. The provided solution should fix both.
