### ISSUE TITLE
feat: attach donor name to Stripe customer

### ISSUE THREAD

**Issue by Asparagirl** [impress-org/give#3867]
# Feature Request

## User Story
As a GiveWP user who has the Stripe add-on to process credit card donations, I want GiveWP to add the full name of the donor to the description of any new customer created in Stripe (instead of the annoying line "Stripe Customer generated by GiveWP via [my website URL here]") so that when I'm poking around in the Stripe dashboard trying to find information or reconcile bundled Stripe payouts to their individual component donations, I don't have to keep clicking through each customer link to their donation screen just to see who the heck that person is.

## Possible Solution
Wherever the line "Stripe Customer generated by GiveWP via [my website URL here]" is in the Stripe add-on code, please change it (or give us the option to change it) to something that actually gives the name of the customer. How about "JANE DOE - Stripe Customer generated by GiveWP via [my website URL here]"? Better yet, can you use the name listed by the donor on the payment screen to attach to the customer object in Stripe, too? Not just to the Description field for easy visibility, but also to the Given Name and Surname field, too?

## Acceptance Criteria

See above.

**Comment by mehul0810** [comment]
@Asparagirl Thanks for providing your feedback on the issue. I've taken a detailed look on the issue you're facing. I understand that you want to modify the `description` text of a new customer in Stripe dashboard as shown in the screenshot below. 
![image](https://user-images.githubusercontent.com/1852711/49057612-6ad7b280-f226-11e8-9d32-e9096df3df93.png)

However, I would like to let you know that we're already showing the first name and last name of the donor in the metadata fields of Stripe Customer as shown below:
![image](https://user-images.githubusercontent.com/1852711/49057678-9b1f5100-f226-11e8-918d-d8a6b8db13f7.png)

If you're still not comfortable with those metadata fields. Then, I've created a new snippet which will modify the `description` text to the full name of the donor as you expect.

**Snippet:** https://github.com/impress-org/give-snippet-library/blob/master/add-on-snippets/stripe/modify-customer-description.php

**After Implementing Snippet**
![image](https://user-images.githubusercontent.com/1852711/49057920-b6d72700-f227-11e8-9817-59af4a740902.png)

Let me know if you still have any questions.

**Comment by kevinwhoffman** [comment]
@Asparagirl Thanks for your feedback. It sounds like the snippet that @mehul0810 provided should filter the description text to meet your needs. If you need additional help implementing the snippet let us know. Closing as resolved.
