### ISSUE TITLE
feat: auto load Give options in Give_Cache to prevent frequent multiple queries

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3872]
# Feature Request

## Description
As we can see in the screenshot, we are doing a few DB queries to fetch plugin option. We can prevent multiple queries by preloading them to `Give_Cache`

![image](https://user-images.githubusercontent.com/1784821/48996861-b0877300-f173-11e8-8fec-f827806a47f4.png)

List of frequently load options:
- [x] give_settings
- [x] give_version
- [x] give_completed_upgrades
- [ ] __give_get_active_license_info
- [x] give_is_addon_activated
- [x] give_doing_upgrade
- [x] give_install_pages_created
- [x] give_show_db_upgrade_complete_notice
- [ ] give_cache__give_activation_redirect
- [ ] give_cache__give_installed
- [ ] <s>_give_table_check</s>: Need to discuss maybe we can remove code.
- [ ] give_cache__give_ajax_works
- [x] give_paused_batches ?
- [ ] give_cache__give_notice_give_upgrade_db ?
- [ ] give_cache_hide_license_notice_after_activation
- [ ] give_cache__give_notice_give-invalid-license_shortly_**

We can save <12 queries If we load them prior to use and maintain result in cache. 

## Acceptance Criteria
- [x] Identify plugin option which we are fetching on each page load.
- [x] Preload option to `Give_Cache` which we query on each page load.
- [x] get, set and delete option must update cached value.
- [x] Add PHPUnit tests

**Comment by ravinderk** [comment]
Slack Chat Summary

Participants: @DevinWalker @ravinderk 
Topic: Can we start working on this
Result: As we discuss, we can start working on this if a few points will be taken care ( added in to acceptance criteria).
ref: https://givewp.slack.com/archives/C0FAGC83C/p1544788335124300

**Comment by kevinwhoffman** [comment]
@ravinderk Can you provide an update on this and whether you think it should stay in 2.4.0 with projected release of next week?

**Comment by ravinderk** [comment]
@kevinwhoffman this implemented for the frontend, so one part of this issue done. Next phase of this issue will be implement this in admin which we can do after `2.4.0`

**Comment by kevinwhoffman** [comment]
Per @ravinderk's recommendation, I'm removing this from 2.4.0 and moving back to Product Backlog to address the rest of the options mentioned in Acceptance Criteria in a future release.

**Comment by kevinwhoffman** [comment]
Closing as this was resolved in https://github.com/impress-org/give/pull/4023 but did not auto-close.
