### ISSUE TITLE
fix: improve donations list performance

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3874]
# Bug Report

## User Story
As a user, I want to fetch the donation listing as fast as possible so that it provides a great UX.

## Current Behavior
While working on a recurring add-on issue, I've noticed that Give Core is creating more than 350 queries to list the donations which need improvement.

## Expected Behavior
I expect to optimize queries to a lesser number which will help improve performance to list down the donations when there are more than 5000 donations

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install Query Monitor to identify the number of queries used to list down donations.
2. Filter the duplicate queries
3. Try to bail out early to remove duplicate queries where not required.

## Visuals
**Only Give Core is active**
![image](https://user-images.githubusercontent.com/1852711/49060740-cf9a0980-f234-11e8-9ac5-ecf9fe7c7ed4.png)

## Related
- https://github.com/impress-org/give-recurring-donations/issues/778

## Acceptance Criteria
- [ ] Improve performance without affecting functionality.
- [ ] Test existing functionality

**Comment by kevinwhoffman** [comment]
@DevinWalker and I reviewed the current query count for the Donations page in Give 2.4.0 and think performance is okay for now. Closing.
