### ISSUE TITLE
fix: ensure compatibility with Tickera QR code

### ISSUE THREAD

**Issue by marutim** [impress-org/give#3880]
# Bug Report

## User Story

As a user I would like to use Tickera ( https://tickera.com/ ) and Give together in my website with both the plugins working seamlessly.

At the moment when Give core is activated then the QR code does not appear in the generated PDF
by Tickera.

## Current Behavior

Tickera QR code does not appear in the PDF when the Give core plugin is activated.

## Expected Behavior

Tickera QR code should appear as usual in the PDF when the Give core plugin is activated.

## Bug Type

- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1) With both plugins activated, access from the dashboard sidebar "Tickera --> Ticket Templates".
2) Click Edit.
3) Click Preview in the right hand toolbar.
4) Notice that no QR code appears in the PDF generated.
5) Disable the GiveWP core plugin.
6) Repeat steps 1-4.
7) Notice that the QR code appears in the PDF generated.

## Visuals

![1](https://user-images.githubusercontent.com/3498917/49244223-54ec0c80-f435-11e8-83dc-65ef72531c2a.png)
![2](https://user-images.githubusercontent.com/3498917/49244227-56b5d000-f435-11e8-974b-14d3a7bcc472.png)
![3](https://user-images.githubusercontent.com/3498917/49244230-587f9380-f435-11e8-96c2-99430646c8ab.png)

## Related
HS link: https://secure.helpscout.net/conversation/699176426/28445?folderId=1457790
Tickera plugin is added to the Google Drive -

## Acceptance Criteria

- [ ] Tickera and Give core works seamlessly together and QR code is available in the generated PDF.

## Environment

<details>
  ### WordPress Environment ###

Home URL: http://give-new.local
Site URL: http://give-new.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, order_received, order_paid, order_cancelled, order_fraud, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give-new.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.52.1, OpenSSL/1.0.2l
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: 2.3.0
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give-new.local/donation-confirmation/
Failure Page: http://give-new.local/donation-failed/
Donation History Page: http://give-new.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Offline Donation, PayPal Standard, Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.2

### Other Active Plugins ###

Tickera: by Tickera.com – 3.2.9.9

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by DevinWalker** [comment]
## Review Findings

I attempted to replicate the issue and was unable to do so:

### PDF Preview

![2019-01-17_13-48-52](https://user-images.githubusercontent.com/1571635/51351279-472f2c80-1a5f-11e9-97c0-571c9c2bb533.png)

### Configuration

![2019-01-17_13-50-10](https://user-images.githubusercontent.com/1571635/51351282-48f8f000-1a5f-11e9-9c2e-c1c54f6cacc1.png)

### System Info

### WordPress Environment ###

Home URL: https://give.test
Site URL: https://give.test
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, order_received, order_paid, order_cancelled, order_fraud, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.4.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.4.0
Test Mode: Enabled
Currency Code: EUR
Currency Position: Before
Decimal Separator: ,
Thousands Separator: .
Success Page: https://give.test/donation-confirmation/
Failure Page: https://give.test/donation-failed/
Donation History Page: https://give.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard, Test Donation, Offline Donation, Stripe - Credit Card, Square Gateway, Authorize.net, Mollie Gateway
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Annual Receipts: ❌ Unlicensed – by GiveWP – 1.0.0
Give - Authorize.net Gateway: ❌ Unlicensed – by GiveWP – 1.4.6
Give - Currency Switcher: ❌ Unlicensed – by GiveWP – 1.3.1
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.1
Give - GoCardless Gateway: ❌ Unlicensed – by WordImpress – 1.2.1
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.4.3
Give - Mollie Gateway: ❌ Unlicensed – by GiveWP – 1.2.0
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 2.3.2
Give - Per Form Gateways: ❌ Unlicensed – by GiveWP – 1.0.2
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.8.4
Give - Square: ❌ Unlicensed – by GiveWP – 1.0.0
Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.2
Give - Testing Plugin: ❌ Unlicensed – by GiveWP – 1.0
Give - Tributes: ❌ Unlicensed – by GiveWP – 1.5.2

### Other Active Plugins ###

Debug Bar: by wordpressdotorg – 1.0
Debug Bar Console: by koopersmith – 0.3
Query Monitor: by John Blackbourn & contributors – 3.2.2
Simply Show Hooks: by Stuart O'Brien, cxThemes – 1.2.1
Tickera: by Tickera.com – 3.2.9.9
User Switching: by John Blackbourn & contributors – 1.4.0

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.1
Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 2.1.7.2
Caldera Forms: by Caldera Labs – 1.7.5.1
Classic Editor: by WordPress Contributors – 1.3
Constant Contact Plugin for WordPress: by Katz Web Services, Inc. – 4.1.1
Custom Post Type UI: by WebDevStudios – 1.6.1
Easy Custom Auto Excerpt: by tonjoo – 2.4.10
Easy Digital Downloads: by Easy Digital Downloads – 2.9.11
Easy Digital Downloads - Recurring Payments: by Easy Digital Downloads – 2.7.28
Elementor: by Elementor.com – 2.3.8
Give - 2Checkout Gateway: by WordImpress – 1.1.3
Give - Addon Boilerplate: by WordImpress, LLC – 1.0
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.3.3
Give - AWeber: by WordImpress – 1.0.3
Give - Braintree Gateway: by GiveWP – 1.2.3
Give - CCAvenue Gateway: by GiveWP – 1.0.4
Give - Constant Contact: by GiveWP – 1.2.2
Give - ConvertKit: by WordImpress – 1.0.2
Give - CSV Toolbox: by WordImpress – 1.0
Give - Custom PayPal Success Redirects: by Devin Walker – 1.0
Give - Donation Upsells for WooCommerce: by GiveWP – 1.1.0
Give - Email Reports: by WordImpress – 1.1.2
Give - Fee Recovery: by GiveWP – 1.7.3
Give - Form Countdown: by WordImpress – 1.0.1
Give - Gift Aid: by GiveWP – 1.2.0
Give - Google Analytics Donation Tracking: by GiveWP – 1.2.2
Give - iATS Payment Solutions: by GiveWP – 1.0.4
Give - MailChimp: by GiveWP – 1.4.3
Give - PayFast Payment Gateway: by WordImpress – 1.0.2
Give - PayPal Pro Gateway: by GiveWP – 1.2.1
Give - Paytm Gateway: by GiveWP – 1.0.1
Give - PayUmoney: by GiveWP – 1.0.4
Give - Razorpay: by GiveWP – 1.2.1
Give - Setting API Fields Example: by WordImpress – 1.0
Give - Sofort Payment Gateway: by WordImpress, CoachBirgit – 1.0
Give - WePay Gateway: by WordImpress – 1.3.1
Give - Zapier: by GiveWP – 1.2.1
Give to ZBS CRM Connector: by https://zerobscrm.com – 1.0.4
Gutenberg: by Gutenberg Team – 4.8.0
iThemes Sales Accelerator: by iThemes – 1.2.11
Jetpack by WordPress.com: by Automattic – 6.8.1
MonsterInsights Pro: by MonsterInsights – 6.2.4
Ninja Forms: by The WP Ninjas – 3.3.21.2
Ninja Forms - File Uploads: by The WP Ninjas – 3.0.19
Ninja Forms - Multi-Part Forms: by The WP Ninjas – 3.0.23
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Page Builder by SiteOrigin: by SiteOrigin – 2.9.7
RTL Tester: by Yoav Farhi, Automattic – 1.1
The Events Calendar: by Modern Tribe, Inc. – 4.7.3
The Events Calendar: Eventbrite Tickets: by Modern Tribe, Inc. – 4.5.5
Transients Manager: by Pippin Williamson – 1.7.5
User Role Editor: by Vladimir Garagulya – 4.48
WooCommerce: by Automattic – 3.5.3
WooCommerce Admin: by Automattic – 0.2.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.6
WooCommerce Services: by Automattic – 1.18.0
WooCommerce Stripe Gateway: by WooCommerce – 4.1.13
Wordfence Security: by Wordfence – 7.1.20
WordPress Admin Style: by Frank Bültge – 1.5.1
WordPress Beta Tester: by Peter Westwood – 1.2.6
WordPress Importer: by wordpressdotorg – 0.6.4
WP Business Reviews: by Impress.org – 1.2.0
WP Crontrol: by John Blackbourn & contributors – 1.6.2
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.0
WPForms: by WPForms – 1.4.9
WP Migrate DB Pro: by Delicious Brains – 1.7.1
WPML Multilingual CMS: by OnTheGoSystems – 3.7.1

### Active MU Plugins ###

load.php: by  –
Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

---

Closing until further reports or replicable.

**Comment by Benunc** [comment]
Reopening, see video:

http://somup.com/cqivoAe2bc
