### ISSUE TITLE
Plugin Conflict: AMP currently creates 500 server error when viewing /wp-admin/

### ISSUE THREAD

**Issue by KZeni** [impress-org/give#3895]
# Bug Report

## User Story
As a web developer & manager, I want Give updated so that using the AMP plugin (https://wordpress.org/plugins/amp/) doesn't cause a 500 server error when accessing the site admin.

## Current Behavior
I’m getting a 500 server error when trying to access the site admin after updating AMP (https://wordpress.org/plugins/amp/) to the latest version. Turns out that there’s a conflict with Gives which my sites were running into. I also believe the issue could be specific to PHP 7.x (a matter of the number of variables provided to a function vs. what was expected).

I’ve opted to disable AMP to avoid this error until this is fixed since Give is more important to the site than AMP is. This issue happened on live sites so I haven't re-implemented the problematic setup to dig into the debug log since I'm sure the issue can be easily re-created on a dev setup.

## Expected Behavior
I'd expect the site admin to work without issue with both Give and AMP enabled.

## Bug Type
- [x] This bug describes functionality that once worked as expected in Give version 2.3.0 with AMP version 0.7.2.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Possibly need to be running PHP 7.x
2. Install & enable Give 2.3.0.
3. Install & enable AMP 1.0.0.
4. Try to access the site admin & instead be greeted with a 500 server error.

## Related
I've also submitted this on the WP.org support forum at https://wordpress.org/support/topic/plugin-conflict-amp-currently-creates-500-server-error-when-viewing-wp-admin/

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: All</li>
        <li>Version: Any</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: All</li>
        <li>Version: Any</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://www.forallenforyou.com
Site URL: https://www.forallenforyou.com
WP Version: 5.0
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%postname%/
Show on Front: page
Page on Front: Home (#2)
Page for Posts: Unset
Table Prefix Length: almfwp_
Table Prefix Length: 7
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, acf-disabled, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: amperage-rds.cfmz5zg2f7qi.us-east-1.rds.amazonaws.com, SRV: www.forallenforyou.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Bad
Server Info: Apache
PHP Version: 7.2.11
PHP Post Max Size: 2 GB
PHP Time Limit: 1800
PHP Max Input Vars: 16384
PHP Max Upload Size: 2 GB
cURL Version: 7.53.1, NSS/3.36
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note❌Email access
Upgraded From: –
Test Mode: Disabled
Currency Code: USD
Currency Position: After
Decimal Separator: .
Thousands Separator: ,
Success Page: https://www.forallenforyou.com/donation-confirmation/
Failure Page: https://www.forallenforyou.com/transaction-failed/
Donation History Page: https://www.forallenforyou.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Authorize.net
Default Payment Gateway: Authorize.net
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Disabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.2.3
Give - Email Reports: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.1.3
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by WordImpress – 1.0
Give - MailChimp: ❌ Unlicensed – by WordImpress – 1.3.6
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.1.1
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.0.6
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.3.1

### Other Active Plugins ###

ACF Content Analysis for Yoast SEO: by Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast – 2.1.0
Admin Bar Color: by Eduardo Zulian – 1.2
Admin Bar Wrap Fix: by KZeni – 0.9.2
Admin Color Schemes: by WordPress Core Team – 2.2
Advanced Automatic Updates: by pento – 1.0.2
Advanced Custom Fields: by Elliot Condon – 5.7.8
Akismet Anti-Spam: by Automattic – 4.1
Audience Analytics – by Quantcast: by Quantcast – 1.0.1
Broken Link Checker: by Janis Elsts, Vladimir Prelovac – 1.11.5
Central Color Palette: by Gáravo – 1.12.6
Classic Editor: by WordPress Contributors – 1.1
CMS Tree Page View: by Pär Thernström – 1.6
Custom Dashboard: by AMPERAGE – 1.0
Custom Post Type UI: by WebDevStudios – 1.6.1
Default Admin Color Scheme: by Barry Ceelen – 1.0.1
Download Monitor: by Never5 – 4.1.1
Email Address Encoder: by Till Krüss – 1.0.12
Enable Media Replace: by ShortPixel – 3.2.7
Enhanced Media Library: by wpUXsolutions – 2.7.2
Facebook Instant Articles & Google AMP Pages by PageFrog: by PageFrog Team – 1.0.9
FeedPress: by FeedPress – 1.7.2
Fluid Video Embeds: by jamie3d – 1.2.9
Glue for Yoast SEO & AMP: by Joost de Valk – 0.4.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.3.2
Gravity Forms: by rocketgenius – 2.1.2
Gravity Forms Event Tracking: by Ronald Huereca – 2.3.5
Jetpack by WordPress.com: by Automattic – 6.8.1
MailChimp Activity: by ibericode – 1.0.5
MailChimp for WordPress: by ibericode – 4.3.1
Media File Renamer Auto: by Jordy Meow – 4.5.0
MetaSlider: by Team Updraft – 3.10.3
MetaSlider - Pro Add-on Pack: by Team Updraft – 2.11.0
Page Builder by SiteOrigin: by SiteOrigin – 2.9.5
Post Snippets: by David de Boer – 3.0.5
Quoty: by TNT Studio – 1.1.4
Really Simple SSL: by Rogier Lankhorst, Mark Wolters – 3.1.3
Recent Posts Widget Extended: by Satrya – 0.9.9.7
Redirection: by John Godley – 3.6.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Simple History: by Pär Thernström – 2.28.1
SiteOrigin Widgets Bundle: by SiteOrigin – 1.13.4
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.18
TinyMCE Advanced: by Andrew Ozz – 4.8.0
Unattach: by tamlyn – 1.2.2
Use Google Libraries: by Jason Penney – 1.6.2.3
User Role Editor: by Vladimir Garagulya – 4.47
W3 Total Cache: by Frederick Townes – 0.9.7
WP-Optimize: by David Anderson, Ruhani Rabin, Team Updraft – 2.2.6
WP Better Emails: by Nicolas Lemoine – 0.3
WP Feed Post Thumbnail: by required – 2.1.1
WP Mail SMTP: by WPForms – 1.4.1
WP Retina 2x: by Jordy Meow – 5.5.1
Yoast SEO: by Team Yoast – 9.2.1

### Inactive Plugins ###

Give - 2Checkout Gateway: by WordImpress – 1.0.1
Give - AWeber: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.1
Give - CCAvenue Gateway: by WordImpress – 1.0
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.1
Give - Dwolla Gateway: by WordImpress – 1.1.1
Give - iATS Gateway: by WordImpress – 1.0
Give - Paymill Gateway: by WordImpress – 1.0.2
Give - PayPal Pro Gateway: by WordImpress – 1.1.3
Give - PayUmoney: by WordImpress – 1.0
Give - Per Form Emails: by WordImpress – 1.0.1
Give - Per Form Gateways: by WordImpress – 1.0.1
Give - Razorpay: by WordImpress – 1.0
Give - Stripe Gateway: by WordImpress – 1.4.7
Give - WePay Gateway: by WordImpress – 1.3.1
Give - Zapier: by WordImpress – 1.1.1
Gutenberg: by Gutenberg Team – 4.6.1
Media Cleaner: by Jordy Meow – 5.1.0

### Theme ###

Name: For Allen For You
Version: 1.0
Author URL: http://www.amperagemarketing.com/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by ravinderk** [comment]
@KZeni Can we close this issue because I think it will be fixed in `AMP 1.0.1` or Do we have to make any change on our side as well?

**Comment by KZeni** [comment]
@ravinderk Yeah, the conflict with AMP should be resolved in AMP 1.0.1. Also, https://github.com/impress-org/give/pull/3899 highlights changes to be made on the Give side of things which would also prevent this conflict with AMP 1.0.0 & potentially other plugins. As such, I'll go ahead and close this issue.
