### ISSUE TITLE
fix: have session persist through accessing donation history and receipt

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3935]
# Bug Report

## User Story

As a donor, I want to access my donation history so that I can see my past donation from the donation history page. From there I want to view my receipt page from the list of past donations.

## Current Behavior

Currently, when I submit a donation and then attempt to view that donation receipt on the donation history page I'm asked again and again to verify my email address to view my receipt page.

## Expected Behavior
I expect to verify my email address and then have access to my donation history and receipt pages.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Submit a donation through a form
2. Navigate to the donation history page in an incognito window
3. Use the submitted email address to generate an email
4. In the email select the link to view donation history in an incognito window
5. Select to view the receipt on the donation history page
6. Keep being presented with the form to verify the email address without viewing receipt

## Visuals

Screencast of the issue:
https://screencast-o-matic.com/watch/cqV6Y63jA2

## Related

https://secure.helpscout.net/conversation/750208959/32303

## Acceptance Criteria

- [ ] Completing the process to obtain access to the donation history page allows the receipt to be viewed.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, in-progress, failed, acf-disabled, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.1
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access✔Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.3.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Authorize.net
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by GiveWP – 1.4.4
Give - Braintree Gateway: ❌ Unlicensed – by GiveWP – 1.2.3
Give - CCAvenue Gateway: ❌ Unlicensed – by GiveWP – 1.0.4
Give - Donation Upsells for WooCommerce: ❌ Unlicensed – by GiveWP – 1.1.0
Give - Fee Recovery: ❌ Unlicensed – by GiveWP – 1.7.4
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.1
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by GiveWP – 1.2.1
Give - MailChimp: ❌ Unlicensed – by GiveWP – 1.4.3
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.4.2
Give - Mollie Gateway: ❌ Unlicensed – by WordImpress – 1.1.2
Give - PayPal Pro Gateway: ❌ Unlicensed – by GiveWP – 1.2.1
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0.1
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 2.3.2
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.8.2
Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.2
Give - Tributes: ❌ Unlicensed – by GiveWP – 1.5.2
Sam's Helper Function: ❌ Unlicensed – by WordImpress – 1.0

### Other Active Plugins ###

Advanced Custom Fields: by Elliot Condon – 5.7.7
Give - Hook Helper: by Ravinder Kumar – 1.0
Transients Manager: by Pippin Williamson – 1.7.5
User Role Editor: by Vladimir Garagulya – 4.47
WooCommerce: by Automattic – 3.5.2

### Inactive Plugins ###

All-in-One WP Migration: by ServMask – 6.78
Contact Form 7: by Takayuki Miyoshi – 5.0.4
Elementor: by Elementor.com – 2.3.2
Give - Email Reports: by WordImpress – 1.1.2
Give - Gift Aid: by WordImpress – 1.1.6
Give - GoCardless Gateway: by WordImpress – 1.2.1
Give - Razorpay: by WordImpress – 1.2.0
Gutenberg: by Gutenberg Team – 4.1.1
Intelligence: by LevelTen – 1.3.1
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
WordPress Importer: by wordpressdotorg – 0.6.4
WP Business Reviews: by Impress.org – 1.0.0

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by DevinWalker** [comment]
@samsmith89 	this was actually resolved in this commit: f5b34e69b5dc2e3c932cd7ad9e0ba72284a75613
