### ISSUE TITLE
fix: update email tag descriptions for name and company

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3943]
# Bug Report

## User Story

As a Give user I want to know what to expect when I use certain email tags in my email notifications.

## Current Behavior

The `{name}` email tag currently is described as:
> The donor's first name

See here:
![image](https://user-images.githubusercontent.com/930724/51217811-7f5b3180-18de-11e9-8815-dc54a0488b70.png)

But in reality, it displays different things under different circumstances:
* If there is no last name, it displays only the first name
* If there is a prefix and last name, it display those and NOT the first name. 

## Expected Behavior

I think we should simply update the description of this tag to the following:
> Displays the donor's name for salutation purposes; either just the first name, or prefix and last name if provided.

## Bug Type

- [X] This bug describes functionality that once worked as expected in version X.X.X. -- most likely when we introduced the prefixes this got changed but not he tag description.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. View the tag description
2. Test the output by having different donations with just a first name, just a prefix and first name, and prefix/first/last all present and preview the email with the Preview Email feature.

## Acceptance Criteria

- [ ] The email tag description is updated in every place where it exists.

**Comment by kevinwhoffman** [comment]
@nishitlangaliya There are two email tags and descriptions that need to be clarified and made consistent with the other descriptions. Please update the following descriptions for `{name}` and `{company}`.

> {name} -  The donor's name for salutation purposes—either first name only or prefix and last name if provided.

> {company} - The donor's company name.
