### ISSUE TITLE
fix: incorrect title placement within give form widget

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#3947]
# Bug Report

Reported here: https://wordpress.org/support/topic/update-caused-widget-display-issues/

## User Story

As a admin, I do not want the form title to display when I add a Give Form Widget in the sidebar so that donors don't see duplicate titles or content displayed above the title.

## Expected Behavior

The form title always appears at the top of the widget regardless of configuration.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.3.1.

## Steps to Reproduce

1. Create a donation form with dummy content like lorem ipsum
2. Add the donation form to the sidebar in modal view with content displayed above the form
3. Visit the sidebar on the frontend and open the modal and close it

## Visuals

![2019-01-17_14-27-56](https://user-images.githubusercontent.com/1571635/51353007-24534700-1a64-11e9-85fa-0abd403a8a26.gif)

## Possible Solution

1. Option 1: Display the title only when 
2. Option 2: _Never_ display the title in the donation form widget like previous versions. 

## Related

https://github.com/impress-org/give/issues/3881

**Comment by marutim** [comment]
@DevinWalker I would also like to add that I can replicate this issue with the give_form shortcode and Give form block.

The form title appears irrespective of whether it is set to show_title="False" in shortcode or title being disabled in the block settings.

**Comment by DevinWalker** [comment]
I've taken care of the shortcode attributes and Gutenberg blocks @marutim in https://github.com/impress-org/give/pull/3991

**Comment by ravinderk** [comment]
@DevinWalker Closing this issue

**Comment by ravinderk** [comment]
@mehul0810 @DevinWalker reopening this issue because it needs to be tested with past issue: https://github.com/impress-org/give/issues/3881

**Comment by mehul0810** [comment]
## Slack Call Summary
Participants: @mehul0810 @ravinderk 
Topic: Discussion about this issue
Result: This issue is not fixed yet or maybe not worked upon. However, #3881 is working fine as per my testing over a call with Ravinder. While testing #3881, I noticed an issue with currency switcher dropdown in the modal popup of form grid for which I'll create an issue

**Comment by DevinWalker** [comment]
I've confirmed this issue is resolved.
