### ISSUE TITLE
fix: ensure donor mailing addresses match when exporting to csv

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3971]
# Bug Report

## User Story

As a Give admin, I want my export of my donors to have the correct mailing address according to the database. 

## Current Behavior

Currently, when I export my donors, the mailing addresses do not match the donor correctly. Mailing addresses of one donor are showing up in a row for a different donor. 

## Expected Behavior

Each donor row should only have information for that donor and none other.

## Bug Type

- [x] This bug describes functionality that once worked as expected before version 2.4
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Have a site with donors that were created in Give versions older than 2.4
2. Update to 2.4
3. Add new donors
4. Go to "Donations > Tools > Exports" and do a Donor Export
5. Open the CSV file and note that the mailing addresses are mixed up.

## Related

HelpScout Reports
-- https://secure.helpscout.net/conversation/765518833/33490?folderId=1457790
-- https://secure.helpscout.net/conversation/766256253/33525?folderId=672194

## Acceptance Criteria

- [x] When the Export Donor tool is used, the donor mailing addresses match correctly.

## Environment

This is the System Info from the most recent report in HelpScout with the URL redacted.
<details>
    ### WordPress Environment ###
Home URL: {redacted}
Site URL: {redacted}
WP Version: 5.0.3
WP Multisite: -
WP Memory Limit: 256 MB
WP Debug Mode: -
WP Cron: ✔
Language: fr_FR
Permalink Structure: //
Show on Front: page
Page on Front: Accueil (#7)
Page for Posts: Carnet de vol (#44)
Table Prefix Length: bqg_
Table Prefix Length: 4
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, customize-draft, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: {redacted}
TLS Connection: Connexion utilisé TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.1.23
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 2500
PHP Max Upload Size: 128 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - Nous recommandons au minimum cURL 7.40.
SUHOSIN Installed: -
MySQL Version: 5.7.20
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.4.0
Give Cache: Activé
Database Updates: Toutes les mises à jours de la base de données sont terminéees.
Give Cache: Activé
Give Cache: ❌Nouveau don✔Reçu de dons✔Nouveau don hors-ligne✔Instructions pour le dons hors ligne❌Enregistrement d'un nouvel utilisateur✔User Registration Information✔Donor Note✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: -
Test Mode: Désactivé
Currency Code: EUR
Currency Position: Après
Decimal Separator: .
Thousands Separator: ,
Success Page: {redacted}
Failure Page: {redacted}
Donation History Page: {redacted}
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard, Don hors ligne, Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Activé
PayPal IPN Notifications: IPN reçu pour #4126 ( 3TK49859PF895470P ) le 01/29/2019 à 12:37. Statut VERIFIED
Donor Email Access: Activé

### Active Give Add-ons ###

Give - Annual Receipts: ❌ Non autorisé - par GiveWP - 1.0.1
Give - Currency Switcher: ❌ Non autorisé - par GiveWP - 1.3.1
Give - Email Reports: ✔ Autorisé - par WordImpress - 1.1.2
Give - MailChimp: ❌ Non autorisé - par GiveWP - 1.4.3
Give - Manual Donations: ❌ Non autorisé - par GiveWP - 1.4.2
Give - Recurring Donations: ❌ Non autorisé - par GiveWP - 1.8.3
Give - Stripe Gateway: ❌ Non autorisé - par GiveWP - 2.1.2

### Other Active Plugins ###

Akismet Anti-Spam: par Automattic - 4.1
AWSM Team Pro: par AWSM Innovations - 1.1.4
Better Menu Widget: par Tracey Holinka - 1.5.1
Code Snippets: par Shea Bunge - 2.13.0
Contact Form 7: par Takayuki Miyoshi - 5.1.1
Customize Posts: par XWP - 0.9.1
Display Posts Shortcode: par Bill Erickson - 2.9.0
Google Analytics Dashboard for WP (GADWP): par ExactMetrics - 5.3.5
Hide Page And Post Title: par Arjun Thakur - 1.2
HTML5 Responsive FAQ: par Aman Verma - 2.5.5
MailChimp for WordPress: par ibericode - 4.3.3
Media Credit: par Peter Putzer - 3.2.0
Mega Addons For Visual Composer: par Nasir - 2.2
MetaSlider: par Team Updraft - 3.9.1
Organic Builder Widgets: par Organic Themes - 1.2.14
Polylang: par Frédéric Demarle - 2.5.1
Really Simple SSL: par Rogier Lankhorst, Mark Wolters - 3.1.3
SiteOrigin CSS: par SiteOrigin - 1.2.4
Smart Slider 3: par Nextend - 3.3.7
Smush: par WPMU DEV - 2.8.1
Sticky Menu (or Anything!) on Scroll: par Mark Senff - 2.1.1
UpdraftPlus - Backup/Restore: par UpdraftPlus.Com, DavidAnderson - 1.16.4
Video Slider Rich: par Rich-Web - 1.2.4
WP Socializer: par Aakash Chakravarthy - 3.3.4
Yoast SEO: par Team Yoast - 9.5

### Inactive Plugins ###

Classic Editor: par WordPress Contributors - 1.3
Conditional Menus: par Themify - 1.1.1
Contact Form 7 Polylang extension: par Aurovrata V. - 2.3.0
Give - PDF Receipts: par WordImpress - 2.3
Google Analytics for WordPress by MonsterInsights: par MonsterInsights - 7.4.1
Responsive WordPress Slider - Soliloquy Lite: par Soliloquy Team - 2.5.3
Team Members: par WP Darko - 4.1.2
WooCommerce: par Automattic - 3.5.4

### Theme ###

Name: GivingPress Lite
Version: 1.8.5
Author URL: http://givingpress.com/
Child Theme: Non - Si vous modifiez Give sur un thème parent que vous n'avez pas personnellement créé, nous vous recommandons d'utiliser un thème enfant. Voir Comment créer un thème enfant
</details>

**Comment by kevinwhoffman** [comment]
@nishitlangaliya Please recreate the issue as Matt has described. Once you have a PR ready, post a brief video showing that the exported donor addresses match up with the address in the donor profile screen.

**Comment by ravinderk** [comment]
@DevinWalker @kevinwhoffman I think we faced a similar issue with give_get_donor_address fn when developing annual receipt addon too. The main cause of this issue is backward compatibility for user ID. If we will drop backward compatibility then the issue will fix automatically.

Let me know what do you think.

**Comment by kevinwhoffman** [comment]
@ravinderk Assigning this one to you. I do believe it's related to the issue we ran into with Annual Receipts. Please look into that solution and we can discuss any backwards compatibility issues on status call.

**Comment by kevinwhoffman** [comment]
Per dev team discussion, we agree to deprecate support for old user ID method to prevent address mismatch going forward.
