### ISSUE TITLE
fix: correctly display license status in system info

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#3975]
# Bug Report

## User Story

As a site admin, I want my system info to correctly reflect the license status of my add-ons so that i'm not confused by a notice on the system info that they are inactive.

## Current Behavior
Addons that have been switched to "GiveWP" as the author are showing as unlicensed on the system info.

## Expected Behavior
I expect licensed add-ons to display as such.

## Bug Type
- [x] This bug describes functionality that once worked as expected in a previous version.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install and activate the Give Zapier add-on (release version)
2. Install and activate the Give Stripe add-on
3. Input a valid license key to each of those in the settings/licenses tab and save the settings
4. Navigate to tools > system info
5. Zapier will show as licensed, Stripe will not.

## Acceptance Criteria
- [x] when a license is active on the licenses tab, it shows as licensed on the system info
- [x] when a license is NOT active on the licenses tab, it shows as UNlicensed on the system info
- [x] The solution works for both add-ons marked as "GiveWP" for the author and "WOrdImpress" for the author.

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://livegive.wpsteward.com
Site URL: https://livegive.wpsteward.com
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_8138bfdc07_
Table Prefix Length: 14
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: livegive.wpsteward.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.37 (Unix) OpenSSL/1.0.1f
PHP Version: 7.3.1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
PHP Max Upload Size: 512 MB
cURL Version: ❌ 7.35.0, OpenSSL/1.0.1f - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.4.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation❌Donation Receipt❌New Offline Donation❌Offline Donation Instructions❌New User Registration❌User Registration Information❌Donor Note✔Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.3.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://livegive.wpsteward.com/donation-confirmation/
Failure Page: –
Donation History Page: https://livegive.wpsteward.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, PayPal Payments Pro, Stripe + Plaid, PayPal Standard, Authorize.net, Authorize.net eCheck (ACH), Mollie Gateway
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #1626 ( 7G231521RB710244C ) on 12/28/2018 at 19:40. Status N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by GiveWP – 1.4.5
Give - Currency Switcher: ❌ Unlicensed – by GiveWP – 1.3.1
Give - Fee Recovery: ❌ Unlicensed – by GiveWP – 1.7.4
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.1
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by GiveWP – 1.2.2
Give - MailChimp: ❌ Unlicensed – by GiveWP – 1.4.3
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.4.2
Give - Mollie Gateway: ❌ Unlicensed – by GiveWP – 1.2.1
Give - PayPal Pro Gateway: ❌ Unlicensed – by GiveWP – 1.2.1
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 2.3.2
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.8.3
Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.3
Give - Tributes: ❌ Unlicensed – by GiveWP – 1.5.2
Give - Zapier: ✔ Licensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Ben's Helper Functions: by BenUNC –
Better Click To Tweet: by Ben Meredith – 5.7.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.4.1
Query Monitor: by John Blackbourn & contributors – 3.2.2
User Switching: by John Blackbourn & contributors – 1.4.0
WP Crontrol: by John Blackbourn & contributors – 1.6.2

### Inactive Plugins ###

Email Cop: by Ashfame – 0.1.1
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.3.1
Give - Database HealthCheck: by WordImpress – 0.0.2
Give - Email Reports: by WordImpress – 1.1.2
Hello Dolly: by Matt Mullenweg – 1.6
Loco Translate: by Tim Whitlock – 2.2.0
WordPress Event Ticketing: by Tickera.com – 3.3.2

### Active MU Plugins ###

api-hacks.php: by  –
per-form-currency.php: by  –

### Theme ###

Name: Twenty Seventeen
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

bonus image from that install:
![screen shot 2019-01-30 at 8 22 41 am](https://user-images.githubusercontent.com/9629102/51984015-42f40d80-2468-11e9-961d-233c70fad2e9.png)

</details>

**Comment by mathetos** [comment]
I have a user who is experiencing this issue, but they are claiming that it also leads to being unable to update the Addons. This is also the Microsoft Server issue that I've mentioned in Slack as well, so that might be related. 

https://secure.helpscout.net/conversation/785082854/34873?folderId=672201
