### ISSUE TITLE
fix: "state" text appearing twice on donor detail screen

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3995]
# Bug Report

## User Story
As an admin, I want to see uncluttered donor detail screen.

## Current Behavior
![image](https://user-images.githubusercontent.com/1784821/52461192-f315f480-2b93-11e9-91e4-e3262665c838.png)

## Expected Behavior
`State` tag must appear only once.

## Bug Type
- [x] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria
- [x] Research from where the code for donor is implemented
- [x] Found the cause with html element for text field.
- [x] `State` text appearing only once on donor detail screen under `Addresses` metabox.
- [x] Try changing the base country to US, UK, and India to ensure that issue is fixed.

**Comment by mehul0810** [comment]
@ravinderk Can you add `System Info` in the WP instance where you can reproduce the issue. I'm unable to reproduce the issue with `master` as well as `release/2.4.2` after running `npm run dev`.

**Comment by ravinderk** [comment]
Slack Chat Summary

Participants: @mehul0810 @ravinderk 
Topic: How we can reproduce this issue
Result: We were able to reproduce this issue when the base country set as `United Kingdom`.
