### ISSUE TITLE
feat: add per form confirmation message

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3998]
# Feature Request

## User Story

As a Give admin, I want to display a message on the Donation Confirmation page that is specific to the donation form that the donor donated with. 

For example, I might have 3 different forms for a Dog shelter, each form for a different Dog who needs surgery. When donors give to "Dog A" I want to be able to provide unique information before the Donation Confirmation table about that campaign and how their donations help "Dog A" specifically. This applies equally to "Dog B" and "Dog C" as well of course. 

## Possible Solution

It would require the following:

*METABOX* 
A new metabox on the Form Edit screen would say "Confirmation Message"

That metabox tab would hold the following options:

* Enable/Disable
* WYSIWYG Editor for the message
* Message Position: Before/After Donation Receipt Table

*DONATION RECEIPT LOGIC*
The information from the form edit screen can be saved simply as post meta. Then when the donation is completed, the Donation Receipt template has a before/after hook already. The information can be show in its place once the receipt is loaded over ajax. 

*EMAIL TAG*
Optionally, an email tag `{donation_confirm_message}` could be created to display this message in the Donation Confirmation email as well. 

## Related

- [Customer Request](https://secure.helpscout.net/conversation/771491927/33908?folderId=672197)

While there is only one specific customer request currently, if I think back to other customers who have wanted to use our custom redirect snippet for going to different donation confirmation pages, each of them generally just want to show unique content on that page based on the form that was donated to. So this feature would serve a wide variety of past requests. 

## Acceptance Criteria

- [ ] The metabox tab appears on the form edit screen with the above options
- [ ] When the settings are set correctly, the message appears on the donation confirmation page and in the right position.
- [ ] Ideally, this information is NOT passed as donation meta, but only stored as post_meta for display purposes on the Donation Confirmation page only. 
- [ ] The email tag displays the message in the email correctly.

**Comment by mathetos** [comment]
This is a simple functionality plugin showing how this could work:
https://github.com/impress-org/give-per-form-confirmation-message

**Comment by ravinderk** [comment]
@mathetos I think per success page make more sense to me because in this way admin will get more control over how their confirmation page. Maybe we can provide both because sometime admin wants only few change in confirmation message.

ref: https://github.com/impress-org/give/issues/3643

**Comment by mathetos** [comment]
This provides customization while keeping just one donation confirmation page, which I think is preferable. It's a much harder workflow for the user to create both one form and one confirmation page.

**Comment by kevinwhoffman** [comment]
Blocking until Matt, Devin, and I discuss on next Product Management call.

**Comment by kevinwhoffman** [comment]
## Slack Call Summary

Participants: @DevinWalker @mathetos @kevinwhoffman 
Topic: Best way to implement per form confirmation messages
Result: We considered the following possibilities:

- Option A: Customizable message field in the form editor (content is entered in the form editor).
- Option B: Page selector field in the form editor (content is entered in page and then selected in form editor).

Also discussed best method of release:

- Free plugin hosted on WP.org
- Free plugin hosted on givewp.com
- Paid add-on with a similar scope to Per Form Emails or Per Form Gateways

### Next Steps

@DevinWalker is going to look into the technical complexity of the issue to see how difficult it would be to implement option A or B above. We will revisit the best release method after that.

**Comment by mathetos** [comment]
I just discovered another important reason why we should go with the route @ravinderk suggested, of per-form donation confirmation PAGES. Multi-language support. Several popular multi-language plugins set the language per page, and in order for Give to show the Donation Confirmation page in the right language, there has to be a FORM per LANGUAGE and a DONATION CONFIRMATION PAGE per LANGUAGE as well. 

See this free ticket for full explanation:
https://wordpress.org/support/topic/confirmation-page-showing-in-wrong-language/#post-11242488

**Comment by mikejhale** [comment]
Closed as we will be adding a per form thank you page in the new Campaign builder
