### ISSUE TITLE
fix: support date formats with translated strings

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#4000]
# Bug Report

## User Story
As a site admin for sites with a default format of `j F Y` (many European users), I want to be able to add and change the date on donations. 

ref: https://github.com/impress-org/give-manual-donations/issues/141

## Current Behavior
When you try to update the date on the resulting donation it will only save as today's date.

## Expected Behavior
I expect to be able to update the donation date with the correct historical date.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Set language to (`fr_FR`)
2. Change the date format at Settings > General to `j F Y`
3. Attempt to create a donation (any date will replicate the problem)
4. On the resulting donation, attempt to change the date
5. It won't work.

## Acceptance Criteria
- [ ] Donations updated that date format work as expected
- [ ] The fix does not affect donations added in other date formats

**Comment by kevinwhoffman** [comment]
@ravinderk I think the cause of the issue needs clarified. As I discovered in the [related WPBR issue](https://github.com/impress-org/wp-business-reviews/issues/251#issuecomment-429405566), the problem is not so much the `j F Y` format but rather the presence of a translated string in the date.

I am copying my explanation here for reference:

> The `j. F Y` format worked fine as a custom format with `English (United States)` site language. However I was able to replicate the error once I changed the site language to `Deutsch`.
>
> The cause of the error is not any specific format, but rather any format that includes translated words as opposed to numbers. For example, I replicated the error on a `Deutch` site using both `j. F Y` and `F j, Y` formats, whereas `m/d/Y` worked fine because it did not include a translated word like `Oktober`.

Also updating the issue title for clarity.

**Comment by ravinderk** [comment]
@kevinwhoffman I found that we are using  `datepicker` in the following places:
1. Donor listing page
2. Donation listing page
3. Form listing page
4. Donation detail page
5. Export page
6. Export donation history page
7. Addon:
    1. Gift Aid
    2. Recurring

@kevinwhoffman Fix can affect third party code if they are expecting a date in WordPress format.
