### ISSUE TITLE
fix: ensure logged-in users without donor accounts can donate

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#4039]
# Bug Report

## User Story

As a logged-in WordPress user, I want to donate without getting an `Invalid Email` error so that my donation completes as expected.

## Current Behavior

When I am logged in with `admin@example.com` and attempt a donation using that email or any other email, I receive the following error:

`Error: Invalid email.`

@mathetos said:

> On a fresh install as long as my login is NOT a donor I cannot donate at all. Once I manually created a donor associated with the logged in user I was able to donate no problem

## Expected Behavior

As a logged-in user, I should be able to donate with the primary email address associated with my account.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.4.1.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. With Give 2.4.2 installed, create a new Give form with default settings.
2. Attempt to donate while logged in.
3. See `Error: Invalid email.`
4. If you try the same donation while logged out, the donation will succeed and create a new donor account with that email.
5. If you go into the donor profile and manually connect the donor account to the WP user account, then future donations work as intended.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/54292181-20373780-4584-11e9-8320-cfd688264965.png)

## Possible Solution

Investigate whether the work done to resolve https://github.com/impress-org/give/issues/4025 caused this issue.

## Related

https://github.com/impress-org/give/issues/4025
https://wordpress.org/support/topic/invalid-email-error-2/

## Acceptance Criteria

- [x] On a fresh install, a WordPress user with `admin@example.com` can successfully submit a donation even if they do not yet have a donor account.
- [x] The same email `admin@example.com` can be used to donate when logged out and the donation is correctly associated with the existing donor account.
- [x] Case-insensitive versions of the email `ADMIN@example.com` allow the donation to be associated with the existing donor account.
- [x] An error appears if a logged-in donor tries to donate with the email of an existing donor.
- [x] A new donor can donate and register a WP user account when Login + Registration is enabled.
- [x] An existing donor can log in and complete a donation when Login is enabled.
- [ ] An error appears if a logged-in donor tries to donate with the email of an existing WP user. (Team agreed to resolve this in later release)

**Comment by DevinWalker** [comment]
Closing as all points are addressed in PR #4040 besides the last one which is already discussed in an existing issue.
