### ISSUE TITLE
fix: prevent warning in System Info host detection

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#4041]
# Bug Report

## User Story

As a user, I want to view and copy my System Info without errors so that I can provide accurate information to support.

## Current Behavior

Currently the condition for Bluehost detection is causing a warning if a host is not detected before the switch statement gets to Bluehost.

## Expected Behavior

The switch statement should continue processing through to the default case.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. View system info screen in Give 2.4.2 in a local dev environment.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/54305208-2f76af00-459d-11e9-81c6-fd33cc5e03e2.png)

## Possible Solution

Correct the use of `preg_match()`.

## Related

#3356

## Acceptance Criteria

- [ ] There are no errors when System Info is viewed in a local environment.
- [ ] There are no errors when System Info is viewed in a production environment.

**Comment by DevinWalker** [comment]
Resolved in PR #4042
