### ISSUE TITLE
feat: add support to automate webhooks creation

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#4051]
@mehul0810 commented on [Wed Dec 12 2018](https://github.com/impress-org/give-stripe/issues/374)

# Bug Report

## User Story
As a user, I want to automatically create a webhook for my site, if one doesn't exist so that it will be an easy on-boarding process for every user.

## Related
- https://stripe.com/docs/api/webhook_endpoints

## Acceptance Criteria
- [x] Research on implementing the WebHook Automation
- [x] Planning Basic implementation strategy
- [x] Update Stripe Version https://github.com/impress-org/give-stripe/issues/381
- [x] Remove Deprecated Stripe SDK Code
- [x] Add Webhook status check settings field in admin
- [x] Make sure webhook is set properly when Stripe add-on is activated
- [x] Show Webhook status under Stripe Settings
- [x] If somehow, webhook not set automatically. Provide a link on clicking it will set the webhook for the user.
- [x] Process one-time as well as recurring donations after setting the webhooks automatically.
- [x] Migrate this feature to Stripe Core
- [x] Ensure that we use cron to check the webhook status regularly
- [x] Testing

---

@mehul0810 commented on [Mon Jan 07 2019](https://github.com/impress-org/give-stripe/issues/374#issuecomment-451915347)

@DevinWalker I've done some research and basic implementation on this issue. But, I've noticed that we need to update the Stripe PHP SDK version from `5.9.2` to `6.20.0` or `latest` to support automating the WebHook Endpoints and doing so will drop support of Stripe add-on for PHP version `5.3` Let me know what do you think about the same.

**Ref:** https://github.com/stripe/stripe-php (Check releases section for version 	6.20.0)

---

@mathetos commented on [Mon Jan 07 2019](https://github.com/impress-org/give-stripe/issues/374#issuecomment-452011151)

@DevinWalker My vote is to update. WordPress as a whole is pushing for PHP 7.0 minimum support. While we DO have customers on 5.3 it is VERY rare. 

---

@kevinwhoffman commented on [Wed Jan 09 2019](https://github.com/impress-org/give-stripe/issues/374#issuecomment-452579396)

Per dev team call, we will move forward with updating the Stripe SDK.

**Comment by mathetos** [comment]
Thanks for making this issue @mehul0810 We also had a conversation in Slack about the percentage of our users using older PHP versions. Here's my data from that:

~~~~~~~~~~~~
I know there's been some convo of dropping support for older versions of PHP. I wanted to just put together the data we have on customer PHP versions based on HelpScout tickets to inform that decision.

Keep in mind this is total conversations, not individual sites or customers. Also keep in mind that this is only those who provided their System Info for us -- not all provide this info, but the majority do.

Here's what HelpScout says:

5.3 == 71
5.4 == 265
5.5 == 152
5.6 == 1,911
*Total less than 7.0 == 2399*

7.0 == 1352
7.1 == 518
7.2 == 339
*Total at 7 or higher == 2209*

That means more than half our customers are on a version older than 7.0 with 5.6 being the most popular version. This data isn't perfect, but it's the best we have currently without true in-plugin telemetry.
~~~~~~~~~~~~~~~~~~~~~~

This means that currently roughly 8% of our users are are a version older that PHP 7.0. But far less than that are on versions older than 5.6

Just data to help inform our discussions about this important issue.

**Comment by mehul0810** [comment]
@mathetos This issue already existed in Stripe repository. Now, I've moved it to Give as the automated webhooks should be part of Stripe Core. This feature is almost completed just need to polish some areas to make sure that the webhooks are set in every scenario because payment intents require webhooks to be set to complete the donation. 

To support automated webhooks, we're only dropping support for PHP `5.3`. So, the minimum PHP version supported will be `5.4` as per the discussion around this issue on earlier dev call.

**Comment by mehul0810** [comment]
@DevinWalker I want to discuss this issue as there is a challenge in achieving this issue with Connect API. Can we discuss this issue tomorrow morning?

**Comment by mehul0810** [comment]
This issue is complete as per the discussion with Devin.

**Here are some screenshot on how webhooks are implemented:**
1. on Stripe settings page
![image](https://user-images.githubusercontent.com/1852711/56179572-cf53ac80-6023-11e9-9478-4e5cdc994483.png)

2. on System Info page 
![image](https://user-images.githubusercontent.com/1852711/56179586-e0042280-6023-11e9-87de-f9c49d1119a2.png)

Hence, closing this issue
