### ISSUE TITLE
feat: filter Donation Form Grid block by category/tag slug

### ISSUE THREAD

**Issue by amandagorman** [impress-org/give#4056]
# Bug Report

## User Story

As an admin, I want to be able to filter my forms by category when creating a Donation Form Grid Block so that only the forms under a specific category will display in my form grid.

## Current Behavior

Currently, when I enter the category name to filter my donation form grid, all of my forms still display in the form grid instead of filtering my the indicated category. When I filter by tags, the forms do in-fact filter correctly. 

## Expected Behavior

I expect that when I indicate a category that my donation form grid block will filter by that specific category, rather than display all of my forms.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Create a category and apply the category to some donation forms.
2. Build a Donation Form Grid Block and use the category name in the form grid settings to filter. 
3. See that all donations forms display instead of being filtered by category.

## Acceptance Criteria

- [x] When a category slug ( with backward compatibility to cat ID ) is selected, only forms within that category display in the grid.
- [x] When a tag slug ( with backward compatibility to tag ID ) is selected, only forms within that tag display in the grid.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by kevinwhoffman** [comment]
@amandagorman I have reviewed the functionality and both the Category and Tag filters require numerical IDs to be passed in order for the filters to have any effect. The slug or category name is not currently supported. This is noted in the [Form Grid documentation](https://givewp.com/documentation/core/shortcodes/give_form_grid/).

I've labeled this as a feature request since it is not a bug with the documented functionality.
