### ISSUE TITLE
fix: style conflict with visual composer on donation detail page

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#4064]
# Bug Report

## User Story
As an admin, I want to see well-formatted donation details on the donation history page.

ref: https://secure.helpscout.net/conversation/793091260/35410?folderId=848135

## Current Behavior
I am seeing an unexpected border under donation detail meta box which looks cluttered.

## Expected Behavior
See donation detail page without any border around donation information

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install visual composer
2. Visit any donation detail page

## Visuals
![image](https://user-images.githubusercontent.com/1784821/55052354-a1132a80-507e-11e9-83f9-5586c0c06929.png)

## Possible Solution
Use modify general classes name with `give-` prefix.

## Acceptance Criteria
- [ ] I am not see any border around donation information when visual composer installed.
- [ ] `column` class changed to `give-column`.

## Environment
Visual composer 2.3

**Comment by mikejhale** [comment]
@ravinderk What specifically do you mean by "visual composer"? Can you explain how you are set up and how to reproduce?

**Comment by mikejhale** [comment]
Could not reproduce.  Tested with WP Bakery (formely visual composer) and Visual Composer (free).
