### ISSUE TITLE
fix: prevent fatal error when click on resend receipt

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#4068]
# Bug Report

## User Story
As an admin, I want to resend receipt without any failure.

ref: https://secure.helpscout.net/conversation/796694823/35676?folderId=848135#thread-2266009265

## Current Behavior
I am getting a fatal error when click on resend receipt.
![image](https://user-images.githubusercontent.com/1784821/55210697-c20a8580-520e-11e9-8f97-93a163b418eb.png)
![image](https://user-images.githubusercontent.com/1784821/55210707-cd5db100-520e-11e9-94a3-12c67d1e6d78.png)

## Expected Behavior
Resend receipt without any fatal error.

## Bug Type
- [x] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Add `{donation_history_link}` or `{subscriptions_link}` [or both] email to receipt
2. Click on resend receipt button for any of donation
3. you will get an error:
```
Call to a member function set_verify_key() on a non-object in /wp-content/plugins/give/includes/emails/class-give-email-tags.php on line 1238
```

## Visuals
![image](https://user-images.githubusercontent.com/1784821/55210565-ffbade80-520d-11e9-9a25-e2d61dc78d13.png)

## Possible Solution
Above mentioned email tags use `Give_Email_Access` class in logic but after refactoring that class only available only on the frontend, so to prevent fatal error we can load this class as backward compatibility on specific resend receipt event [ either bulk or single]

To prevent fatal error we can load this class for this email tag code.
ref: https://github.com/impress-org/give/issues/3871

## Acceptance Criteria
- [x] Resend receipt button is working fine when receipt email contains `{donation_history_link}` email tag.
- [x] Resend receipt button is working fine when receipt email contains `{subscriptions_link}` email tag.

**Comment by Benunc** [comment]
Another user reported the same issue with offline donations. To reproduce:

1. Add the `{donation_history_link}` tag to the donation dreceipt email.
1. Submit an offline donation from the front end
1. Manually mark the donation as complete on the back end.

Error!

**Comment by ravinderk** [comment]
@Benunc I reviewed the above issue and confirming that it will be fixed by https://github.com/impress-org/give/pull/4069

**Comment by ravinderk** [comment]
Note: I can reproduce same with `subscriptions_link` email tag from recurring addon. I updated acceptance criteria of this issue.
