### ISSUE TITLE
fix: Give API returns inconsistent amount formats

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#4073]
# Bug Report

The current version if the Give API has inconsistent amount formatting for multiple keys.

![2019-04-02_01-38-38](https://user-images.githubusercontent.com/1571635/55388581-64b15580-54e8-11e9-90c7-45345a8044f0.png)

1. Some amounts have six decimals 
2. Some amounts are strings and others like `total` are integers
3. The amounts don't respect other currency formats.
4. Add-ons like Fee Recovery also have six decimals `"_give_fee_donation_amount": "100.000000"`

## User Story

As a Give admin who wants to use Zapier, I want clear amount formatting within the API so that I can set properly pipe the data in need.

## Possible Considerations

1. Is there a standard for APIs to return amounts? 
2. What does Stripe and WooCommerce return for their amount fields?
3. Should some of the duplicate 

## Bug Type
- [x] This bug describes functionality that never worked as expected.

**Comment by ravinderk** [comment]
![image](https://user-images.githubusercontent.com/1784821/55456877-d03d1500-5605-11e9-8a67-2d7e75ceb302.png)
http://woocommerce.github.io/woocommerce-rest-api-docs/?php#list-all-orders


![image](https://user-images.githubusercontent.com/1784821/55457315-337b7700-5607-11e9-9ea8-e3956bebfe40.png)
https://stripe.com/docs/api/plans/object


@DevinWalker As we can see Woocomerce output price item as string and form them as per number of decimal set in woocommerce setting while stripe output amount as  float.

As we discussed we can output price as Woocommerce doing
