### ISSUE TITLE
fix: resolve exporter not respecting category or tag filters

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#4085]
# Bug Report

## User Story

As a site admin, I want to export only donations to forms in particular categories or with particular tags.

## Current Behavior
Currently, selecting a particular category or tag does not change anything about the exported CSV. 
## Expected Behavior
I expect when selecting a category or tag filter that only donations to those forms would export.

## Bug Type
- [x] This bug describes functionality that once worked as expected in some previous version.

## Steps to Reproduce
1. Create a fresh test site
2. Import the sample data csv using the impter tool at Donations > Tools > Import > Import Donations and then use the sample CSV that ships with give in the `give/sample-data/` directory. 
3. Enable Form Categories and tags at Donations > Settings > Display Options > Taxonomies
4. Add a category to the first two Forms created at Donations > All Forms
5. Export DOnation history at Donations > Tools > Export > Export DOnation History
6. Select the newly created tag/category as a filter.

Whether you add it or not, the filter make no difference.

## Related
https://secure.helpscout.net/conversation/821572784/37177?folderId=848135

## Acceptance Criteria
- [x] the category filter works 
- [x] the tag filter works
- [x] using no filter works
- [x] using the two filters combined works

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://samdestroysthings.local
Site URL: http://samdestroysthings.local
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: samdestroysthings.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.4.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://samdestroysthings.local/donation-confirmation/
Failure Page: http://samdestroysthings.local/donation-failed/
Donation History Page: http://samdestroysthings.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Theme ###

Name: Twenty Nineteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by ravinderk** [comment]
Note: This commit is the cause of this issue: https://github.com/impress-org/give/commit/e44934648b02fd027bc7a45d32f6eee70f098e95
