### ISSUE TITLE
fix: improve frontend testing using puppeteer

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#4111]
# Bug Report

## User Story
As a developer, I want to improve frontend testing using Puppeteer so that we can leverage the best testing benefits.

**Video from Google io19:** https://www.youtube.com/watch?v=MbnATLCuKI4

## Benefits
- Processing donations with other gateways.
- Ensuring that intercepting the donation will make the donation fail.
- Adding tests to check on Firefox as Puppeteer now supports Firefox.
- Ensuring the after processing donation the donation existing in admin with its proper status.
- Utilizing the frontend testing with all our popular add-ons to take benefit.
- Test with incognito mode.
- Don't sleep for a specific time during tests. Puppeteer has a better solution to it.
- Adding Accessibility Tests to ensure Give is accessible to everyone.

## Current Behavior
Currently, we are using most of the tests to see the existence of the tooltips and its hover effect, buttons, and much more. Also, we have a few interactive tests which process a test donation.

## Expected Behavior
I expect to leverage the benefits of Puppeteer for testing

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Related
- https://pptr.dev/

**Comment by mikejhale** [comment]
Will be addressed in new optimized build process
