### ISSUE TITLE
Remove redundant code in give_tribute_tag_donor_message

### ISSUE THREAD

**Issue by denisjacobi** [impress-org/give#4121]
# Bug Report

## Current Behavior
In Tribute Plugin version 1.5.3 there is a redundant variable assignment in function give_tribute_tag_donor_message() in includes/admin/class-give-tributes-tags.php

Line 745 & 748 are identical:
```
$ecard_or_mailed  = give_get_meta( $payment_id, '_give_tributes_would_to', true );
$notify_full_name = '';

$ecard_or_mailed  = give_get_meta( $payment_id, '_give_tributes_would_to', true );
```

## Expected Behavior
$ecard_or_mailed only assigned once. 

## Bug Type

- [ ] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria

- [ ] Redundant code removed

## Environment

Tribute Plugin version 1.5.3

**Comment by ravinderk** [comment]
Issue moved to [impress-org/give-tributes #291](https://github.com/impress-org/give-tributes/issues/291) via [**ZenHub**](https://www.zenhub.com/)
