### ISSUE TITLE
fix: adjust positioning of invalid license alert

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#4128]
# Feature Request

## User Story

As a Give admin, I want that the admin alerts look nice an aligned on all Give settings screens.

## Visuals

![image](https://user-images.githubusercontent.com/930724/59122497-c25e8580-890f-11e9-84e7-1db3698d1229.png)

## Possible Solution

It's a tough one, but possibly making them `inline-block` but when there are multiples I think it gets even more messy...

![image](https://user-images.githubusercontent.com/930724/59122645-24b78600-8910-11e9-8554-9253ceeefa52.png)

**Comment by DevinWalker** [comment]
@mathetos inline looks funny and won't stack well. What about:

![2019-06-07_19-42-31](https://user-images.githubusercontent.com/1571635/59122989-77b72a80-895c-11e9-890b-fb6e66e9e24f.png)

Also we can use this issue to QA all notices in `2.5.0` if we find any other strange positioning.

**Comment by mathetos** [comment]
That would be more ideal, I just wasn't sure whether it was feasible.

**Comment by DevinWalker** [comment]
@mathetos I fixed this issue. Please reopen if you find any other notices gone awry.
