### ISSUE TITLE
fix: remove the word "nonce" from all front end error messages.

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#4129]
# Bug Report

## User Story

As a donor or site admin, I want error messages that are helpful and inoffensive so that I can take action to resolve the problem.

In the UK (at least) the word `nonce` is slang associated with concept of pedophilia.

## Current Behavior
There are several places in the Give Core Code as well as add-ons that the word `nonce` is used in the front-end output of an error. So in addition to it not being helpful (a donor has no idea what `Nonce verification failed` means or the steps to resolve the problem), it can be offensive to see a slang term displayed.

## Expected Behavior
I expect any error message to point to what specifically is going wrong, and how the reader of the error message can resolve the issue. 

I expect that a site administrator or support technician would know exactly where in the code the error message is coming from to be able to resolve it quickly.

I expect there to be no offensive terminology in error messages.
## Bug Type
- [x] This bug describes functionality that never worked as expected.

## Steps to Reproduce
1. Browse the code searching for the word `nonce` in translatable/echoed strings. 
2. See that many of them are similar to one another, but slightly different in terms of precisely the same string.

## Possible Solution
Make a list of each error message, and explain in layman's terms what is actually happening to cause the error message.
Create error messages that allow the Donor, User, and Support technician to all take necessary action.

## Related
https://secure.helpscout.net/conversation/873431370/41330/

## Acceptance Criteria
- [ ] the word `nonce` is never output on the front end or back end of the site.
- [ ] All error messages have a unique identifier, eg `Error 38: session issues. Please contact _______`
- [ ] All error messages have a next step for the reader of the message.

**Comment by mathetos** [comment]
We have some strings that are totally redundant and should be combined:
- [ ] "Nonce verification failed."
- [ ] "Nonce verification has failed." 

Some of these are on the admin side, others are frontend. Here's what I suggest:

> We're unable to recognize your session. Please refresh the screen to try again; otherwise contact your website administrator for assistance.

I think this covers the issue and provides action to be tried accurately whether it's on the admin or visitor-facing side. Let's just make sure it's consistent with in all instances so we don't double translators efforts.
