### ISSUE TITLE
fix: display required mark for Panama states

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#4143]
# Bug Report

## User Story

As a SIte owner in Panama, I want the State field to show as required when the page loads with floating labels so that donors do not think that the field is not required.

## Current Behavior
WIth FLoating lables active and the site set to load Panama as the country, the field does not show the asterisk that indicates required. The field still is required, and will error when attempting to donate, but it is not displaying the asterisk. 

Switching from Panama to another country and back will correctly show the asterisk. Switching to non-floating labels will display the asterisk correctly. 

It just doesn't display on initial page load.
 
## Expected Behavior
If a field is required, it should show the asterisk.

## Bug Type
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Set the country to Panama at Donations > Settings > General
2. Require billing info at Donations > Settings > Payment Gateways > PayPal Standard
3. Enable PayPal Standard, and create a form with floating labels enabled.
4. visit the front end of the form.

## Related
https://secure.helpscout.net/conversation/881548626/41904?folderId=672194

## Acceptance Criteria
- [x] floating labels on non-dropdown state lists still show as required on page load.

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://samdestroysthings.local
Site URL: http://samdestroysthings.local
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: samdestroysthings.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.4.7
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note❌Email access
Upgraded From: 2.4.6
Test Mode: Disabled
Currency Code: USD
Currency Position: After
Decimal Separator: .
Thousands Separator: ,
Success Page: http://samdestroysthings.local/donation-confirmation/
Failure Page: http://samdestroysthings.local/donation-failed/
Donation History Page: http://samdestroysthings.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Disabled

### Inactive Plugins ###

WPForms Lite: by WPForms – 1.5.2.3

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by ravinderk** [comment]
Resolved.

![PKhgTAMWHn](https://user-images.githubusercontent.com/1784821/59653991-e5135880-91b1-11e9-9738-6108bf8f7703.gif)

**Comment by ravinderk** [comment]
@Benunc I am open a new issue which I found while developing this: https://github.com/impress-org/give/issues/4144

cc: @DevinWalker

**Comment by Genevieve-K** [comment]
Thank, it works.
