### ISSUE TITLE
Fix: make styles show when a site has been localized to a non-english language.

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#4146]
# Bug Report

## User Story

As a site administrator of a site in French (for example), I want the Settings > Email page to display styles correctly.

## Current Behavior
When a site is in French, the styles on the emails page of settings do not display correctly.
![Screen Shot 2019-06-19 at 10 34 16 AM](https://user-images.githubusercontent.com/9629102/59774643-d1352880-927d-11e9-980c-2a407f4345ca.png)

## Expected Behavior
I expect the styles to be language-agnostic. 

![Screen Shot 2019-06-19 at 10 35 10 AM](https://user-images.githubusercontent.com/9629102/59774712-ef9b2400-927d-11e9-9431-f08b828874d4.png)

## Bug Type
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install Give.
2. Switch language of the site to French
3. Visit the site updates page to make sure the French localized files for Give download.
4. Visit Donations > Settings > Emails
See the styles not applied to the check marks.

## Possible Solution
prevent the styles from being reliant on English.

## Related
https://secure.helpscout.net/conversation/881548626/41904?folderId=848135

## Acceptance Criteria
- [x] The language change does not affect the styles being applied
- [x] Styles still show in english
- [x] Styles show in a language that Give has not been translated into.

## Environment
<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: https://livegive.wpsteward.com
Site URL: https://livegive.wpsteward.com
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_8138bfdc07_
Table Prefix Length: 14
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: livegive.wpsteward.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.39 (Unix) OpenSSL/1.0.1f
PHP Version: 7.1.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
PHP Max Upload Size: 512 MB
cURL Version: ❌ 7.35.0, OpenSSL/1.0.1f - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.5.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_8138bfdc07_give_donors -  1.0✔ wp_8138bfdc07_give_donormeta -  1.0✔ wp_8138bfdc07_give_comments -  1.0✔ wp_8138bfdc07_give_commentmeta -  1.0✔ wp_8138bfdc07_give_sessions -  1.0✔ wp_8138bfdc07_give_logs -  1.0✔ wp_8138bfdc07_give_logmeta -  1.0✔ wp_8138bfdc07_give_formmeta -  1.0✔ wp_8138bfdc07_give_sequential_ordering -  1.0✔ wp_8138bfdc07_give_donationmeta -  1.0
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions❌New User Registration✔User Registration Information❌Donor Note❌Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report✔Renewal Receipt Email❌Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Cancelled Email✔Subscription Completed Email✔Subscription Reminder Email❌Subscriptions Email Access
Upgraded From: 2.4.7
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://livegive.wpsteward.com/donation-confirmation/
Failure Page: –
Donation History Page: https://livegive.wpsteward.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, PayPal Payments Pro, Stripe + Plaid, PayPal Standard, Braintree, Offline Donation, Square Gateway
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #2687 ( 55R67687XB9220817 ) on 05/06/2019 at 10:13. Status N/A
Donor Email Access: Disabled
Stripe Webhook Notifications: N/A

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by GiveWP – 1.4.6
Give - Braintree Gateway: ✔ Licensed – by GiveWP – 1.2.4
Give - Currency Switcher: ✔ Licensed – by GiveWP – 1.3.2
Give - Email Reports: ✔ Licensed – by GiveWP – 1.1.3
Give - Fee Recovery: ✔ Licensed – by GiveWP – 1.7.5
Give - Form Field Manager: ✔ Licensed – by GiveWP – 1.4.3
Give - Google Analytics Donation Tracking: ✔ Licensed – by GiveWP – 1.2.4
Give - MailChimp: ✔ Licensed – by GiveWP – 1.4.4
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.4.4
Give - PayPal Pro Gateway: ✔ Licensed – by GiveWP – 1.2.2
Give - PDF Receipts: ✔ Licensed – by GiveWP – 2.3.3
Give - Per Form Gateways: ✔ Licensed – by GiveWP – 1.0.2
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.8.13
Give - Square: ❌ Unlicensed – by GiveWP – 1.0.2
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.1.8
Give - Tributes: ✔ Licensed – by GiveWP – 1.5.4
Give - Zapier: ✔ Licensed – by GiveWP – 1.2.2

### Other Active Plugins ###

Email Cop: by Ashfame – 0.1.1
Page Builder by SiteOrigin: by SiteOrigin – 2.10.6
Query Monitor: by John Blackbourn – 3.3.6
SiteOrigin Widgets Bundle: by SiteOrigin – 1.15.7
Wordfence Security: by Wordfence – 7.3.4

### Inactive Plugins ###

Ben's Helper Functions: by BenUNC –
Disable Gutenberg: by Jeff Starr – 1.8.1
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.3.1
Give - Database HealthCheck: by WordImpress – 0.0.2
Give - Form Countdown: by GiveWP – 1.0.1
Give - Mollie Gateway: by GiveWP – 1.2.1
Give - PayFast Payment Gateway: by WordImpress – 1.0.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.6.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Loco Translate: by Tim Whitlock – 2.3.0
Shortcode in Menus: by Gagan Deep Singh – 3.5
Tickera: by Tickera.com – 3.4.4
User Role Editor: by Vladimir Garagulya – 4.51.1
User Switching: by John Blackbourn & contributors – 1.5.1
WP Crontrol: by John Blackbourn & crontributors – 1.7.1

### Active MU Plugins ###

api-hacks.php: by  –
helpr-mu.php: by  –
per-form-currency.php: by  –

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@DevinWalker this issue has been fixed in `release/2.5.0`. Please check and confirm.

**Comment by DevinWalker** [comment]
Looks good @ravinderk - it's removed for me now. Good catch 👍

**Comment by DevinWalker** [comment]
I also confirmed the language and styles work as expected with WP_DEBUG as `false`.
