### ISSUE TITLE
fix: remove deprecated notice for gutenberg block

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#4151]
# Bug Report

## User Story
As a user, I want to ensure that the Gutenberg blocks of Give doesn't show any warnings for deprecated functions so that it works properly with future version of Gutenberg.

![image](https://user-images.githubusercontent.com/1852711/60148498-f7fbdd80-97ee-11e9-9719-85dd3682da8f.png)

## Current Behavior
Currently, this console notices appears when the Gutenberg plugin is installed with version 5.9.2

## Expected Behavior
I expect to see no console notices to ensure that the Give blocks are future proof

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install Give and Gutenberg plugin in latest WP version instance
2. Create a donation form
3. Create a new page and add Give Form block
4. Notice the console with deprecated notices.

## Related
- https://github.com/impress-org/give/issues/4137

## Acceptance Criteria
- [x] Ensure that the deprecated functions are replaced with new ones.
- [x] Ensure that all the Give blocks are working fine.

**Comment by DevinWalker** [comment]
Fix merged in PR #4199
