### ISSUE TITLE
fix: improve overall admin notices and its jumpy behaviour in Give core

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#4155]
# Bug Report

## User Story
As a user, I want to remove the jumpy behaviour of admin notices which is quite frustrating so that it provide better UX.

## Current Behaviour
Currently, When any admin page is loaded Give notices are first hidden and then slides down after couple of seconds which holds user to wait for sometime before clicking. 

## Expected Behaviour
I expect to create a delightful experience with admin notices.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Visuals
**Jumpy Behaviour of current Give admin notices**
![gif](http://g.recordit.co/dSwB3aL2rL.gif)

**Video  by Ravinder about Toast notices as proposal**
https://www.loom.com/share/6c363afdd9f6477bb9c21c8b40e02f67

## Related
- https://givewp.slack.com/archives/C0FAGC83C/p1561701330050200

I've tested the @ravinderk toast notice feature branch (i.e. https://github.com/impress-org/give/tree/feat/toast-notice) and it is working fine except few user scenarios where Square and Stripe add-on has connect button.

## Further Suggestions with UI improvement
1. Auto hide toast notice after 5 seconds
2. All the toast notice should be dismissible
3. On reloading page, relevant notice will reappear for 5 seconds. For example, invalid license notice
4. When notices are dismissed, relevant dismissal function will call and the notice is dismissed for specific interval. This will apply to dismiss all button as well
5. Hide All button will hide the notices and show the notification center icon as per the screenshot suggested by Ravinder
6. By default, notices will not be hidden under notification center icon. Notification center icon will display only when the Hide All button is clicked

![image](https://user-images.githubusercontent.com/1852711/60333767-83c06600-99b7-11e9-84c7-510a5c1ab48c.png)

**Comment by ravinderk** [comment]
Adding example of auto dismissible notices with the progress bar.

![ZXDZEZJadw](https://user-images.githubusercontent.com/1784821/60360583-a07d8d80-99f9-11e9-95d5-5ad9242517d5.gif)

**Comment by mikejhale** [comment]
Closed in favor of new Notification center
