### ISSUE TITLE
Display Type not working in From Grid View

### ISSUE THREAD

**Issue by flack** [impress-org/give#4159]
# Bug Report

## User Story
I want to be able to click on a form in the grid and be taken to the page (i.e. "Redirect" option in Display Type). 

## Current Behavior
No matter what I configure, clicking a form in the grid view always opens the modal

## Expected Behavior
If I select vDisplay Type Redirect, I expect it to redirect

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Add "Give Donation Form Grid" block to any page
2. In the block settings, select "Redirect" for Display Type
3. Go to the frontend, click on anything in the form grid, and see that a modal opens instead

## Possible Solution

Not a possible solution, but a possible cause:

https://github.com/impress-org/give/blob/release/2.5.0/includes/shortcodes.php#L776

You see that the key is `display_style`, but the key passed into this functions (from the saved block settings) is called `display_type`. So it is impossible to overwrite the default value currently

## Acceptance Criteria

- [ ] Display Type setting should actually have an effect in the frontend 

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Ubuntu</li>
        <li>Version: 19.04</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    5.2.2
</details>

**Comment by ravinderk** [comment]
@flack Thank you for creating an issue. Fix will be part of Give `2.5.0`.

**Comment by flack** [comment]
@ravinderk thank for the quick fix! I applied your patch locally, and now the "Redirect" option works. However, the "Modal" option does not work any more. If I select it, in `templates/shortcode-form.php` the value is `modal`, and not `modal_reveal`. do I need to empty a cache or something for this to work also?

**Comment by ravinderk** [comment]
@flack Please run `npm run dev` first to recompile JS file to test, because as you can see I made changes in JS file as well: https://github.com/impress-org/give/commit/8ba189edd89dec5b2ccf7950e4f151fb6bef933d

For more information, you can review readme file https://github.com/impress-org/give#npm-commands

**Comment by flack** [comment]
@ravinderk alright, cool, that fixed it. Thx!
