### ISSUE TITLE
fix: improve licensing workflow when transitioned to Give 2.5.0

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#4160]
# Bug Report

## User Story
As a user, I want to ensure that transitioning my add-on licenses when switched to Give 2.5.0 works fine  so that it will be a consistent UX.

## Current Behavior
There are some add-on licenses not transitioning properly

Affected add-ons are:
1. Mollie
2. Moneris
3. Square
4. Sofort: In add-on version `1.0` plugin URL is pointing to Github instead of `givewp` that why this plugin excludes from license list and license upgrade process too. @DevinWalker made required changes but still need to release add-on version `1.0.1` 
ref: https://github.com/impress-org/give-sofort/blame/master/give-sofort.php

Also, Give Core is shown as licensed add-on instead of free plugin under licenses tab.

## Expected Behavior
I expect to transition the add-on licenses properly

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Visuals
Video Link: https://www.loom.com/share/cce7250e8b4b4cb88b845cc633e62442

## Acceptance Criteria
- [x] Ensure that transitioning licenses is a smoother experience
- [x] Testing

**Comment by ravinderk** [comment]
@mehul0810 Good catch. Above mentioned add-ons were excluded from the license upgrade process because of the difference between item name and plugin slug. I updated logic to handle these scenarios.

![image](https://user-images.githubusercontent.com/1784821/60607685-62a6ad80-9ddb-11e9-90b3-920eaaa77ac3.png)

**Comment by mehul0810** [comment]
@ravinderk Additionally, I've counted the licenses list in Give 2.5.0 as shown in the video above and noticed that few add-ons are not listed.
1. Sofort
2. Payfast
3. Americloud Payments
4. Razorpay
5. Paytm
6. Payumoney

**Comment by mehul0810** [comment]
## Slack Call Summary
Participants: @mehul0810 @ravinderk 
Topic: Discussion about the above comment
Result: Ravinder explained why some of the add-ons are not listed on licenses page after transitioning to Give 2.5.0 due to the URL linked to the add-on has GitHub URL and AmeriCloud gateway has author as AmeriCloud Inc which is causing issue. So, we concluded a workaround as checking the add-ons in the add-on page feed of givewp.com to ensure that the list is loaded properly

**Comment by ravinderk** [comment]
@mehul0810 @DevinWalker 
As I found that few add-ons' plugin URI still points to `github.com` and in edge case neither author set to `GiveWP` or `WordImpress` for example: `Give - AmeriCloud Payments`.

I updated logic to find premium add-ons. I reused add-ons feed HTML to get a list of premium add-ons and also any add-on consider as Give add-on if hosted on `givewp` or has `GiveWP` or `WordImpress`
