### ISSUE TITLE
fix: prevent fatal error when refresh licenses

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#4176]
# Bug Report

## User Story
As an admin, I want to update the license without any issue.

## Current Behavior
Admin will get a fatal error if he is on WP <= 4.9.10
```
PHP Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /wp-includes/class-wp-list-util.php:150
Stack trace:
#0 /wp-includes/functions.php(3697): WP_List_Util->pluck('check_license', NULL)
#1 /wp-content/plugins/give/includes/misc-functions.php(2410): wp_list_pluck(Object(stdClass), 'check_license')
```

related ticket:
https://secure.helpscout.net/conversation/902058350/43406/
https://secure.helpscout.net/conversation/902220799/43422?folderId=672194
https://secure.helpscout.net/conversation/902155992/43413?folderId=672194

## Steps to Reproduce
1. Install WP 4.9.10
2. Add add-on license (maybe you will also get a fatal error when adding license)
3. Open license setting page

## Acceptance Criteria
- [x] I am not getting PHP fatal error when refresh license on WP <=4.9.10 or WP>4.9.10.

**Comment by mathetos** [comment]
I'm not sure but this ticket seems to suggest this error also happens on WP version 5.0.2
https://secure.helpscout.net/conversation/904914308/43578/

**Comment by DevinWalker** [comment]
@mathetos 	yes it occurs on that version as well. I've confirmed this resolves the underlying issue though.
