### ISSUE TITLE
fix: resolve fatal error incompatibility with Give and GS Logo Slider Pro

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#4183]
# Bug Report

## User Story

As a site admin, I want install both the GS Logo Slider Pro and Give without resulting in a fatal error.

## Current Behavior
When both plugins are activated a fatal error displays:

Fatal error: Uncaught Error: Call to undefined function get_plugins() in /app/public/wp-content/plugins/give/includes/misc-functions.php:786
Stack trace:
#0 /app/public/wp-content/plugins/give/includes/class-give-license-handler.php(482): give_get_plugins()
#1 /app/public/wp-content/plugins/give/includes/misc-functions.php(2498): Give_License::get_plugin_by_slug('give-currency-s...')
#2 /app/public/wp-includes/class-wp-hook.php(288): give_check_addon_updates(Object(stdClass))
#3 /app/public/wp-includes/plugin.php(208): WP_Hook->apply_filters(NULL, Array)
#4 /app/public/wp-includes/option.php(1815): apply_filters('pre_set_site_tr...', NULL, 'update_plugins')
#5 /app/public/wp-content/plugins/gs-logo-slider-pro/gsl-files/gs-plugins/lic/EDD_SL_GSLOGO_Plugin_Updater.php(3): set_site_transient('update_plugins', NULL)
#6 /app/public/wp-content/plugins/gs-logo-slider-pro/gsl-files/gs-plugins/lic/gs_logo_lic.php(18): include('/app/public/wp-...')
#7 /app/public/wp-content/plugins/gs-logo-slider-pro/gs-logo-slider-pro.php(53): req in /app/public/wp-content/plugins/give/includes/misc-functions.php on line 786

## Expected Behavior
I expect to use both plugins at the same time.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install the GS Logo Slider Pro plugin at the protected link below
2. View the fatal error that displays

## Visuals
![Screen Shot 2019-07-17 at 9 41 54 AM](https://user-images.githubusercontent.com/20672471/61380705-de8f0400-a877-11e9-8a72-940a68181ca6.png)

Here is the download to the plugin:
https://drive.google.com/open?id=1ADO6wsA2S6H6cHColBC35qRRikVInbs-

## Related
https://secure.helpscout.net/conversation/900899420/43297

## Acceptance Criteria

- [ ] Both plugins can be active without producing errors

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://loversfoundation.local
Site URL: http://loversfoundation.local
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: page
Page on Front: Home (#1327)
Page for Posts: Blog (#473)
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: loversfoundation.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.5.2
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: 2.5.2
Test Mode: Disabled
Currency Code: EUR
Currency Position: Before
Decimal Separator: ,
Thousands Separator: .
Success Page: http://loversfoundation.local/donatie-bevestiging/
Failure Page: http://loversfoundation.local/donatie-mislukt/
Donation History Page: http://loversfoundation.local/donatiegeschiedenis/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.2
All-in-One WP Migration: by ServMask – 6.97
Code Snippets: by Shea Bunge – 2.13.3
Contact Form 7: by Takayuki Miyoshi – 5.1.3
Counter Number Pro: by wpshopmart – 5.0
Counter Number Showcase: by wpshopmart – 1.1.4
Disable XML-RPC Pingback: by Samuel Aguilera – 1.2
Give - Annual Receipts: by GiveWP – 1.0.2
Give - Email Reports: by GiveWP – 1.1.3
Give - Form Field Manager: by GiveWP – 1.4.3
Give - MailChimp: by GiveWP – 1.4.4
Give - Mollie Gateway: by GiveWP – 1.2.2
Give - PDF Receipts: by GiveWP – 2.3.3
Give - Per Form Gateways: by GiveWP – 1.0.2
Give - Recurring Donations: by GiveWP – 1.8.13
GS Logo Slider PRO: by Golam Samdani – 2.0.10
Jetpack by WordPress.com: by Automattic – 7.5.2
Loco Translate: by Tim Whitlock – 2.3.0
Mailchimp for WooCommerce: by Mailchimp – 2.1.17
Mailchimp for WordPress: by ibericode – 4.5.2
Mollie Payments for WooCommerce: by Mollie – 5.1.8
NextScripts: SNAP Pro Upgrade Helper: by NextScripts – 1.5.9
NextScripts: Social Networks Auto-Poster: by NextScripts – 4.3.8
Page Builder by SiteOrigin: by SiteOrigin – 2.10.6
Pena Custom Widgets for SiteOrigin Page Builder Plugin: by Anariel Design – 1.0
PHP Compatibility Checker: by WP Engine – 1.4.7
Responsive WordPress Slider - Soliloquy Lite: by Soliloquy Team – 2.5.6
Shareaholic - Grow and Engage Your Audience: by Shareaholic – 8.13.6
SiteOrigin Widgets Bundle: by SiteOrigin – 1.15.7
Strong Testimonials: by MachoThemes – 2.39.1
The Events Calendar: by Modern Tribe, Inc. – 4.9.4
WooCommerce: by Automattic – 3.6.5
WooCommerce Blocks: by Automattic – 2.2.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.15
WooCommerce Services: by Automattic – 1.21.0
Wordfence Security: by Wordfence – 7.3.4
WPS Hide Login: by WPServeur, NicolasKulka, tabrisrp – 1.5.2.2

### Theme ###

Name: Pena Child
Version: 1.0.0
Author URL: http://www.anarieldesign.com/
Child Theme: Yes
Parent Theme Name: Pena
Parent Theme Version: 1.1.9
Parent Theme Author URL: https://www.anarieldesign.com/

</details>

**Comment by ravinderk** [comment]
@samsmith89 I noticed that a line of code which should be the comment on live add-on
![image](https://user-images.githubusercontent.com/1784821/61461714-db3a6c00-a98e-11e9-94ea-b2633852f6f8.png)

Please ask plugin user to reach out to  GS Logo Slider PRO Pro plugin developer

ref: https://www.loom.com/share/c3f1eeff2f9c47969129c2de9606e0fd
