### ISSUE TITLE
Invalid display (rounded) in emails

### ISSUE THREAD

**Issue by rvola** [impress-org/give#4190]
# Bug Report

## User Story

As a developer, I want get a fix so that the plugin works perfectly.

With the use of the "give-fee-recovery" extension and the payment gateway "Paypal standard - Don"

I noticed that the "amount" sign in the email has a rounding.
Here is the configuration of Paypal Standard:
Fee recovery = yes
fee percentegage = 2.90
additional fee amount = 0.30
currency: €

For a donation of 250 €, the amount of commission is: 7.78 €
The amount displayed in the donor's email is: "258.00 € (250.00 € donation + 8.00 € to help the bank transaction fees.)"

We would say that the extension has a rounding.
I tried with Stripe is everything works fine.

## Current Behavior
incorrect display of the commission amount in the email

## Expected Behavior
that the display in the email is the same as the calculation

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Visuals
![Capture-d’écran-2019-07-24-à-12 28 23](https://user-images.githubusercontent.com/6870615/61787407-064e1100-ae10-11e9-9c88-b8afd1ab18b9.jpg)
![Capture-d’écran-2019-07-24-à-12 37 18](https://user-images.githubusercontent.com/6870615/61787412-0817d480-ae10-11e9-9c16-7bc710e12abd.jpg)

**Comment by mikejhale** [comment]
Issue moved to [impress-org/give-fee-recovery #256](https://github.com/impress-org/give-fee-recovery/issues/256) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mikejhale** [comment]
Issue moved to [impress-org/give-fee-recovery #257](https://github.com/impress-org/give-fee-recovery/issues/257) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mikejhale** [comment]
Thank you for your submission, we're looking into this and have moved it to the appropriate add-on repository.
