### ISSUE TITLE
Stripe asks for the "State" field that is not useful and is not displayed

### ISSUE THREAD

**Issue by rvola** [impress-org/give#4191]
# Bug Report

## User Story

As a developer, I want get a fix so that the plugin works perfectly.

With the give-stripe version 2.2.0,

the form can not be validated.
JS error prevents execution with error:
"An invalid form control with name = 'card_state' is not focusable."

The configuration is in French and we do not have the form "State".

Through the console, we notice that the "State" field is mandatory.

## Current Behavior

Can not validate the donation form

## Expected Behavior
Can validate the form when "State" is not needed.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.1.8.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Visuals
![Capture-d’écran-2019-07-24-à-12 45 57](https://user-images.githubusercontent.com/6870615/61788007-58436680-ae11-11e9-8286-5d8f407a4e8f.jpg)

**Comment by DevinWalker** [comment]
Resolved in PR #4209
