### ISSUE TITLE
fix: resolve compatibility issues with Stripe and other Stripe based WordPress plugins

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#4193]
# Bug Report

## User Story
As a user, I want to ensure that there is no plugin conflict with Give core with basic version of Stripe so that the customer site doesn't get broken.

## Current Behavior
Currently, we noticed compatibility issues with EDD Stripe add-on and Give 2.5.0+

## Expected Behavior
I expect to have no compatibility issue with any Stripe WordPress plugin and Give 2.5.0+

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria
- [x] Implement manual installation of Stripe SDK
- [x] Test with EDD Stripe WordPress Plugin
- [x] Test with WP Full Stripe WordPress Plugin
- [x] Test with WP Simple Pay WordPress plugin
- [x] Test it on our staging site to ensure that the patch is working fine.

**Comment by mikejhale** [comment]
@mathetos Did additional testing with Gravity Forms Stripe and worked as expected.

**Comment by mehul0810** [comment]
Re-opening this issue due to customer reports as per slack discussion https://givewp.slack.com/archives/C0FAGC83C/p1564619203092900
