### ISSUE TITLE
fix: ensure requirement on state field is removed from hidden state field

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#4201]
# Bug Report

## User Story

As a site admin, I want my donors to be able to process donations in countries that don't require a state, and as a result, that field is hidden on page load.

In my Give settings, I've set my default country to Germany. This removes the state field from displaying on the donation form by default.

## Current Behavior

When my donor clicks submit, the processing circle quickly displays and they aren't redirected to PayPal.

If I remove the requirement from the State field with a custom code snippet the donation processes without issue.

Snippet here:
```
function give_dont_require_fields( $required_fields, $form_id ) {
	if(isset($required_fields['card_state'])) {
		unset($required_fields['card_state']);
	}
	return $required_fields;
}
add_filter( 'give_donation_form_required_fields', 'give_dont_require_fields', 10, 2 );

```
## Expected Behavior

I expect my donors to be able to process donations without having to add a custom code snippet.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version X.X.X.

## Steps to Reproduce

1. Set the default Country in Give to be Germany
2. Configure the PayPal gateway to require billing details 
3. Without using auto-populate, fill out the billing details fields.
4. Process the donation and see that it doesn't go through
5. View the console and see the error

## Visuals

<img width="231" alt="Screen Shot 2019-07-31 at 11 26 00 AM" src="https://user-images.githubusercontent.com/20672471/62226653-82080a80-b388-11e9-8f8b-e304cff70702.png">

Here's a screencast of me walking through the issue:
http://somup.com/cqiwome29z

## Related

https://secure.helpscout.net/conversation/911537366/44028

This bug may be related to this issue:
https://github.com/impress-org/give/issues/4144
## Acceptance Criteria

- [ ] Donors can process donations when the default country is set to Germany.
## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, in-progress, failed, acf-disabled, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, revoked, cancelled, abandoned, processing, preapproval, atum_pending, atum_completed, atum_ordered, atum_onthewayin, atum_receiving, atum_received, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.5.2
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access✔Renewal Receipt Email❌Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.5.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, Test Donation, PayPal Standard
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Active Give Add-ons ###

Give - Annual Receipts: ✔ Licensed – by GiveWP – 1.0.2
Give - Authorize.net Gateway: ✔ Licensed – by GiveWP – 1.4.6
Give - Braintree Gateway: ✔ Licensed – by GiveWP – 1.2.4
Give - CCAvenue Gateway: ✔ Licensed – by GiveWP – 1.0.4
Give - Currency Switcher: ✔ Licensed – by GiveWP – 1.3.2
Give - Donation Upsells for WooCommerce: ✔ Licensed – by GiveWP – 1.1.1
Give - Fee Recovery: ✔ Licensed – by GiveWP – 1.7.5
Give - Form Countdown: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Form Field Manager: ✔ Licensed – by GiveWP – 1.4.3
Give - Google Analytics Donation Tracking: ✔ Licensed – by GiveWP – 1.2.4
Give - MailChimp: ✔ Licensed – by GiveWP – 1.4.4
Give - Manual Donations: ✔ Licensed – by GiveWP – 1.4.5
Give - Mollie Gateway: ✔ Licensed – by GiveWP – 1.2.3
Give - PayPal Pro Gateway: ✔ Licensed – by GiveWP – 1.2.2
Give - Paytm Gateway: ✔ Licensed – by GiveWP – 1.1.0
Give - PDF Receipts: ✔ Licensed – by GiveWP – 2.3.4
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.9.0
Give - Square: ❌ Unlicensed – by GiveWP – 1.0.3
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.2.0
Give - Tributes: ✔ Licensed – by GiveWP – 1.5.4

### Other Active Plugins ###

Advanced Custom Fields: by Elliot Condon – 5.8.1
All-in-One WP Migration: by ServMask – 6.97
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.5.8.9
ATUM Multi-Inventory: by Stock Management Labs™ – 1.2.1.6
EWWW Image Optimizer: by Exactly WWW – 4.8.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Jetpack by WordPress.com: by Automattic – 7.5.2
Notification: by BracketSpace – 6.0.4
Query Monitor: by John Blackbourn – 3.3.6
Show Current Template: by JOTAKI Taisuke – 0.3.0
Transients Manager: by Pippin Williamson – 1.7.7
User Role Editor: by Vladimir Garagulya – 4.51.1
WooCommerce: by Automattic – 3.6.5

### Inactive Plugins ###

Amelia: by TMS – 1.4.4
Classic Editor: by WordPress Contributors – 1.5
Cookie Notice: by dFactory – 1.2.46
GDPR Cookie Consent: by WebToffee – 1.7.7
GDPR Cookie Consent Banner: by termly – 2.3.14
Give - Email Reports: by GiveWP – 1.1.3
Give - Gift Aid: by GiveWP – 1.2.2
Give - GoCardless Gateway: by GiveWP – 1.3.3
Give - Razorpay: by GiveWP – 1.2.1
WordPress Importer: by wordpressdotorg – 0.6.4
WP Business Reviews: by Impress.org – 1.2.0

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0

### Theme ###

Name: Twenty Seventeen
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by mikejhale** [comment]
Also see #4191
