### ISSUE TITLE
Request for help: Redirect of admin settings page (for an Add-On)

### ISSUE THREAD

**Issue by deckerweb** [impress-org/give#4222]
Hi, I am currently finishing development of a new free Add-On for GiveWP regarding the Toolbar: it connects GiveWP with my Toolbar Extras plugin :-)

For one small issue I would need your help, it is regarding your settings API.
I have created a new settings tab, which works fine. However, I don't want a new tab section to appear as a page but rather redirect to my existing admin page of Toolbar Extras plugin.
In general I know how make a safe redirect in WP Admin but don't know how to make this within your settings API. That is my problem currently.

Why would I do that?
In my opinion having a dedicated settings tab in GiveWP settings makes total sense, as users would expect it there, it helps for user guidance. But when they click the tab they should land on my (existing) admin page.

This is my current working code for the tab alone:
```
add_filter( 'give-settings_get_settings_pages', 'ddw_tbexgive_givewp_settings_tab', 10, 1 );
function ddw_tbexgive_givewp_settings_tab( $settings ) {

	$settings[] = include TBEXGIVE_PLUGIN_DIR . '/includes/admin/givewp-settings-tab.php';

	return $settings;
}
```

and:

```
if ( ! class_exists( 'DDW_TBEXGIVE_GiveWP_Settings_Tab' ) ) :

	/**
	 * DDW_TBEXGIVE_GiveWP_Settings_Tab.
	 *
	 * @sine 1.0.0
	 */
	class DDW_TBEXGIVE_GiveWP_Settings_Tab extends Give_Settings_Page {

		/**
		 * Constructor.
		 *
		 * @since 1.0.0
		 */
		public function __construct() {
			$this->id    = 'tbexgive';
			$this->label = __( 'Toolbar Extras', 'toolbar-extras-givewp' );

			parent::__construct();
		}

		/**
		 * Get settings array.
		 *
		 * @since  1.0.0
		 * @access public
		 *
		 * @return array
		 */
		public function get_settings() {

			$is_global = true; // Set Global flag.

			$settings = array();

			/**
			 * Filter the TBEX Give settings.
			 *
			 * @since  1.0.0
			 *
			 * @param  array $settings
			 */
			$settings = apply_filters( 'give_toolbar_get_settings_' . $this->id, $settings );

			// Output.
			return $settings;
		}

	}

endif;

return new DDW_TBEXGIVE_GiveWP_Settings_Tab();
```

Thanks a lot in advance!

**Comment by ravinderk** [comment]
@deckerweb thanks for reaching us.

As per code, We are creating tab link internally before rendering tabs and the third party developer can not modify these link, so you have to handle redirect yourself.
https://github.com/impress-org/give/blob/743dd851ca937b7ba5e6004fdee786da162b735e/includes/admin/views/html-admin-settings.php#L72


Let us know if you have another query.

**Comment by deckerweb** [comment]
@ravinderk 
Thanks for your quick response - makes total sense, was not aware of it.
I have an idea for another solution not touching your settings.
Thanks again! :)
