### ISSUE TITLE
fix: typos in readme.md

### ISSUE THREAD

**Issue by mikejhale** [impress-org/give#4234]
## Current Behavior
1. Under **Local Development** section, item 4 says `Run composer install to set up dependancies`
2. In the Local Development section, under Available Commands the Read More link in the npm run test scripts links to a non-existent branch/file.

## Expected Behavior
1. Should be `dependencies`
2. Link should be to the file in the Master branch: https://github.com/impress-org/give/tree/master/tests/e2e

**Comment by DevinWalker** [comment]
Merged
