### ISSUE TITLE
refactor: remove the "Transaction Failed" Page

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#647]
Currently this page is automatically created when Give is activated. It only contains a simple static sentence saying the transaction failed without any explanation.

I haven't encountered being redirected to this page hardly ever. But I wonder if we should have a [give_failed_donation] shortcode which we could then pass error messages to in order to provide more valuable feedback to the donor on what exactly happened.

@DevinWalker What are your thoughts?

**Comment by DevinWalker** [comment]
My thoughts are we should look into a) deprecating this page b) repurposing it like you say so it's more useful. I would like to deprecate it if that wouldn't be too difficult.

**Comment by mathetos** [comment]
Just realized that this page still is necessary, specifically for PayPal Standard. 

Currently, a donor can hit "Donate" then go to PayPal.com, and there they could hit "Cancel payment". That currently redirects to the website to the "Failed Transaction" page. 

But the donation didn't "fail". They purposely cancelled it. The wording should be totally different and organizations would want to get their feedback on why they failed, etc.

## New Suggestions
1) Look for other ways that donors will land on this Failed Transactions page.
2) If the ONLY way they land on it is by Cancelling their Donation, then we need to change the wording so it's clear what the purpose of this page is exactly.
3) If there are multiple ways that they can land on this page, then we need to separate out the truly FAILED transactions, from the CANCELLED transactions and route them to different pages with different text.

**Comment by mikejhale** [comment]
This will be addressed in new UI
